services:
  postgresql:
    container_name: postgres
    image: postgres:17
    ports:
      - '${DB_PORT:-5432}:5432'
    volumes:
      - db:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=${DB_USER:-flowintel}
      - POSTGRES_PASSWORD=${DB_PASSWORD:-your_secure_password_here}
      - POSTGRES_DB=${DB_NAME:-flowintel}
    networks:
      - net
    restart: unless-stopped

  valkey:
    container_name: valkey
    image: valkey/valkey
    ports:
      - '${VALKEY_PORT:-6379}:6379'
    volumes:
      - valkey-data:/data
    networks:
      - net


  flowintel:
    image: ghcr.io/flowintel/flowintel:latest
    container_name: flowintel
    command: bash -i ./launch.sh -ld
    ports:
      - '${APP_PORT:-7006}:7006'
    environment:
      - SECRET_KEY=${FLOWINTEL_SECRET_KEY:-SECRET_KEY_ENV_VAR_NOT_SET}
      #
      - DB_HOST=${DB_HOST:-postgresql}
      - DB_PORT=${DB_PORT:-5432}
      - DB_USER=${DB_USER:-flowintel}
      - DB_PASSWORD=${DB_PASSWORD:-your_secure_password_here}
      - DB_NAME=${DB_NAME:-flowintel}
      - DB_DIALECT=${FLOWINTEL_DB_DIALECT:-postgresql}
      - DB_DRIVER=${FLOWINTEL_DB_DRIVER:-psycopg2}
      #
      - VALKEY_IP=${VALKEY_IP:-valkey}
      - ADMIN_FIRST_NAME=${FLOWINTEL_ADMIN_FIRST_NAME:-admin}
      - ADMIN_LAST_NAME=${FLOWINTEL_ADMIN_LAST_NAME:-admin}
      - ADMIN_MAIL=${FLOWINTEL_ADMIN_MAIL:-admin@admin.admin}
      - ADMIN_PASSWORD=${FLOWINTEL_ADMIN_PASSWORD:-admin}
      - BOT_MAIL=${FLOWINTEL_BOT_MAIL:-neo@admin.admin}
      #
      - FLASKENV=${FLASKENV:-production}
    networks:
      - net
    depends_on:
      - postgresql
      - valkey

    volumes:
      - flowintel-data:/var/lib/flowintel

volumes:
  db:
  flowintel-data:
  valkey-data:

networks:
  net:
    driver: bridge
