services:
  mariadb:
    container_name: mariadb
    image: mariadb:12
    ports:
      - '${DB_PORT:-3306}:3306'
    volumes:
      - db:/var/lib/mariadb/data
    environment:
      - MYSQL_ROOT_PASSWORD=${DB_PASSWORD:-flowintel}
      - MYSQL_USER=${DB_USER:-flowintel}
      - MYSQL_PASSWORD=${DB_USER:-your_secure_password_here}
      - MYSQL_DATABASE=${DB_NAME:-flowintel}
    networks:
      - net
    restart: unless-stopped

  valkey:
    container_name: valkey
    image: valkey/valkey
    ports:
      - '${VALKEY_PORT:-6379}:6379'
    volumes:
      - valkey-data:/data
    networks:
      - net


  flowintel:
    image: ghcr.io/flowintel/flowintel:latest
    container_name: flowintel
    command: bash -i ./launch.sh -ld
    ports:
      - '${APP_PORT:-7006}:7006'
    environment:
      - DB_HOST=${DB_HOST:-mariadb}
      - DB_PORT=${DB_PORT:-3306}
      - DB_USER=${DB_USER:-flowintel}
      - DB_PASSWORD=${DB_PASSWORD:-flowintel}
      - DB_NAME=${DB_NAME:-flowintel}
      - VALKEY_IP=${VALKEY_IP:-valkey}
    networks:
      - net
    depends_on:
      - mariadb
      - valkey

    volumes:
      - flowintel-data:/var/lib/flowintel

volumes:
  db:
  flowintel-data:
  valkey-data:

networks:
  net:
    driver: bridge
