services:
  mariadb:
    container_name: mariadb
    image: mariadb:12
    # TODO
    # https://mariadb.com/docs/server/server-management/automated-mariadb-deployment-and-administration/docker-and-mariadb/mariadb-server-docker-official-image-environment-variables#using-_file-environment-variables-for-secrets
    #
    ports:
      - '${DB_PORT:-3306}:3306'
    volumes:
      - db:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=${DB_ROOT_PASSWORD:-mysql}
      - MYSQL_USER=${DB_USER:-flowintel}
      - MYSQL_PASSWORD=${DB_PASSWORD:-your_secure_password_here}
      - MYSQL_DATABASE=${DB_NAME:-flowintel}
    networks:
      - net
    restart: unless-stopped

  valkey:
    container_name: valkey
    image: valkey/valkey
    ports:
      - '${VALKEY_PORT:-6379}:6379'
    volumes:
      - valkey-data:/data
    networks:
      - net


  flowintel:
    image: flowintel_maria:latest
    container_name: flowintel
    command: bash -i ./launch.sh -ld
    ports:
      - '${APP_PORT:-7006}:7006'
    environment:
      - SECRET_KEY=${FLOWINTEL_SECRET_KEY:-SECRET_KEY_ENV_VAR_NOT_SET}
      #
      - DB_HOST=${DB_HOST:-mariadb}
      - DB_PORT=${DB_PORT:-3306}
      - DB_USER=${DB_USER:-flowintel}
      - DB_PASSWORD=${DB_PASSWORD:-your_secure_password_here}
      - DB_NAME=${DB_NAME:-flowintel}
      - DB_DIALECT=${DB_DIALECT:-mysql}
      - DB_DRIVER=${DB_DRIVER:-pymysql}
      #
      - VALKEY_IP=${VALKEY_IP:-valkey}
      - ADMIN_FIRST_NAME=${FLOWINTEL_ADMIN_FIRST_NAME:-admin}
      - ADMIN_LAST_NAME=${FLOWINTEL_ADMIN_LAST_NAME:-admin}
      - ADMIN_MAIL=${FLOWINTEL_ADMIN_MAIL:-admin@admin.admin}
      - ADMIN_PASSWORD=${FLOWINTEL_ADMIN_PASSWORD:-admin}
      - BOT_MAIL=${FLOWINTEL_BOT_MAIL:-neo@admin.admin}
      #
      - FLASKENV=${FLASKENV:-production}
      - FLASK_PORT=${FLOWINTEL_APP_PORT:-7006}
      - FLASK_URL=${FLASK_URL:-0.0.0.0}
    networks:
      - net
    depends_on:
      - mariadb
      - valkey

    volumes:
      - flowintel-data:/var/lib/flowintel

volumes:
  db:
  flowintel-data:
  valkey-data:

networks:
  net:
    driver: bridge
    enable_ipv6: true
    ipam:
      config:
        - subnet: 10.0.0.0/24
        - subnet: fd31:50:0:1::/64