"""Create or delete community test cases via the REST API.

Requires a running Flowintel instance and the .community-api-keys.json
file generated by init_community_data.py.

Cases are created by a CaseAdmin, tasks by a Queuer (which triggers
TASK_REQUESTED status and approver notifications in privileged cases).
Deletion uses the CaseAdmin keys from the API keys file.

Usage:
    python3 tests/testdata/init_community_cases.py create
    python3 tests/testdata/init_community_cases.py create --url http://host:port
    python3 tests/testdata/init_community_cases.py delete
"""

import argparse
import json
import os
import random
import string
import sys

import requests

SCRIPT_DIR = os.path.dirname(os.path.abspath(__file__))
API_KEYS_FILE = os.path.join(SCRIPT_DIR, ".community-api-keys.json")
DEFAULT_URL = "http://127.0.0.1:7006"

_CASE_TAG = "[community-test-case]"


# ---------------------------------------------------------------------------
# Helpers
# ---------------------------------------------------------------------------

def _headers(api_key):
    return {"X-API-KEY": api_key, "Content-Type": "application/json"}


def _error_msg(resp):
    try:
        return resp.json().get("message", resp.text)
    except Exception:
        return f"HTTP {resp.status_code}: {resp.text[:200]}"


def _random_prefix():
    return "TC-" + "".join(random.choices(string.ascii_uppercase + string.digits, k=5))


def _load_api_keys():
    if not os.path.exists(API_KEYS_FILE):
        print(f"Error: {API_KEYS_FILE} not found.")
        print("Run init_community_data.py create first.")
        sys.exit(1)
    with open(API_KEYS_FILE) as f:
        return json.load(f)


def _keys_by_org_and_role(api_keys):
    mapping = {}
    for entry in api_keys:
        org = entry["org"]
        role = entry["role"]
        mapping.setdefault(org, {}).setdefault(role, []).append(entry)
    return mapping


def _find_key(keys_map, org, role):
    entries = keys_map.get(org, {}).get(role, [])
    if not entries:
        return None
    return entries[0]


def _find_assignees(keys_map, org):
    return keys_map.get(org, {}).get("Queuer", [])


def _parse_deadline(deadline_str):
    """Split 'YYYY-MM-DD HH:MM' into (deadline_date, deadline_time) for the API.

    The API expects deadline_date as '%Y-%m-%d' and deadline_time as '%H-%M'
    (dash, not colon).
    """
    if not deadline_str:
        return None, None
    parts = deadline_str.strip().split(" ", 1)
    date_part = parts[0]
    time_part = parts[1].replace(":", "-") if len(parts) > 1 else None
    return date_part, time_part


def _load_case_files():
    files = sorted(
        f for f in os.listdir(SCRIPT_DIR)
        if f.startswith("case_") and f.endswith(".json")
    )
    return [os.path.join(SCRIPT_DIR, f) for f in files]


# ---------------------------------------------------------------------------
# Create / Delete
# ---------------------------------------------------------------------------

def _create_case(base_url, case_data, case_admin_key):
    deadline_date, deadline_time = _parse_deadline(case_data.get("deadline"))

    body = {
        "title": case_data["title"],
        "description": case_data.get("description") or "",
        "tags": case_data.get("tags", []),
        "clusters": case_data.get("clusters", []),
    }
    if deadline_date:
        body["deadline_date"] = deadline_date
    if deadline_time:
        body["deadline_time"] = deadline_time
    if case_data.get("time_required"):
        body["time_required"] = case_data["time_required"]

    resp = requests.post(
        f"{base_url}/api/case/create",
        headers=_headers(case_admin_key),
        json=body,
    )
    if resp.status_code != 201:
        print(f"    Error creating case: {_error_msg(resp)}")
        return None
    return resp.json()["case_id"]


def _set_privileged(base_url, case_id, case_admin_key):
    resp = requests.post(
        f"{base_url}/api/case/{case_id}/edit",
        headers=_headers(case_admin_key),
        json={"privileged_case": True},
    )
    if resp.status_code != 200:
        print(f"    Warning: could not set privileged flag: {_error_msg(resp)}")


def _add_case_note(base_url, case_id, note, api_key):
    requests.post(
        f"{base_url}/api/case/{case_id}/modify_case_note",
        headers=_headers(api_key),
        json={"note": note},
    )


def _create_task(base_url, case_id, task_data, api_key):
    deadline_date, deadline_time = _parse_deadline(task_data.get("deadline"))

    body = {
        "title": task_data["title"],
        "description": task_data.get("description") or "",
        "tags": task_data.get("tags", []),
        "clusters": task_data.get("clusters", []),
    }
    if deadline_date:
        body["deadline_date"] = deadline_date
    if deadline_time:
        body["deadline_time"] = deadline_time
    if task_data.get("time_required"):
        body["time_required"] = task_data["time_required"]

    resp = requests.post(
        f"{base_url}/api/case/{case_id}/create_task",
        headers=_headers(api_key),
        json=body,
    )
    if resp.status_code != 201:
        print(f"    Error creating task '{task_data['title']}': {_error_msg(resp)}")
        return None
    return resp.json()["task_id"]


def _add_task_notes(base_url, task_id, notes, api_key):
    for note_data in notes:
        text = note_data.get("note", "")
        if not text:
            continue
        requests.post(
            f"{base_url}/api/task/{task_id}/create_note",
            headers=_headers(api_key),
            json={"note": text},
        )


def _add_subtasks(base_url, task_id, subtasks, api_key):
    for sub in subtasks:
        requests.post(
            f"{base_url}/api/task/{task_id}/create_subtask",
            headers=_headers(api_key),
            json={"description": sub["description"]},
        )


def _add_url_tools(base_url, task_id, urls_tools, api_key):
    for ut in urls_tools:
        requests.post(
            f"{base_url}/api/task/{task_id}/create_url_tool",
            headers=_headers(api_key),
            json={"name": ut["name"]},
        )


def _assign_users(base_url, task_id, user_ids, api_key):
    if not user_ids:
        return
    requests.post(
        f"{base_url}/api/task/{task_id}/assign_users",
        headers=_headers(api_key),
        json={"users_id": user_ids},
    )


def _create_misp_objects(base_url, case_id, misp_objects, api_key):
    for obj in misp_objects:
        body = {
            "object-template": {
                "uuid": obj.get("template_uuid", ""),
                "name": obj.get("name", ""),
            },
            "attributes": obj.get("attributes", []),
        }
        resp = requests.post(
            f"{base_url}/api/case/{case_id}/create_misp_object",
            headers=_headers(api_key),
            json=body,
        )
        if resp.status_code != 200:
            print(f"    Warning: MISP object '{obj.get('name')}' failed: {_error_msg(resp)}")


def create(base_url):
    """Import test cases from case_*.json files via the REST API."""
    api_keys = _load_api_keys()
    keys_map = _keys_by_org_and_role(api_keys)

    orgs = list(keys_map.keys())
    if not orgs:
        print("Error: no community organisations found in API keys file.")
        sys.exit(1)

    case_files = _load_case_files()
    if not case_files:
        print("No case_*.json files found in tests/testdata/.")
        sys.exit(1)

    created_cases = []

    print("Importing test cases...")
    for filepath in case_files:
        filename = os.path.basename(filepath)
        with open(filepath) as f:
            case_data = json.load(f)

        # Pick a random community org for this case
        chosen_org = random.choice(orgs)
        case_admin_entry = _find_key(keys_map, chosen_org, "CaseAdmin")
        if not case_admin_entry:
            print(f"  Skipped {filename}: no CaseAdmin found for {chosen_org}")
            continue

        queuer_entries = keys_map.get(chosen_org, {}).get("Queuer", [])
        if not queuer_entries:
            print(f"  Skipped {filename}: no Queuer found for {chosen_org}")
            continue
        queuer_entry = queuer_entries[0]

        # Randomise title so re-runs create distinct cases
        prefix = _random_prefix()
        case_data["title"] = f"{prefix} {case_data['title']}"

        # Mark description for later identification/deletion
        desc = case_data.get("description") or ""
        case_data["description"] = f"{_CASE_TAG} {desc}"

        # 1. Create the case as CaseAdmin
        case_id = _create_case(base_url, case_data, case_admin_entry["api_key"])
        if not case_id:
            continue
        print(f"  Created case: {case_data['title']} (org: {chosen_org})")

        # 2. Set as privileged so queuer tasks get TASK_REQUESTED status
        _set_privileged(base_url, case_id, case_admin_entry["api_key"])

        # 3. Set case-level note if present
        if case_data.get("notes"):
            _add_case_note(base_url, case_id, case_data["notes"], case_admin_entry["api_key"])

        # 4. Create tasks as the Queuer (triggers TASK_REQUESTED + notifications)
        assignees = _find_assignees(keys_map, chosen_org)
        for task_data in case_data.get("tasks", []):
            task_id = _create_task(base_url, case_id, task_data, queuer_entry["api_key"])
            if not task_id:
                continue
            print(f"    Task: {task_data['title']}")

            # Notes, subtasks, url_tools — created by the same queuer
            _add_task_notes(base_url, task_id, task_data.get("notes", []), queuer_entry["api_key"])
            _add_subtasks(base_url, task_id, task_data.get("subtasks", []), queuer_entry["api_key"])
            _add_url_tools(base_url, task_id, task_data.get("urls_tools", []), queuer_entry["api_key"])

            # Assign a random community user from the same org
            if assignees:
                chosen = random.choice(assignees)
                _assign_users(base_url, task_id, [chosen["user_id"]], case_admin_entry["api_key"])

        # 5. MISP objects — created by the CaseAdmin
        _create_misp_objects(base_url, case_id, case_data.get("misp-objects", []), case_admin_entry["api_key"])

        created_cases.append((case_data["title"], chosen_org, len(case_data.get("tasks", []))))

    _print_overview(created_cases)


def delete(base_url):
    """Delete all community test cases (identified by the description tag)."""
    api_keys = _load_api_keys()
    keys_map = _keys_by_org_and_role(api_keys)

    # Collect CaseAdmin keys from every org
    case_admin_keys = [
        entry["api_key"]
        for org in keys_map
        for entry in keys_map[org].get("CaseAdmin", [])
    ]
    if not case_admin_keys:
        print("Error: no CaseAdmin keys found in the API keys file.")
        sys.exit(1)

    # Gather community case IDs visible to any CaseAdmin
    community_cases = {}  # id -> title
    for key in case_admin_keys:
        resp = requests.get(
            f"{base_url}/api/case/all",
            headers=_headers(key),
        )
        if resp.status_code != 200:
            continue
        for c in resp.json().get("cases", []):
            if (c.get("description") or "").startswith(_CASE_TAG):
                community_cases[c["id"]] = c["title"]

    if not community_cases:
        print("No community test cases found.")
        return

    print(f"Deleting {len(community_cases)} community test case(s)...")
    for cid, title in community_cases.items():
        deleted = False
        for key in case_admin_keys:
            resp = requests.get(
                f"{base_url}/api/case/{cid}/delete",
                headers=_headers(key),
            )
            if resp.status_code == 200:
                print(f"  Deleted: {title}")
                deleted = True
                break
        if not deleted:
            print(f"  Error: {title} - {_error_msg(resp)}")

    print("Done.")


def _print_overview(created_cases):
    if not created_cases:
        return
    print(f"\n--- Community test cases overview ---")
    print(f"  {'Case title':<45} {'Organisation':<25} {'Tasks'}")
    print(f"  {'-'*45} {'-'*25} {'-'*6}")
    for title, org, task_count in created_cases:
        print(f"  {title:<45} {org:<25} {task_count}")
    print()


# ---------------------------------------------------------------------------
# CLI
# ---------------------------------------------------------------------------

if __name__ == "__main__":
    parser = argparse.ArgumentParser(
        description="Manage community test cases via the Flowintel REST API"
    )
    parser.add_argument("action", choices=["create", "delete"])
    parser.add_argument("--url", default=DEFAULT_URL,
                        help=f"Base URL (default: {DEFAULT_URL})")
    args = parser.parse_args()

    if args.action == "create":
        create(args.url)
    else:
        delete(args.url)
