"""Initial migration

Revision ID: 345ddbac01e2
Revises: 
Create Date: 2026-06-16 18:29:54.663789

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '345ddbac01e2'
down_revision = None
branch_labels = ("postgres", "sqlite",)
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('alert',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('case_id', sa.Integer(), nullable=True),
    sa.Column('message', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=30), nullable=True),
    sa.Column('creation_date', sa.DateTime(), nullable=True),
    sa.Column('is_read', sa.Boolean(), nullable=True),
    sa.Column('webhook_url', sa.String(length=255), nullable=True),
    sa.Column('webhook_status', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('alert', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_alert_case_id'), ['case_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_alert_creation_date'), ['creation_date'], unique=False)
        batch_op.create_index(batch_op.f('ix_alert_message'), ['message'], unique=False)

    op.create_table('case',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('uuid', sa.String(length=36), nullable=True),
    sa.Column('title', sa.String(length=255), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('creation_date', sa.DateTime(), nullable=True),
    sa.Column('deadline', sa.DateTime(), nullable=True),
    sa.Column('last_modif', sa.DateTime(), nullable=True),
    sa.Column('finish_date', sa.DateTime(), nullable=True),
    sa.Column('status_id', sa.Integer(), nullable=True),
    sa.Column('completed', sa.Boolean(), nullable=True),
    sa.Column('owner_org_id', sa.Integer(), nullable=True),
    sa.Column('notif_deadline_id', sa.Integer(), nullable=True),
    sa.Column('recurring_date', sa.DateTime(), nullable=True),
    sa.Column('recurring_type', sa.String(length=30), nullable=True),
    sa.Column('nb_tasks', sa.Integer(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('hedgedoc_url', sa.String(length=255), nullable=True),
    sa.Column('time_required', sa.String(length=64), nullable=True),
    sa.Column('is_private', sa.Boolean(), nullable=True),
    sa.Column('privileged_case', sa.Boolean(), nullable=True),
    sa.Column('ticket_id', sa.String(length=36), nullable=True),
    sa.Column('is_updated_from_misp', sa.Boolean(), nullable=True),
    sa.Column('computer_assistate_report', sa.Text(), nullable=True),
    sa.Column('computer_assistate_model', sa.String(length=36), nullable=True),
    sa.Column('computer_assistate_prompt', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('case', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_case_creation_date'), ['creation_date'], unique=False)
        batch_op.create_index(batch_op.f('ix_case_deadline'), ['deadline'], unique=False)
        batch_op.create_index(batch_op.f('ix_case_finish_date'), ['finish_date'], unique=False)
        batch_op.create_index(batch_op.f('ix_case_is_private'), ['is_private'], unique=False)
        batch_op.create_index(batch_op.f('ix_case_last_modif'), ['last_modif'], unique=False)
        batch_op.create_index(batch_op.f('ix_case_nb_tasks'), ['nb_tasks'], unique=False)
        batch_op.create_index(batch_op.f('ix_case_notif_deadline_id'), ['notif_deadline_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_case_owner_org_id'), ['owner_org_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_case_privileged_case'), ['privileged_case'], unique=False)
        batch_op.create_index(batch_op.f('ix_case_recurring_date'), ['recurring_date'], unique=False)
        batch_op.create_index(batch_op.f('ix_case_recurring_type'), ['recurring_type'], unique=False)
        batch_op.create_index(batch_op.f('ix_case_status_id'), ['status_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_case_uuid'), ['uuid'], unique=False)

    op.create_table('case__connector__instance',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('case_id', sa.Integer(), nullable=True),
    sa.Column('instance_id', sa.Integer(), nullable=True),
    sa.Column('identifier', sa.String(length=64), nullable=True),
    sa.Column('is_updating_case', sa.Boolean(), nullable=True),
    sa.Column('last_sync', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('case__connector__instance', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_case__connector__instance_case_id'), ['case_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_case__connector__instance_instance_id'), ['instance_id'], unique=False)

    op.create_table('case__custom__tags',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('case_id', sa.Integer(), nullable=True),
    sa.Column('custom_tag_id', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('case__custom__tags', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_case__custom__tags_case_id'), ['case_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_case__custom__tags_custom_tag_id'), ['custom_tag_id'], unique=False)

    op.create_table('case__galaxy__tags',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('cluster_id', sa.Integer(), nullable=True),
    sa.Column('case_id', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('case__galaxy__tags', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_case__galaxy__tags_case_id'), ['case_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_case__galaxy__tags_cluster_id'), ['cluster_id'], unique=False)

    op.create_table('case__link__case',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('case_id_1', sa.Integer(), nullable=True),
    sa.Column('case_id_2', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('case__link__case', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_case__link__case_case_id_1'), ['case_id_1'], unique=False)
        batch_op.create_index(batch_op.f('ix_case__link__case_case_id_2'), ['case_id_2'], unique=False)

    op.create_table('case__misp__object',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('case_id', sa.Integer(), nullable=True),
    sa.Column('template_uuid', sa.String(length=36), nullable=True),
    sa.Column('name', sa.String(length=64), nullable=True),
    sa.Column('creation_date', sa.DateTime(), nullable=True),
    sa.Column('last_modif', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('case__misp__object', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_case__misp__object_case_id'), ['case_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_case__misp__object_creation_date'), ['creation_date'], unique=False)
        batch_op.create_index(batch_op.f('ix_case__misp__object_last_modif'), ['last_modif'], unique=False)
        batch_op.create_index(batch_op.f('ix_case__misp__object_template_uuid'), ['template_uuid'], unique=False)

    op.create_table('case__note__template__model',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('case_id', sa.Integer(), nullable=True),
    sa.Column('note_template_id', sa.Integer(), nullable=True),
    sa.Column('values', sa.JSON(), nullable=True),
    sa.Column('content', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('case__note__template__model', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_case__note__template__model_case_id'), ['case_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_case__note__template__model_note_template_id'), ['note_template_id'], unique=False)

    op.create_table('case__org',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('case_id', sa.Integer(), nullable=True),
    sa.Column('org_id', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('case__tags',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('tag_id', sa.Integer(), nullable=True),
    sa.Column('case_id', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('case__tags', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_case__tags_case_id'), ['case_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_case__tags_tag_id'), ['tag_id'], unique=False)

    op.create_table('case__template',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('uuid', sa.String(length=36), nullable=True),
    sa.Column('title', sa.String(length=255), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('last_modif', sa.DateTime(), nullable=True),
    sa.Column('time_required', sa.String(length=64), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('version', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('case__template', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_case__template_last_modif'), ['last_modif'], unique=False)
        batch_op.create_index(batch_op.f('ix_case__template_title'), ['title'], unique=False)
        batch_op.create_index(batch_op.f('ix_case__template_uuid'), ['uuid'], unique=False)

    op.create_table('case__template__connector__instance',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('case_template_id', sa.Integer(), nullable=True),
    sa.Column('connector_instance_id', sa.Integer(), nullable=True),
    sa.Column('identifier', sa.String(length=64), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('case__template__connector__instance', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_case__template__connector__instance_case_template_id'), ['case_template_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_case__template__connector__instance_connector_instance_id'), ['connector_instance_id'], unique=False)

    op.create_table('case__template__custom__tags',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('case_template_id', sa.Integer(), nullable=True),
    sa.Column('custom_tag_id', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('case__template__custom__tags', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_case__template__custom__tags_case_template_id'), ['case_template_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_case__template__custom__tags_custom_tag_id'), ['custom_tag_id'], unique=False)

    op.create_table('case__template__galaxy__tags',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('cluster_id', sa.Integer(), nullable=True),
    sa.Column('template_id', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('case__template__galaxy__tags', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_case__template__galaxy__tags_cluster_id'), ['cluster_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_case__template__galaxy__tags_template_id'), ['template_id'], unique=False)

    op.create_table('case__template__tags',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('tag_id', sa.Integer(), nullable=True),
    sa.Column('case_id', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('case__template__tags', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_case__template__tags_case_id'), ['case_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_case__template__tags_tag_id'), ['tag_id'], unique=False)

    op.create_table('case__timeline__event',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('case_id', sa.Integer(), nullable=True),
    sa.Column('date_text', sa.String(length=64), nullable=False),
    sa.Column('date_parsed', sa.DateTime(), nullable=True),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('misp_object_id', sa.Integer(), nullable=True),
    sa.Column('creation_date', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('case__timeline__event', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_case__timeline__event_case_id'), ['case_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_case__timeline__event_creation_date'), ['creation_date'], unique=False)

    op.create_table('configurable__fields',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=64), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('configurable__fields', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_configurable__fields_name'), ['name'], unique=True)

    op.create_table('connector',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=64), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('uuid', sa.String(length=36), nullable=True),
    sa.Column('icon_id', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('connector', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_connector_icon_id'), ['icon_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_connector_name'), ['name'], unique=False)
        batch_op.create_index(batch_op.f('ix_connector_uuid'), ['uuid'], unique=False)

    op.create_table('connector__icon',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=64), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('uuid', sa.String(length=36), nullable=True),
    sa.Column('file_icon_id', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('connector__icon', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_connector__icon_file_icon_id'), ['file_icon_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_connector__icon_name'), ['name'], unique=True)
        batch_op.create_index(batch_op.f('ix_connector__icon_uuid'), ['uuid'], unique=False)

    op.create_table('connector__sync__log',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('case_id', sa.Integer(), nullable=True),
    sa.Column('case_connector_instance_id', sa.Integer(), nullable=True),
    sa.Column('direction', sa.String(length=10), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.Column('status', sa.String(length=10), nullable=True),
    sa.Column('message', sa.Text(), nullable=True),
    sa.Column('objects_synced', sa.Integer(), nullable=True),
    sa.Column('objects_failed', sa.Integer(), nullable=True),
    sa.Column('details', sa.JSON(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('connector__sync__log', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_connector__sync__log_case_connector_instance_id'), ['case_connector_instance_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_connector__sync__log_case_id'), ['case_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_connector__sync__log_timestamp'), ['timestamp'], unique=False)

    op.create_table('custom__tags',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=64), nullable=True),
    sa.Column('color', sa.String(length=20), nullable=True),
    sa.Column('icon', sa.String(length=255), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('custom__tags', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_custom__tags_color'), ['color'], unique=False)
        batch_op.create_index(batch_op.f('ix_custom__tags_icon'), ['icon'], unique=False)
        batch_op.create_index(batch_op.f('ix_custom__tags_name'), ['name'], unique=True)

    op.create_table('galaxy',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=64), nullable=True),
    sa.Column('uuid', sa.String(length=36), nullable=True),
    sa.Column('version', sa.Integer(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('icon', sa.String(length=64), nullable=True),
    sa.Column('type', sa.String(length=64), nullable=True),
    sa.Column('exclude', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('galaxy', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_galaxy_uuid'), ['uuid'], unique=False)
        batch_op.create_index(batch_op.f('ix_galaxy_version'), ['version'], unique=False)

    op.create_table('icon__file',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=64), nullable=True),
    sa.Column('uuid', sa.String(length=36), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('icon__file', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_icon__file_name'), ['name'], unique=True)
        batch_op.create_index(batch_op.f('ix_icon__file_uuid'), ['uuid'], unique=False)

    op.create_table('login__event',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('login_date', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('login__event', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_login__event_login_date'), ['login_date'], unique=False)
        batch_op.create_index(batch_op.f('ix_login__event_user_id'), ['user_id'], unique=False)

    op.create_table('misp__attribute__instance__uuid',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('instance_id', sa.Integer(), nullable=True),
    sa.Column('misp_attribute_id', sa.Integer(), nullable=True),
    sa.Column('attribute_instance_uuid', sa.String(length=36), nullable=True),
    sa.Column('case_id', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('misp__attribute__instance__uuid', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_misp__attribute__instance__uuid_attribute_instance_uuid'), ['attribute_instance_uuid'], unique=False)
        batch_op.create_index(batch_op.f('ix_misp__attribute__instance__uuid_case_id'), ['case_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_misp__attribute__instance__uuid_instance_id'), ['instance_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_misp__attribute__instance__uuid_misp_attribute_id'), ['misp_attribute_id'], unique=False)

    op.create_table('misp__module',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=64), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('input_attr', sa.Text(), nullable=True),
    sa.Column('version', sa.String(length=15), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('misp__module', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_misp__module_name'), ['name'], unique=True)

    op.create_table('misp__module__config',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('module_id', sa.Integer(), nullable=True),
    sa.Column('config_id', sa.Integer(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('value', sa.String(length=36), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('misp__module__config', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_misp__module__config_config_id'), ['config_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_misp__module__config_module_id'), ['module_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_misp__module__config_user_id'), ['user_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_misp__module__config_value'), ['value'], unique=False)

    op.create_table('misp__module__result',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('uuid', sa.String(length=36), nullable=True),
    sa.Column('modules_list', sa.String(length=255), nullable=True),
    sa.Column('query_enter', sa.Text(), nullable=True),
    sa.Column('input_query', sa.Text(), nullable=True),
    sa.Column('result', sa.Text(), nullable=True),
    sa.Column('nb_errors', sa.Integer(), nullable=True),
    sa.Column('query_date', sa.DateTime(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('misp__module__result', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_misp__module__result_nb_errors'), ['nb_errors'], unique=False)
        batch_op.create_index(batch_op.f('ix_misp__module__result_query_date'), ['query_date'], unique=False)
        batch_op.create_index(batch_op.f('ix_misp__module__result_user_id'), ['user_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_misp__module__result_uuid'), ['uuid'], unique=True)

    op.create_table('misp__object__instance__uuid',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('instance_id', sa.Integer(), nullable=True),
    sa.Column('misp_object_id', sa.Integer(), nullable=True),
    sa.Column('object_instance_uuid', sa.String(length=36), nullable=True),
    sa.Column('case_id', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('misp__object__instance__uuid', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_misp__object__instance__uuid_case_id'), ['case_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_misp__object__instance__uuid_instance_id'), ['instance_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_misp__object__instance__uuid_misp_object_id'), ['misp_object_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_misp__object__instance__uuid_object_instance_uuid'), ['object_instance_uuid'], unique=False)

    op.create_table('note__template__model',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('uuid', sa.String(length=36), nullable=True),
    sa.Column('author', sa.Integer(), nullable=True),
    sa.Column('title', sa.String(length=255), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('content', sa.Text(), nullable=True),
    sa.Column('params', sa.JSON(), nullable=True),
    sa.Column('creation_date', sa.DateTime(), nullable=True),
    sa.Column('last_modif', sa.DateTime(), nullable=True),
    sa.Column('version', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('note__template__model', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_note__template__model_author'), ['author'], unique=False)
        batch_op.create_index(batch_op.f('ix_note__template__model_creation_date'), ['creation_date'], unique=False)
        batch_op.create_index(batch_op.f('ix_note__template__model_last_modif'), ['last_modif'], unique=False)
        batch_op.create_index(batch_op.f('ix_note__template__model_uuid'), ['uuid'], unique=False)
        batch_op.create_index(batch_op.f('ix_note__template__model_version'), ['version'], unique=False)

    op.create_table('notification',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('message', sa.Text(), nullable=True),
    sa.Column('is_read', sa.Boolean(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('case_id', sa.Integer(), nullable=True),
    sa.Column('creation_date', sa.DateTime(), nullable=True),
    sa.Column('for_deadline', sa.DateTime(), nullable=True),
    sa.Column('read_date', sa.DateTime(), nullable=True),
    sa.Column('html_icon', sa.String(length=60), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('notification', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_notification_case_id'), ['case_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_notification_creation_date'), ['creation_date'], unique=False)
        batch_op.create_index(batch_op.f('ix_notification_for_deadline'), ['for_deadline'], unique=False)
        batch_op.create_index(batch_op.f('ix_notification_html_icon'), ['html_icon'], unique=False)
        batch_op.create_index(batch_op.f('ix_notification_message'), ['message'], unique=False)
        batch_op.create_index(batch_op.f('ix_notification_read_date'), ['read_date'], unique=False)
        batch_op.create_index(batch_op.f('ix_notification_user_id'), ['user_id'], unique=False)

    op.create_table('org',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=64), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('uuid', sa.String(length=36), nullable=True),
    sa.Column('default_org', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('org', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_org_name'), ['name'], unique=False)
        batch_op.create_index(batch_op.f('ix_org_uuid'), ['uuid'], unique=False)

    op.create_table('recurring__notification',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('case_id', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('recurring__notification', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_recurring__notification_case_id'), ['case_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_recurring__notification_user_id'), ['user_id'], unique=False)

    op.create_table('role',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=64), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('admin', sa.Boolean(), nullable=True),
    sa.Column('read_only', sa.Boolean(), nullable=True),
    sa.Column('org_admin', sa.Boolean(), nullable=True),
    sa.Column('case_admin', sa.Boolean(), nullable=True),
    sa.Column('queue_admin', sa.Boolean(), nullable=True),
    sa.Column('queuer', sa.Boolean(), nullable=True),
    sa.Column('audit_viewer', sa.Boolean(), nullable=True),
    sa.Column('template_editor', sa.Boolean(), nullable=False),
    sa.Column('misp_editor', sa.Boolean(), nullable=False),
    sa.Column('importer', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('role', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_role_name'), ['name'], unique=True)

    op.create_table('rulezet__rule',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('uuid', sa.String(length=36), nullable=True),
    sa.Column('case_id', sa.Integer(), nullable=True),
    sa.Column('instance_id', sa.Integer(), nullable=True),
    sa.Column('remote_id', sa.String(length=36), nullable=True),
    sa.Column('title', sa.String(length=255), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('format', sa.String(length=128), nullable=True),
    sa.Column('content', sa.Text(), nullable=True),
    sa.Column('version', sa.String(length=64), nullable=True),
    sa.Column('date_added', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('rulezet__rule', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_rulezet__rule_case_id'), ['case_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_rulezet__rule_date_added'), ['date_added'], unique=False)
        batch_op.create_index(batch_op.f('ix_rulezet__rule_instance_id'), ['instance_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_rulezet__rule_remote_id'), ['remote_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_rulezet__rule_uuid'), ['uuid'], unique=False)

    op.create_table('status',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=30), nullable=True),
    sa.Column('bootstrap_style', sa.String(length=30), nullable=True),
    sa.Column('order', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('status', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_status_bootstrap_style'), ['bootstrap_style'], unique=False)
        batch_op.create_index(batch_op.f('ix_status_name'), ['name'], unique=True)
        batch_op.create_index(batch_op.f('ix_status_order'), ['order'], unique=False)

    op.create_table('task__connector__instance',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('task_id', sa.Integer(), nullable=True),
    sa.Column('instance_id', sa.Integer(), nullable=True),
    sa.Column('identifier', sa.String(length=64), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('task__connector__instance', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_task__connector__instance_instance_id'), ['instance_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_task__connector__instance_task_id'), ['task_id'], unique=False)

    op.create_table('task__custom__tags',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('task_id', sa.Integer(), nullable=True),
    sa.Column('custom_tag_id', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('task__custom__tags', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_task__custom__tags_custom_tag_id'), ['custom_tag_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_task__custom__tags_task_id'), ['task_id'], unique=False)

    op.create_table('task__galaxy',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('galaxy_id', sa.Integer(), nullable=True),
    sa.Column('task_id', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('task__galaxy', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_task__galaxy_galaxy_id'), ['galaxy_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_task__galaxy_task_id'), ['task_id'], unique=False)

    op.create_table('task__galaxy__tags',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('cluster_id', sa.Integer(), nullable=True),
    sa.Column('task_id', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('task__galaxy__tags', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_task__galaxy__tags_cluster_id'), ['cluster_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_task__galaxy__tags_task_id'), ['task_id'], unique=False)

    op.create_table('task__tags',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('tag_id', sa.Integer(), nullable=True),
    sa.Column('task_id', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('task__tags', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_task__tags_tag_id'), ['tag_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_task__tags_task_id'), ['task_id'], unique=False)

    op.create_table('task__template',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('uuid', sa.String(length=36), nullable=True),
    sa.Column('title', sa.String(length=255), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('nb_notes', sa.Integer(), nullable=True),
    sa.Column('last_modif', sa.DateTime(), nullable=True),
    sa.Column('time_required', sa.String(length=64), nullable=True),
    sa.Column('version', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('task__template', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_task__template_last_modif'), ['last_modif'], unique=False)
        batch_op.create_index(batch_op.f('ix_task__template_nb_notes'), ['nb_notes'], unique=False)
        batch_op.create_index(batch_op.f('ix_task__template_title'), ['title'], unique=False)
        batch_op.create_index(batch_op.f('ix_task__template_uuid'), ['uuid'], unique=False)

    op.create_table('task__template__custom__tags',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('task_template_id', sa.Integer(), nullable=True),
    sa.Column('custom_tag_id', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('task__template__custom__tags', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_task__template__custom__tags_custom_tag_id'), ['custom_tag_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_task__template__custom__tags_task_template_id'), ['task_template_id'], unique=False)

    op.create_table('task__template__galaxy',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('galaxy_id', sa.Integer(), nullable=True),
    sa.Column('template_id', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('task__template__galaxy', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_task__template__galaxy_galaxy_id'), ['galaxy_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_task__template__galaxy_template_id'), ['template_id'], unique=False)

    op.create_table('task__template__galaxy__tags',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('cluster_id', sa.Integer(), nullable=True),
    sa.Column('template_id', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('task__template__galaxy__tags', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_task__template__galaxy__tags_cluster_id'), ['cluster_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_task__template__galaxy__tags_template_id'), ['template_id'], unique=False)

    op.create_table('task__template__tags',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('tag_id', sa.Integer(), nullable=True),
    sa.Column('task_id', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('task__template__tags', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_task__template__tags_tag_id'), ['tag_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_task__template__tags_task_id'), ['task_id'], unique=False)

    op.create_table('task__user',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('task_id', sa.Integer(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('taxonomy',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('uuid', sa.String(length=36), nullable=True),
    sa.Column('name', sa.String(length=64), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('exclude', sa.Boolean(), nullable=True),
    sa.Column('version', sa.String(length=15), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('taxonomy', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_taxonomy_uuid'), ['uuid'], unique=False)

    op.create_table('template__repository',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('uuid', sa.String(length=36), nullable=True),
    sa.Column('name', sa.String(length=256), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('url', sa.String(length=512), nullable=True),
    sa.Column('local_path', sa.String(length=512), nullable=True),
    sa.Column('version', sa.Integer(), nullable=True),
    sa.Column('creation_date', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('template__repository', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_template__repository_creation_date'), ['creation_date'], unique=False)
        batch_op.create_index(batch_op.f('ix_template__repository_name'), ['name'], unique=False)
        batch_op.create_index(batch_op.f('ix_template__repository_uuid'), ['uuid'], unique=True)

    op.create_table('user__connector__instance',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('instance_id', sa.Integer(), nullable=True),
    sa.Column('api_key', sa.String(length=100), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('user__connector__instance', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_user__connector__instance_api_key'), ['api_key'], unique=False)
        batch_op.create_index(batch_op.f('ix_user__connector__instance_instance_id'), ['instance_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_user__connector__instance_user_id'), ['user_id'], unique=False)

    op.create_table('case__task__template',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('case_id', sa.Integer(), nullable=True),
    sa.Column('task_id', sa.Integer(), nullable=True),
    sa.Column('case_order_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['case_id'], ['case__template.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['task_id'], ['task__template.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('case__task__template', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_case__task__template_case_id'), ['case_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_case__task__template_case_order_id'), ['case_order_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_case__task__template_task_id'), ['task_id'], unique=False)

    op.create_table('case__timeline__event__link',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('case_id', sa.Integer(), nullable=True),
    sa.Column('source_event_id', sa.Integer(), nullable=True),
    sa.Column('target_event_id', sa.Integer(), nullable=True),
    sa.Column('label', sa.String(length=128), nullable=True),
    sa.ForeignKeyConstraint(['source_event_id'], ['case__timeline__event.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['target_event_id'], ['case__timeline__event.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('case__timeline__event__link', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_case__timeline__event__link_case_id'), ['case_id'], unique=False)

    op.create_table('cluster',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=255), nullable=True),
    sa.Column('uuid', sa.String(length=36), nullable=True),
    sa.Column('version', sa.Integer(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('meta', sa.Text().with_variant(mysql.LONGTEXT(), 'mariadb').with_variant(mysql.LONGTEXT(), 'mysql'), nullable=True),
    sa.Column('exclude', sa.Boolean(), nullable=True),
    sa.Column('tag', sa.Text(), nullable=True),
    sa.Column('galaxy_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['galaxy_id'], ['galaxy.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('cluster', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_cluster_uuid'), ['uuid'], unique=False)
        batch_op.create_index(batch_op.f('ix_cluster_version'), ['version'], unique=False)

    op.create_table('connector__instance',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=64), nullable=True),
    sa.Column('url', sa.String(length=64), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('uuid', sa.String(length=36), nullable=True),
    sa.Column('type', sa.String(length=36), nullable=True),
    sa.Column('connector_id', sa.Integer(), nullable=True),
    sa.Column('global_api_key', sa.String(length=100), nullable=True),
    sa.ForeignKeyConstraint(['connector_id'], ['connector.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('connector__instance', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_connector__instance_global_api_key'), ['global_api_key'], unique=False)
        batch_op.create_index(batch_op.f('ix_connector__instance_name'), ['name'], unique=False)
        batch_op.create_index(batch_op.f('ix_connector__instance_type'), ['type'], unique=False)
        batch_op.create_index(batch_op.f('ix_connector__instance_url'), ['url'], unique=False)
        batch_op.create_index(batch_op.f('ix_connector__instance_uuid'), ['uuid'], unique=False)

    op.create_table('misp__attribute',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('case_misp_object_id', sa.Integer(), nullable=True),
    sa.Column('value', sa.String(length=255), nullable=True),
    sa.Column('type', sa.String(length=64), nullable=True),
    sa.Column('object_relation', sa.String(length=64), nullable=True),
    sa.Column('first_seen', sa.DateTime(), nullable=True),
    sa.Column('last_seen', sa.DateTime(), nullable=True),
    sa.Column('comment', sa.Text(), nullable=True),
    sa.Column('ids_flag', sa.Boolean(), nullable=True),
    sa.Column('creation_date', sa.DateTime(), nullable=True),
    sa.Column('last_modif', sa.DateTime(), nullable=True),
    sa.Column('disable_correlation', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['case_misp_object_id'], ['case__misp__object.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('misp__attribute', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_misp__attribute_creation_date'), ['creation_date'], unique=False)
        batch_op.create_index(batch_op.f('ix_misp__attribute_first_seen'), ['first_seen'], unique=False)
        batch_op.create_index(batch_op.f('ix_misp__attribute_last_modif'), ['last_modif'], unique=False)
        batch_op.create_index(batch_op.f('ix_misp__attribute_last_seen'), ['last_seen'], unique=False)
        batch_op.create_index(batch_op.f('ix_misp__attribute_object_relation'), ['object_relation'], unique=False)
        batch_op.create_index(batch_op.f('ix_misp__attribute_type'), ['type'], unique=False)
        batch_op.create_index(batch_op.f('ix_misp__attribute_value'), ['value'], unique=False)

    op.create_table('note__template',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('uuid', sa.String(length=36), nullable=True),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('template_id', sa.Integer(), nullable=True),
    sa.Column('template_order_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['template_id'], ['task__template.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('note__template', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_note__template_template_order_id'), ['template_order_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_note__template_uuid'), ['uuid'], unique=False)

    op.create_table('subtask__template',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('template_id', sa.Integer(), nullable=True),
    sa.Column('completed', sa.Boolean(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['template_id'], ['task__template.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('tags',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('uuid', sa.String(length=36), nullable=True),
    sa.Column('name', sa.Text(), nullable=True),
    sa.Column('color', sa.String(length=64), nullable=True),
    sa.Column('exclude', sa.Boolean(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('taxonomy_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['taxonomy_id'], ['taxonomy.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('tags', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_tags_uuid'), ['uuid'], unique=False)

    op.create_table('task',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('uuid', sa.String(length=36), nullable=True),
    sa.Column('title', sa.String(length=255), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('creation_date', sa.DateTime(), nullable=True),
    sa.Column('deadline', sa.DateTime(), nullable=True),
    sa.Column('last_modif', sa.DateTime(), nullable=True),
    sa.Column('finish_date', sa.DateTime(), nullable=True),
    sa.Column('case_id', sa.Integer(), nullable=True),
    sa.Column('status_id', sa.Integer(), nullable=True),
    sa.Column('completed', sa.Boolean(), nullable=True),
    sa.Column('notif_deadline_id', sa.Integer(), nullable=True),
    sa.Column('case_order_id', sa.Integer(), nullable=True),
    sa.Column('nb_notes', sa.Integer(), nullable=True),
    sa.Column('time_required', sa.String(length=64), nullable=True),
    sa.ForeignKeyConstraint(['case_id'], ['case.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('task', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_task_case_order_id'), ['case_order_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_task_creation_date'), ['creation_date'], unique=False)
        batch_op.create_index(batch_op.f('ix_task_deadline'), ['deadline'], unique=False)
        batch_op.create_index(batch_op.f('ix_task_finish_date'), ['finish_date'], unique=False)
        batch_op.create_index(batch_op.f('ix_task_last_modif'), ['last_modif'], unique=False)
        batch_op.create_index(batch_op.f('ix_task_nb_notes'), ['nb_notes'], unique=False)
        batch_op.create_index(batch_op.f('ix_task_notif_deadline_id'), ['notif_deadline_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_task_status_id'), ['status_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_task_uuid'), ['uuid'], unique=False)

    op.create_table('task__template__url__tool',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('task_id', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(length=64), nullable=True),
    sa.ForeignKeyConstraint(['task_id'], ['task__template.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('task__template__url__tool', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_task__template__url__tool_name'), ['name'], unique=False)

    op.create_table('template__repository_entry',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('repository_id', sa.Integer(), nullable=True),
    sa.Column('uuid', sa.String(length=36), nullable=True),
    sa.Column('title', sa.String(length=256), nullable=True),
    sa.Column('type', sa.String(length=8), nullable=True),
    sa.Column('version', sa.Integer(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('download_url', sa.String(length=512), nullable=True),
    sa.Column('remote_sha', sa.String(length=64), nullable=True),
    sa.Column('parent_case_uuid', sa.String(length=36), nullable=True),
    sa.Column('parent_case_title', sa.String(length=256), nullable=True),
    sa.Column('last_synced', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['repository_id'], ['template__repository.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('template__repository_entry', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_template__repository_entry_parent_case_uuid'), ['parent_case_uuid'], unique=False)
        batch_op.create_index(batch_op.f('ix_template__repository_entry_repository_id'), ['repository_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_template__repository_entry_type'), ['type'], unique=False)
        batch_op.create_index(batch_op.f('ix_template__repository_entry_uuid'), ['uuid'], unique=False)

    op.create_table('user',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('first_name', sa.String(length=64), nullable=True),
    sa.Column('last_name', sa.String(length=64), nullable=True),
    sa.Column('nickname', sa.String(length=64), nullable=True),
    sa.Column('email', sa.String(length=64), nullable=True),
    sa.Column('matrix_id', sa.String(length=64), nullable=True),
    sa.Column('role_id', sa.Integer(), nullable=True),
    sa.Column('password_hash', sa.String(length=165), nullable=True),
    sa.Column('api_key', sa.String(length=60), nullable=True),
    sa.Column('org_id', sa.Integer(), nullable=True),
    sa.Column('creation_date', sa.DateTime(), nullable=True),
    sa.Column('auth_provider', sa.String(length=32), server_default='local', nullable=False),
    sa.Column('last_login', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['org_id'], ['org.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_user_api_key'), ['api_key'], unique=False)
        batch_op.create_index(batch_op.f('ix_user_creation_date'), ['creation_date'], unique=False)
        batch_op.create_index(batch_op.f('ix_user_email'), ['email'], unique=True)
        batch_op.create_index(batch_op.f('ix_user_first_name'), ['first_name'], unique=False)
        batch_op.create_index(batch_op.f('ix_user_last_login'), ['last_login'], unique=False)
        batch_op.create_index(batch_op.f('ix_user_last_name'), ['last_name'], unique=False)
        batch_op.create_index(batch_op.f('ix_user_matrix_id'), ['matrix_id'], unique=True)
        batch_op.create_index(batch_op.f('ix_user_nickname'), ['nickname'], unique=False)
        batch_op.create_index(batch_op.f('ix_user_role_id'), ['role_id'], unique=False)

    op.create_table('chat_conversation',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('uuid', sa.String(length=36), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('chat_conversation', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_chat_conversation_user_id'), ['user_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_chat_conversation_uuid'), ['uuid'], unique=True)

    op.create_table('file',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=64), nullable=True),
    sa.Column('task_id', sa.Integer(), nullable=True),
    sa.Column('case_id', sa.Integer(), nullable=True),
    sa.Column('uuid', sa.String(length=36), nullable=True),
    sa.Column('upload_date', sa.DateTime(), nullable=True),
    sa.Column('file_size', sa.Integer(), nullable=True),
    sa.Column('file_type', sa.String(length=100), nullable=True),
    sa.ForeignKeyConstraint(['case_id'], ['case.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['task_id'], ['task.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('file', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_file_name'), ['name'], unique=False)
        batch_op.create_index(batch_op.f('ix_file_uuid'), ['uuid'], unique=True)

    op.create_table('note',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('uuid', sa.String(length=36), nullable=True),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('task_id', sa.Integer(), nullable=True),
    sa.Column('task_order_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['task_id'], ['task.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('note', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_note_task_order_id'), ['task_order_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_note_uuid'), ['uuid'], unique=False)

    op.create_table('subtask',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('task_id', sa.Integer(), nullable=True),
    sa.Column('completed', sa.Boolean(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('task_order_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['task_id'], ['task.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('subtask', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_subtask_task_order_id'), ['task_order_id'], unique=False)

    op.create_table('task__external__reference',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('task_id', sa.Integer(), nullable=True),
    sa.Column('url', sa.String(length=255), nullable=True),
    sa.Column('uuid', sa.String(length=36), nullable=True),
    sa.ForeignKeyConstraint(['task_id'], ['task.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('task__external__reference', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_task__external__reference_url'), ['url'], unique=False)
        batch_op.create_index(batch_op.f('ix_task__external__reference_uuid'), ['uuid'], unique=False)

    op.create_table('task__misp__object',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('task_id', sa.Integer(), nullable=True),
    sa.Column('misp_object_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['misp_object_id'], ['case__misp__object.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['task_id'], ['task.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('task__misp__object', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_task__misp__object_misp_object_id'), ['misp_object_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_task__misp__object_task_id'), ['task_id'], unique=False)

    op.create_table('task__url__tool',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('task_id', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(length=64), nullable=True),
    sa.Column('uuid', sa.String(length=36), nullable=True),
    sa.ForeignKeyConstraint(['task_id'], ['task.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('task__url__tool', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_task__url__tool_name'), ['name'], unique=False)
        batch_op.create_index(batch_op.f('ix_task__url__tool_uuid'), ['uuid'], unique=False)

    op.create_table('chat_message',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('conversation_id', sa.Integer(), nullable=False),
    sa.Column('role', sa.String(length=10), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('model_name', sa.String(length=100), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['conversation_id'], ['chat_conversation.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('chat_message', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_chat_message_conversation_id'), ['conversation_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('chat_message', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_chat_message_conversation_id'))

    op.drop_table('chat_message')
    with op.batch_alter_table('task__url__tool', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_task__url__tool_uuid'))
        batch_op.drop_index(batch_op.f('ix_task__url__tool_name'))

    op.drop_table('task__url__tool')
    with op.batch_alter_table('task__misp__object', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_task__misp__object_task_id'))
        batch_op.drop_index(batch_op.f('ix_task__misp__object_misp_object_id'))

    op.drop_table('task__misp__object')
    with op.batch_alter_table('task__external__reference', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_task__external__reference_uuid'))
        batch_op.drop_index(batch_op.f('ix_task__external__reference_url'))

    op.drop_table('task__external__reference')
    with op.batch_alter_table('subtask', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_subtask_task_order_id'))

    op.drop_table('subtask')
    with op.batch_alter_table('note', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_note_uuid'))
        batch_op.drop_index(batch_op.f('ix_note_task_order_id'))

    op.drop_table('note')
    with op.batch_alter_table('file', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_file_uuid'))
        batch_op.drop_index(batch_op.f('ix_file_name'))

    op.drop_table('file')
    with op.batch_alter_table('chat_conversation', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_chat_conversation_uuid'))
        batch_op.drop_index(batch_op.f('ix_chat_conversation_user_id'))

    op.drop_table('chat_conversation')
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_user_role_id'))
        batch_op.drop_index(batch_op.f('ix_user_nickname'))
        batch_op.drop_index(batch_op.f('ix_user_matrix_id'))
        batch_op.drop_index(batch_op.f('ix_user_last_name'))
        batch_op.drop_index(batch_op.f('ix_user_last_login'))
        batch_op.drop_index(batch_op.f('ix_user_first_name'))
        batch_op.drop_index(batch_op.f('ix_user_email'))
        batch_op.drop_index(batch_op.f('ix_user_creation_date'))
        batch_op.drop_index(batch_op.f('ix_user_api_key'))

    op.drop_table('user')
    with op.batch_alter_table('template__repository_entry', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_template__repository_entry_uuid'))
        batch_op.drop_index(batch_op.f('ix_template__repository_entry_type'))
        batch_op.drop_index(batch_op.f('ix_template__repository_entry_repository_id'))
        batch_op.drop_index(batch_op.f('ix_template__repository_entry_parent_case_uuid'))

    op.drop_table('template__repository_entry')
    with op.batch_alter_table('task__template__url__tool', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_task__template__url__tool_name'))

    op.drop_table('task__template__url__tool')
    with op.batch_alter_table('task', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_task_uuid'))
        batch_op.drop_index(batch_op.f('ix_task_status_id'))
        batch_op.drop_index(batch_op.f('ix_task_notif_deadline_id'))
        batch_op.drop_index(batch_op.f('ix_task_nb_notes'))
        batch_op.drop_index(batch_op.f('ix_task_last_modif'))
        batch_op.drop_index(batch_op.f('ix_task_finish_date'))
        batch_op.drop_index(batch_op.f('ix_task_deadline'))
        batch_op.drop_index(batch_op.f('ix_task_creation_date'))
        batch_op.drop_index(batch_op.f('ix_task_case_order_id'))

    op.drop_table('task')
    with op.batch_alter_table('tags', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_tags_uuid'))

    op.drop_table('tags')
    op.drop_table('subtask__template')
    with op.batch_alter_table('note__template', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_note__template_uuid'))
        batch_op.drop_index(batch_op.f('ix_note__template_template_order_id'))

    op.drop_table('note__template')
    with op.batch_alter_table('misp__attribute', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_misp__attribute_value'))
        batch_op.drop_index(batch_op.f('ix_misp__attribute_type'))
        batch_op.drop_index(batch_op.f('ix_misp__attribute_object_relation'))
        batch_op.drop_index(batch_op.f('ix_misp__attribute_last_seen'))
        batch_op.drop_index(batch_op.f('ix_misp__attribute_last_modif'))
        batch_op.drop_index(batch_op.f('ix_misp__attribute_first_seen'))
        batch_op.drop_index(batch_op.f('ix_misp__attribute_creation_date'))

    op.drop_table('misp__attribute')
    with op.batch_alter_table('connector__instance', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_connector__instance_uuid'))
        batch_op.drop_index(batch_op.f('ix_connector__instance_url'))
        batch_op.drop_index(batch_op.f('ix_connector__instance_type'))
        batch_op.drop_index(batch_op.f('ix_connector__instance_name'))
        batch_op.drop_index(batch_op.f('ix_connector__instance_global_api_key'))

    op.drop_table('connector__instance')
    with op.batch_alter_table('cluster', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_cluster_version'))
        batch_op.drop_index(batch_op.f('ix_cluster_uuid'))

    op.drop_table('cluster')
    with op.batch_alter_table('case__timeline__event__link', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_case__timeline__event__link_case_id'))

    op.drop_table('case__timeline__event__link')
    with op.batch_alter_table('case__task__template', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_case__task__template_task_id'))
        batch_op.drop_index(batch_op.f('ix_case__task__template_case_order_id'))
        batch_op.drop_index(batch_op.f('ix_case__task__template_case_id'))

    op.drop_table('case__task__template')
    with op.batch_alter_table('user__connector__instance', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_user__connector__instance_user_id'))
        batch_op.drop_index(batch_op.f('ix_user__connector__instance_instance_id'))
        batch_op.drop_index(batch_op.f('ix_user__connector__instance_api_key'))

    op.drop_table('user__connector__instance')
    with op.batch_alter_table('template__repository', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_template__repository_uuid'))
        batch_op.drop_index(batch_op.f('ix_template__repository_name'))
        batch_op.drop_index(batch_op.f('ix_template__repository_creation_date'))

    op.drop_table('template__repository')
    with op.batch_alter_table('taxonomy', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_taxonomy_uuid'))

    op.drop_table('taxonomy')
    op.drop_table('task__user')
    with op.batch_alter_table('task__template__tags', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_task__template__tags_task_id'))
        batch_op.drop_index(batch_op.f('ix_task__template__tags_tag_id'))

    op.drop_table('task__template__tags')
    with op.batch_alter_table('task__template__galaxy__tags', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_task__template__galaxy__tags_template_id'))
        batch_op.drop_index(batch_op.f('ix_task__template__galaxy__tags_cluster_id'))

    op.drop_table('task__template__galaxy__tags')
    with op.batch_alter_table('task__template__galaxy', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_task__template__galaxy_template_id'))
        batch_op.drop_index(batch_op.f('ix_task__template__galaxy_galaxy_id'))

    op.drop_table('task__template__galaxy')
    with op.batch_alter_table('task__template__custom__tags', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_task__template__custom__tags_task_template_id'))
        batch_op.drop_index(batch_op.f('ix_task__template__custom__tags_custom_tag_id'))

    op.drop_table('task__template__custom__tags')
    with op.batch_alter_table('task__template', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_task__template_uuid'))
        batch_op.drop_index(batch_op.f('ix_task__template_title'))
        batch_op.drop_index(batch_op.f('ix_task__template_nb_notes'))
        batch_op.drop_index(batch_op.f('ix_task__template_last_modif'))

    op.drop_table('task__template')
    with op.batch_alter_table('task__tags', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_task__tags_task_id'))
        batch_op.drop_index(batch_op.f('ix_task__tags_tag_id'))

    op.drop_table('task__tags')
    with op.batch_alter_table('task__galaxy__tags', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_task__galaxy__tags_task_id'))
        batch_op.drop_index(batch_op.f('ix_task__galaxy__tags_cluster_id'))

    op.drop_table('task__galaxy__tags')
    with op.batch_alter_table('task__galaxy', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_task__galaxy_task_id'))
        batch_op.drop_index(batch_op.f('ix_task__galaxy_galaxy_id'))

    op.drop_table('task__galaxy')
    with op.batch_alter_table('task__custom__tags', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_task__custom__tags_task_id'))
        batch_op.drop_index(batch_op.f('ix_task__custom__tags_custom_tag_id'))

    op.drop_table('task__custom__tags')
    with op.batch_alter_table('task__connector__instance', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_task__connector__instance_task_id'))
        batch_op.drop_index(batch_op.f('ix_task__connector__instance_instance_id'))

    op.drop_table('task__connector__instance')
    with op.batch_alter_table('status', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_status_order'))
        batch_op.drop_index(batch_op.f('ix_status_name'))
        batch_op.drop_index(batch_op.f('ix_status_bootstrap_style'))

    op.drop_table('status')
    with op.batch_alter_table('rulezet__rule', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_rulezet__rule_uuid'))
        batch_op.drop_index(batch_op.f('ix_rulezet__rule_remote_id'))
        batch_op.drop_index(batch_op.f('ix_rulezet__rule_instance_id'))
        batch_op.drop_index(batch_op.f('ix_rulezet__rule_date_added'))
        batch_op.drop_index(batch_op.f('ix_rulezet__rule_case_id'))

    op.drop_table('rulezet__rule')
    with op.batch_alter_table('role', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_role_name'))

    op.drop_table('role')
    with op.batch_alter_table('recurring__notification', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_recurring__notification_user_id'))
        batch_op.drop_index(batch_op.f('ix_recurring__notification_case_id'))

    op.drop_table('recurring__notification')
    with op.batch_alter_table('org', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_org_uuid'))
        batch_op.drop_index(batch_op.f('ix_org_name'))

    op.drop_table('org')
    with op.batch_alter_table('notification', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_notification_user_id'))
        batch_op.drop_index(batch_op.f('ix_notification_read_date'))
        batch_op.drop_index(batch_op.f('ix_notification_message'))
        batch_op.drop_index(batch_op.f('ix_notification_html_icon'))
        batch_op.drop_index(batch_op.f('ix_notification_for_deadline'))
        batch_op.drop_index(batch_op.f('ix_notification_creation_date'))
        batch_op.drop_index(batch_op.f('ix_notification_case_id'))

    op.drop_table('notification')
    with op.batch_alter_table('note__template__model', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_note__template__model_version'))
        batch_op.drop_index(batch_op.f('ix_note__template__model_uuid'))
        batch_op.drop_index(batch_op.f('ix_note__template__model_last_modif'))
        batch_op.drop_index(batch_op.f('ix_note__template__model_creation_date'))
        batch_op.drop_index(batch_op.f('ix_note__template__model_author'))

    op.drop_table('note__template__model')
    with op.batch_alter_table('misp__object__instance__uuid', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_misp__object__instance__uuid_object_instance_uuid'))
        batch_op.drop_index(batch_op.f('ix_misp__object__instance__uuid_misp_object_id'))
        batch_op.drop_index(batch_op.f('ix_misp__object__instance__uuid_instance_id'))
        batch_op.drop_index(batch_op.f('ix_misp__object__instance__uuid_case_id'))

    op.drop_table('misp__object__instance__uuid')
    with op.batch_alter_table('misp__module__result', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_misp__module__result_uuid'))
        batch_op.drop_index(batch_op.f('ix_misp__module__result_user_id'))
        batch_op.drop_index(batch_op.f('ix_misp__module__result_query_date'))
        batch_op.drop_index(batch_op.f('ix_misp__module__result_nb_errors'))

    op.drop_table('misp__module__result')
    with op.batch_alter_table('misp__module__config', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_misp__module__config_value'))
        batch_op.drop_index(batch_op.f('ix_misp__module__config_user_id'))
        batch_op.drop_index(batch_op.f('ix_misp__module__config_module_id'))
        batch_op.drop_index(batch_op.f('ix_misp__module__config_config_id'))

    op.drop_table('misp__module__config')
    with op.batch_alter_table('misp__module', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_misp__module_name'))

    op.drop_table('misp__module')
    with op.batch_alter_table('misp__attribute__instance__uuid', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_misp__attribute__instance__uuid_misp_attribute_id'))
        batch_op.drop_index(batch_op.f('ix_misp__attribute__instance__uuid_instance_id'))
        batch_op.drop_index(batch_op.f('ix_misp__attribute__instance__uuid_case_id'))
        batch_op.drop_index(batch_op.f('ix_misp__attribute__instance__uuid_attribute_instance_uuid'))

    op.drop_table('misp__attribute__instance__uuid')
    with op.batch_alter_table('login__event', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_login__event_user_id'))
        batch_op.drop_index(batch_op.f('ix_login__event_login_date'))

    op.drop_table('login__event')
    with op.batch_alter_table('icon__file', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_icon__file_uuid'))
        batch_op.drop_index(batch_op.f('ix_icon__file_name'))

    op.drop_table('icon__file')
    with op.batch_alter_table('galaxy', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_galaxy_version'))
        batch_op.drop_index(batch_op.f('ix_galaxy_uuid'))

    op.drop_table('galaxy')
    with op.batch_alter_table('custom__tags', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_custom__tags_name'))
        batch_op.drop_index(batch_op.f('ix_custom__tags_icon'))
        batch_op.drop_index(batch_op.f('ix_custom__tags_color'))

    op.drop_table('custom__tags')
    with op.batch_alter_table('connector__sync__log', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_connector__sync__log_timestamp'))
        batch_op.drop_index(batch_op.f('ix_connector__sync__log_case_id'))
        batch_op.drop_index(batch_op.f('ix_connector__sync__log_case_connector_instance_id'))

    op.drop_table('connector__sync__log')
    with op.batch_alter_table('connector__icon', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_connector__icon_uuid'))
        batch_op.drop_index(batch_op.f('ix_connector__icon_name'))
        batch_op.drop_index(batch_op.f('ix_connector__icon_file_icon_id'))

    op.drop_table('connector__icon')
    with op.batch_alter_table('connector', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_connector_uuid'))
        batch_op.drop_index(batch_op.f('ix_connector_name'))
        batch_op.drop_index(batch_op.f('ix_connector_icon_id'))

    op.drop_table('connector')
    with op.batch_alter_table('configurable__fields', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_configurable__fields_name'))

    op.drop_table('configurable__fields')
    with op.batch_alter_table('case__timeline__event', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_case__timeline__event_creation_date'))
        batch_op.drop_index(batch_op.f('ix_case__timeline__event_case_id'))

    op.drop_table('case__timeline__event')
    with op.batch_alter_table('case__template__tags', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_case__template__tags_tag_id'))
        batch_op.drop_index(batch_op.f('ix_case__template__tags_case_id'))

    op.drop_table('case__template__tags')
    with op.batch_alter_table('case__template__galaxy__tags', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_case__template__galaxy__tags_template_id'))
        batch_op.drop_index(batch_op.f('ix_case__template__galaxy__tags_cluster_id'))

    op.drop_table('case__template__galaxy__tags')
    with op.batch_alter_table('case__template__custom__tags', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_case__template__custom__tags_custom_tag_id'))
        batch_op.drop_index(batch_op.f('ix_case__template__custom__tags_case_template_id'))

    op.drop_table('case__template__custom__tags')
    with op.batch_alter_table('case__template__connector__instance', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_case__template__connector__instance_connector_instance_id'))
        batch_op.drop_index(batch_op.f('ix_case__template__connector__instance_case_template_id'))

    op.drop_table('case__template__connector__instance')
    with op.batch_alter_table('case__template', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_case__template_uuid'))
        batch_op.drop_index(batch_op.f('ix_case__template_title'))
        batch_op.drop_index(batch_op.f('ix_case__template_last_modif'))

    op.drop_table('case__template')
    with op.batch_alter_table('case__tags', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_case__tags_tag_id'))
        batch_op.drop_index(batch_op.f('ix_case__tags_case_id'))

    op.drop_table('case__tags')
    op.drop_table('case__org')
    with op.batch_alter_table('case__note__template__model', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_case__note__template__model_note_template_id'))
        batch_op.drop_index(batch_op.f('ix_case__note__template__model_case_id'))

    op.drop_table('case__note__template__model')
    with op.batch_alter_table('case__misp__object', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_case__misp__object_template_uuid'))
        batch_op.drop_index(batch_op.f('ix_case__misp__object_last_modif'))
        batch_op.drop_index(batch_op.f('ix_case__misp__object_creation_date'))
        batch_op.drop_index(batch_op.f('ix_case__misp__object_case_id'))

    op.drop_table('case__misp__object')
    with op.batch_alter_table('case__link__case', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_case__link__case_case_id_2'))
        batch_op.drop_index(batch_op.f('ix_case__link__case_case_id_1'))

    op.drop_table('case__link__case')
    with op.batch_alter_table('case__galaxy__tags', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_case__galaxy__tags_cluster_id'))
        batch_op.drop_index(batch_op.f('ix_case__galaxy__tags_case_id'))

    op.drop_table('case__galaxy__tags')
    with op.batch_alter_table('case__custom__tags', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_case__custom__tags_custom_tag_id'))
        batch_op.drop_index(batch_op.f('ix_case__custom__tags_case_id'))

    op.drop_table('case__custom__tags')
    with op.batch_alter_table('case__connector__instance', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_case__connector__instance_instance_id'))
        batch_op.drop_index(batch_op.f('ix_case__connector__instance_case_id'))

    op.drop_table('case__connector__instance')
    with op.batch_alter_table('case', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_case_uuid'))
        batch_op.drop_index(batch_op.f('ix_case_status_id'))
        batch_op.drop_index(batch_op.f('ix_case_recurring_type'))
        batch_op.drop_index(batch_op.f('ix_case_recurring_date'))
        batch_op.drop_index(batch_op.f('ix_case_privileged_case'))
        batch_op.drop_index(batch_op.f('ix_case_owner_org_id'))
        batch_op.drop_index(batch_op.f('ix_case_notif_deadline_id'))
        batch_op.drop_index(batch_op.f('ix_case_nb_tasks'))
        batch_op.drop_index(batch_op.f('ix_case_last_modif'))
        batch_op.drop_index(batch_op.f('ix_case_is_private'))
        batch_op.drop_index(batch_op.f('ix_case_finish_date'))
        batch_op.drop_index(batch_op.f('ix_case_deadline'))
        batch_op.drop_index(batch_op.f('ix_case_creation_date'))

    op.drop_table('case')
    with op.batch_alter_table('alert', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_alert_message'))
        batch_op.drop_index(batch_op.f('ix_alert_creation_date'))
        batch_op.drop_index(batch_op.f('ix_alert_case_id'))

    op.drop_table('alert')
    # ### end Alembic commands ###
