"""empty message

Revision ID: 014d6c99a5d5
Revises: e38bec5037d7
Create Date: 2024-08-21 11:23:10.340913

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy import inspect
from sqlalchemy import inspect


# revision identifiers, used by Alembic.
revision = '014d6c99a5d5'
down_revision = 'e38bec5037d7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    
    # Obtenir l'inspecteur pour vérifier l'existence des colonnes
    conn = op.get_bind()
    inspector = inspect(conn)
    existing_tables = inspector.get_table_names()
    
    # Ajouter colonne user_id à analyzer__result si elle n'existe pas
    if 'analyzer__result' in existing_tables:
        columns = [col['name'] for col in inspector.get_columns('analyzer__result')]
        if 'user_id' not in columns:
            op.add_column('analyzer__result', sa.Column('user_id', sa.Integer(), nullable=True))
            op.create_index('ix_analyzer__result_user_id', 'analyzer__result', ['user_id'])
            print("Added user_id column to analyzer__result")
        else:
            print("Column user_id already exists in analyzer__result")
    else:
        print("Table analyzer__result does not exist")

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('analyzer__result', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_analyzer__result_user_id'))
        batch_op.drop_column('user_id')

    # ### end Alembic commands ###
