"""empty message

Revision ID: 03a283bcdd4b
Revises: 9ee9484a8102
Create Date: 2023-10-27 09:59:05.090340

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy import inspect


# revision identifiers, used by Alembic.
revision = '03a283bcdd4b'
down_revision = '9ee9484a8102'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # Check if columns exist before adding
    bind = op.get_bind()
    inspector = inspect(bind)
    
    # Check case__template table
    case_template_columns = [col['name'] for col in inspector.get_columns('case__template')]
    if 'taxonomies' not in case_template_columns:
        op.add_column('case__template', sa.Column('taxonomies', sa.String(), nullable=True))

    # Check task__template table
    task_template_columns = [col['name'] for col in inspector.get_columns('task__template')]
    if 'taxonomies' not in task_template_columns:
        op.add_column('task__template', sa.Column('taxonomies', sa.String(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('task__template', schema=None) as batch_op:
        batch_op.drop_column('taxonomies')

    with op.batch_alter_table('case__template', schema=None) as batch_op:
        batch_op.drop_column('taxonomies')

    # ### end Alembic commands ###
