"""empty message

Revision ID: 04ee0d5e0abb
Revises: 85e79b40ca2e
Create Date: 2023-11-29 11:40:27.185464

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy import inspect


# revision identifiers, used by Alembic.
revision = '04ee0d5e0abb'
down_revision = '85e79b40ca2e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # Check what exists before making changes
    bind = op.get_bind()
    inspector = inspect(bind)
    existing_tables = inspector.get_table_names()

    # Create connector table if it doesn't exist
    if 'connector' not in existing_tables:
        op.create_table('connector',
        sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
        sa.Column('name', sa.String(length=64), nullable=True),
        sa.Column('url', sa.String(length=64), nullable=True),
        sa.Column('description', sa.String(), nullable=True),
        sa.Column('icon_id', sa.Integer(), nullable=True),
        sa.PrimaryKeyConstraint('id')
        )
        op.create_index('ix_connector_icon_id', 'connector', ['icon_id'], unique=False)
        op.create_index('ix_connector_name', 'connector', ['name'], unique=False)
        op.create_index('ix_connector_url', 'connector', ['url'], unique=False)
    else:
        print("Table 'connector' already exists")

    # Create connector__icon table if it doesn't exist
    if 'connector__icon' not in existing_tables:
        op.create_table('connector__icon',
        sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
        sa.Column('name', sa.String(length=64), nullable=True),
        sa.Column('uuid', sa.String(length=36), nullable=True),
        sa.PrimaryKeyConstraint('id')
        )
        op.create_index('ix_connector__icon_name', 'connector__icon', ['name'], unique=True)
        op.create_index('ix_connector__icon_uuid', 'connector__icon', ['uuid'], unique=False)
    else:
        print("Table 'connector__icon' already exists")

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('connector__icon', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_connector__icon_uuid'))
        batch_op.drop_index(batch_op.f('ix_connector__icon_name'))

    op.drop_table('connector__icon')
    with op.batch_alter_table('connector', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_connector_url'))
        batch_op.drop_index(batch_op.f('ix_connector_name'))
        batch_op.drop_index(batch_op.f('ix_connector_icon_id'))

    op.drop_table('connector')
    # ### end Alembic commands ###
