"""remove_type_from_connector_instance

Revision ID: 056a43a96b07
Revises: e1a2b3c4d5f6
Create Date: 2026-05-18 14:53:33.971081

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '056a43a96b07'
down_revision = 'e1a2b3c4d5f6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###

    bind = op.get_bind()
    inspector = sa.inspect(bind)
    existing_columns = [col['name'] for col in inspector.get_columns('connector__instance')]

    if 'type' in existing_columns:
        with op.batch_alter_table('connector__instance', schema=None) as batch_op:
            batch_op.drop_index(batch_op.f('ix_connector__instance_type'))
            batch_op.drop_column('type')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    bind = op.get_bind()
    inspector = sa.inspect(bind)
    existing_columns = [col['name'] for col in inspector.get_columns('connector__instance')]

    if 'type' not in existing_columns:
        with op.batch_alter_table('connector__instance', schema=None) as batch_op:
            batch_op.add_column(sa.Column('type', sa.VARCHAR(length=36), nullable=True))
            batch_op.create_index(batch_op.f('ix_connector__instance_type'), ['type'], unique=False)

    # ### end Alembic commands ###
