"""empty message

Revision ID: 19fb9265b8c1
Revises: ffffd6a1fa75
Create Date: 2023-11-16 13:45:07.252715

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy import inspect


# revision identifiers, used by Alembic.
revision = '19fb9265b8c1'
down_revision = 'ffffd6a1fa75'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # Check if column exists before adding
    bind = op.get_bind()
    inspector = inspect(bind)
    existing_columns = [col['name'] for col in inspector.get_columns('galaxy')]
    
    if 'type' not in existing_columns:
        op.add_column('galaxy', sa.Column('type', sa.String(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('galaxy', schema=None) as batch_op:
        batch_op.drop_column('type')

    op.create_table('_alembic_tmp_tags',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('name', sa.VARCHAR(), nullable=True),
    sa.Column('color', sa.VARCHAR(), nullable=True),
    sa.Column('exclude', sa.BOOLEAN(), nullable=True),
    sa.Column('taxonomy_id', sa.INTEGER(), nullable=True),
    sa.ForeignKeyConstraint(['taxonomy_id'], ['taxonomy.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###
