"""empty message

Revision ID: 233237ff2760
Revises: a5e09a98ee8e
Create Date: 2026-02-03 11:39:19.539540

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '233237ff2760'
down_revision = 'a5e09a98ee8e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    bind = op.get_bind()
    inspector = sa.inspect(bind)
    existing_tables = inspector.get_table_names()

    if not "task__galaxy" in existing_tables:
        op.create_table('task__galaxy',
        sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
        sa.Column('galaxy_id', sa.Integer(), nullable=True),
        sa.Column('task_id', sa.Integer(), nullable=True),
        sa.PrimaryKeyConstraint('id')
        )
        with op.batch_alter_table('task__galaxy', schema=None) as batch_op:
            batch_op.create_index(batch_op.f('ix_task__galaxy_galaxy_id'), ['galaxy_id'], unique=False)
            batch_op.create_index(batch_op.f('ix_task__galaxy_task_id'), ['task_id'], unique=False)
    
    if not "task__template__galaxy" in existing_tables:
        op.create_table('task__template__galaxy',
        sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
        sa.Column('galaxy_id', sa.Integer(), nullable=True),
        sa.Column('template_id', sa.Integer(), nullable=True),
        sa.PrimaryKeyConstraint('id')
        )
        with op.batch_alter_table('task__template__galaxy', schema=None) as batch_op:
            batch_op.create_index(batch_op.f('ix_task__template__galaxy_galaxy_id'), ['galaxy_id'], unique=False)
            batch_op.create_index(batch_op.f('ix_task__template__galaxy_template_id'), ['template_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    bind = op.get_bind()
    inspector = sa.inspect(bind)
    existing_tables = inspector.get_table_names()
    if "task__template__galaxy" in existing_tables:
        with op.batch_alter_table('task__template__galaxy', schema=None) as batch_op:
            batch_op.drop_index(batch_op.f('ix_task__template__galaxy_template_id'))
            batch_op.drop_index(batch_op.f('ix_task__template__galaxy_galaxy_id'))

        op.drop_table('task__template__galaxy')

    if "task__galaxy" in existing_tables:
        with op.batch_alter_table('task__galaxy', schema=None) as batch_op:
            batch_op.drop_index(batch_op.f('ix_task__galaxy_task_id'))
            batch_op.drop_index(batch_op.f('ix_task__galaxy_galaxy_id'))

        op.drop_table('task__galaxy')
    # ### end Alembic commands ###
