"""empty message

Revision ID: 2418fe20d609
Revises: ab99c63cd1c2
Create Date: 2023-11-29 15:59:18.366612

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy import inspect


# revision identifiers, used by Alembic.
revision = '2418fe20d609'
down_revision = 'ab99c63cd1c2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # Check what exists before making changes
    bind = op.get_bind()
    inspector = inspect(bind)
    existing_tables = inspector.get_table_names()
    
    # Create icon__file table if it doesn't exist
    if 'icon__file' not in existing_tables:
        op.create_table('icon__file',
        sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
        sa.Column('name', sa.String(length=64), nullable=True),
        sa.Column('uuid', sa.String(length=36), nullable=True),
        sa.PrimaryKeyConstraint('id')
        )
        op.create_index('ix_icon__file_name', 'icon__file', ['name'], unique=True)
        op.create_index('ix_icon__file_uuid', 'icon__file', ['uuid'], unique=False)
    else:
        print("Table 'icon__file' already exists")

    # Add file_icon_id column to connector__icon if it doesn't exist
    connector_icon_columns = [col['name'] for col in inspector.get_columns('connector__icon')]
    if 'file_icon_id' not in connector_icon_columns:
        op.add_column('connector__icon', sa.Column('file_icon_id', sa.Integer(), nullable=True))
        op.create_index('ix_connector__icon_file_icon_id', 'connector__icon', ['file_icon_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('connector__icon', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_connector__icon_file_icon_id'))
        batch_op.drop_column('file_icon_id')

    with op.batch_alter_table('icon__file', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_icon__file_uuid'))
        batch_op.drop_index(batch_op.f('ix_icon__file_name'))

    op.drop_table('icon__file')
    # ### end Alembic commands ###
