"""empty message

Revision ID: 24bb42802255
Revises: b778a0462b8e
Create Date: 2025-04-01 15:49:20.267559

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy import inspect
from sqlalchemy.exc import OperationalError


# revision identifiers, used by Alembic.
revision = '24bb42802255'
down_revision = 'b778a0462b8e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    bind = op.get_bind()
    inspector = inspect(bind)
    
    # Handle tags table
    tags_columns = [col['name'] for col in inspector.get_columns('tags')]
    foreign_keys = inspector.get_foreign_keys('tags')
    with op.batch_alter_table('tags', schema=None) as batch_op:
        if 'uuid' not in tags_columns:
            batch_op.add_column(sa.Column('uuid', sa.String(length=36), nullable=True))
            batch_op.create_index('ix_tags_uuid', ['uuid'], unique=False)
    
        if 'cluster_id' in tags_columns:
            for fk in foreign_keys:
                if fk['constrained_columns'] == ['cluster_id']:
                    batch_op.drop_constraint(fk['name'], type_='foreignkey')
                    break
            batch_op.drop_column('cluster_id')
    
    # Handle taxonomy table  
    taxonomy_columns = [col['name'] for col in inspector.get_columns('taxonomy')]
    with op.batch_alter_table('taxonomy', schema=None) as batch_op:
        if 'uuid' not in taxonomy_columns:
            batch_op.add_column(sa.Column('uuid', sa.String(length=36), nullable=True))
            batch_op.create_index('ix_taxonomy_uuid', ['uuid'], unique=False)
        if 'version' not in taxonomy_columns:
            batch_op.add_column(sa.Column('version', sa.String(length=15), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    bind = op.get_bind()
    inspector = inspect(bind)
    
    # Revert taxonomy table
    taxonomy_columns = [col['name'] for col in inspector.get_columns('taxonomy')]
    taxonomy_indexes = [idx['name'] for idx in inspector.get_indexes('taxonomy')]
    with op.batch_alter_table('taxonomy', schema=None) as batch_op:
        if 'ix_taxonomy_uuid' in taxonomy_indexes:
            batch_op.drop_index('ix_taxonomy_uuid')
        if 'version' in taxonomy_columns:
            batch_op.drop_column('version')
        if 'uuid' in taxonomy_columns:
            batch_op.drop_column('uuid')
    # Revert tags table
    tags_columns = [col['name'] for col in inspector.get_columns('tags')]
    tags_indexes = [idx['name'] for idx in inspector.get_indexes('tags')]
    
    with op.batch_alter_table('tags', schema=None) as batch_op:
        if 'cluster_id' not in tags_columns:
            batch_op.add_column(sa.Column('cluster_id', sa.INTEGER(), nullable=True))
            batch_op.create_foreign_key('fk_tags_cluster_id_cluster', 'tags', 'cluster', ['cluster_id'], ['id'], ondelete='CASCADE')
        if 'ix_tags_uuid' in tags_indexes:
            batch_op.drop_index('ix_tags_uuid')
        if 'uuid' in tags_columns:
            batch_op.drop_column('uuid')

    # ### end Alembic commands ###
