"""empty message

Revision ID: 24bb42802255
Revises: b778a0462b8e
Create Date: 2025-04-01 15:49:20.267559

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.exc import OperationalError


# revision identifiers, used by Alembic.
revision = '24bb42802255'
down_revision = 'b778a0462b8e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    try:
        with op.batch_alter_table('tags', schema=None) as batch_op:
            batch_op.add_column(sa.Column('uuid', sa.String(length=36), nullable=True))
            batch_op.create_index(batch_op.f('ix_tags_uuid'), ['uuid'], unique=False)
            batch_op.drop_constraint('fk_tags_cluster_id_cluster', type_='foreignkey')
            batch_op.drop_column('cluster_id')
    except OperationalError:
        print("Tags table already changed")

    try:
        with op.batch_alter_table('taxonomy', schema=None) as batch_op:
            batch_op.add_column(sa.Column('uuid', sa.String(length=36), nullable=True))
            batch_op.add_column(sa.Column('version', sa.String(length=15), nullable=True))
            batch_op.create_index(batch_op.f('ix_taxonomy_uuid'), ['uuid'], unique=False)
    except OperationalError:
        print("Taxonomy table already changed")

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    try:
        with op.batch_alter_table('taxonomy', schema=None) as batch_op:
            batch_op.drop_index(batch_op.f('ix_taxonomy_uuid'))
            batch_op.drop_column('version')
            batch_op.drop_column('uuid')
    except OperationalError:
        print("Tags table already changed")

    try:
        with op.batch_alter_table('tags', schema=None) as batch_op:
            batch_op.add_column(sa.Column('cluster_id', sa.INTEGER(), nullable=True))
            batch_op.create_foreign_key('fk_tags_cluster_id_cluster', 'cluster', ['cluster_id'], ['id'], ondelete='CASCADE')
            batch_op.drop_index(batch_op.f('ix_tags_uuid'))
            batch_op.drop_column('uuid')
    except OperationalError:
        print("Taxonomy table already changed")

    # ### end Alembic commands ###
