"""empty message

Revision ID: 29493862f7a9
Revises: 7d2e49815606
Create Date: 2025-06-03 14:12:01.024860

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.exc import OperationalError


# revision identifiers, used by Alembic.
revision = '29493862f7a9'
down_revision = '7d2e49815606'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    try:
        with op.batch_alter_table('case__note__template__model', schema=None) as batch_op:
            batch_op.add_column(sa.Column('content', sa.String(), nullable=True))
            batch_op.drop_index('ix_case__note__template__model_template_version')
            batch_op.drop_column('template_version')
    except (OperationalError, ValueError):
        print("table case__note__template__model already modified")
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    try:
        with op.batch_alter_table('case__note__template__model', schema=None) as batch_op:
            batch_op.add_column(sa.Column('template_version', sa.INTEGER(), nullable=True))
            batch_op.create_index('ix_case__note__template__model_template_version', ['template_version'], unique=False)
            batch_op.drop_column('content')
    except (OperationalError, ValueError):
        print("table case__note__template__model already modified")

    # ### end Alembic commands ###
