"""empty message

Revision ID: 29493862f7a9
Revises: 7d2e49815606
Create Date: 2025-06-03 14:12:01.024860

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy import inspect
from sqlalchemy.exc import OperationalError


# revision identifiers, used by Alembic.
revision = '29493862f7a9'
down_revision = '7d2e49815606'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    bind = op.get_bind()
    inspector = inspect(bind)
    existing_tables = inspector.get_table_names()
    
    if 'case__note__template__model' in existing_tables:
        columns = [col['name'] for col in inspector.get_columns('case__note__template__model')]
        indexes = [idx['name'] for idx in inspector.get_indexes('case__note__template__model')]
        
        # Add content column if it doesn't exist
        if 'content' not in columns:
            op.add_column('case__note__template__model', sa.Column('content', sa.String(), nullable=True))
        
        # Drop index if it exists
        if 'ix_case__note__template__model_template_version' in indexes:
            op.drop_index('ix_case__note__template__model_template_version', table_name='case__note__template__model')
        
        # Drop template_version column if it exists
        if 'template_version' in columns:
            op.drop_column('case__note__template__model', 'template_version')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    bind = op.get_bind()
    inspector = inspect(bind)
    existing_tables = inspector.get_table_names()
    
    if 'case__note__template__model' in existing_tables:
        columns = [col['name'] for col in inspector.get_columns('case__note__template__model')]
        indexes = [idx['name'] for idx in inspector.get_indexes('case__note__template__model')]
        
        # Add template_version column if it doesn't exist
        if 'template_version' not in columns:
            op.add_column('case__note__template__model', sa.Column('template_version', sa.INTEGER(), nullable=True))
        
        # Create index if it doesn't exist
        if 'ix_case__note__template__model_template_version' not in indexes:
            op.create_index('ix_case__note__template__model_template_version', 'case__note__template__model', ['template_version'], unique=False)
        
        # Drop content column if it exists
        if 'content' in columns:
            op.drop_column('case__note__template__model', 'content')

    # ### end Alembic commands ###
