"""Remove unique constraint from file name field

Revision ID: 29a27d426ed3
Revises: 7437a55c703f
Create Date: 2026-01-27 17:01:36.878686

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '29a27d426ed3'
down_revision = '7437a55c703f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###

    bind = op.get_bind()
    inspector = sa.inspect(bind)
    existing_indexes = [idx['name'] for idx in inspector.get_indexes('file')]

    with op.batch_alter_table('file', schema=None) as batch_op:
        if 'ix_file_name' in existing_indexes:
            batch_op.drop_index(batch_op.f('ix_file_name'))
            batch_op.create_index(batch_op.f('ix_file_name'), ['name'], unique=False)
        if 'ix_file_uuid' in existing_indexes:
            batch_op.drop_index(batch_op.f('ix_file_uuid'))
            batch_op.create_index(batch_op.f('ix_file_uuid'), ['uuid'], unique=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    bind = op.get_bind()
    inspector = sa.inspect(bind)
    existing_indexes = [idx['name'] for idx in inspector.get_indexes('file')]

    with op.batch_alter_table('file', schema=None) as batch_op:
        if 'ix_file_uuid' in existing_indexes:
            batch_op.drop_index(batch_op.f('ix_file_uuid'))
            batch_op.create_index(batch_op.f('ix_file_uuid'), ['uuid'], unique=False)
        if 'ix_file_name' in existing_indexes:
            batch_op.drop_index(batch_op.f('ix_file_name'))
            batch_op.create_index(batch_op.f('ix_file_name'), ['name'], unique=1)
    # ### end Alembic commands ###
