"""empty message

Revision ID: 3042fb8e5c84
Revises: d914b6b4c07d
Create Date: 2024-03-01 12:05:50.522219

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3042fb8e5c84'
down_revision = 'd914b6b4c07d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('case', schema=None) as batch_op:
        batch_op.add_column(sa.Column('notes', sa.String(), nullable=True))
        batch_op.alter_column('id',
               existing_type=sa.INTEGER(),
               nullable=False,
               autoincrement=True)
        batch_op.alter_column('uuid',
               existing_type=sa.TEXT(),
               type_=sa.String(length=36),
               existing_nullable=True)
        batch_op.alter_column('title',
               existing_type=sa.TEXT(),
               type_=sa.String(length=64),
               existing_nullable=True)
        batch_op.alter_column('description',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True)
        batch_op.alter_column('recurring_type',
               existing_type=sa.TEXT(),
               type_=sa.String(length=30),
               existing_nullable=True)
        batch_op.drop_index('idx_case_creation_date')
        batch_op.drop_index('idx_case_deadline')
        batch_op.drop_index('idx_case_finish_date')
        batch_op.drop_index('idx_case_last_modif')
        batch_op.drop_index('idx_case_notif_deadline_id')
        batch_op.drop_index('idx_case_owner_org_id')
        batch_op.drop_index('idx_case_recurring_date')
        batch_op.drop_index('idx_case_recurring_type')
        batch_op.drop_index('idx_case_status_id')
        batch_op.drop_index('idx_case_title')
        batch_op.drop_index('idx_case_uuid')
        batch_op.create_index(batch_op.f('ix_case_creation_date'), ['creation_date'], unique=False)
        batch_op.create_index(batch_op.f('ix_case_deadline'), ['deadline'], unique=False)
        batch_op.create_index(batch_op.f('ix_case_finish_date'), ['finish_date'], unique=False)
        batch_op.create_index(batch_op.f('ix_case_last_modif'), ['last_modif'], unique=False)
        batch_op.create_index(batch_op.f('ix_case_notif_deadline_id'), ['notif_deadline_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_case_owner_org_id'), ['owner_org_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_case_recurring_date'), ['recurring_date'], unique=False)
        batch_op.create_index(batch_op.f('ix_case_recurring_type'), ['recurring_type'], unique=False)
        batch_op.create_index(batch_op.f('ix_case_status_id'), ['status_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_case_title'), ['title'], unique=False)
        batch_op.create_index(batch_op.f('ix_case_uuid'), ['uuid'], unique=False)

    with op.batch_alter_table('task', schema=None) as batch_op:
        batch_op.alter_column('id',
               existing_type=sa.INTEGER(),
               nullable=False,
               autoincrement=True)
        batch_op.alter_column('uuid',
               existing_type=sa.TEXT(),
               type_=sa.String(length=36),
               existing_nullable=True)
        batch_op.alter_column('title',
               existing_type=sa.TEXT(),
               type_=sa.String(length=64),
               existing_nullable=True)
        batch_op.alter_column('description',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True)
        batch_op.alter_column('url',
               existing_type=sa.TEXT(),
               type_=sa.String(length=64),
               existing_nullable=True)
        batch_op.alter_column('notes',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True)
        batch_op.drop_index('idx_task_case_id')
        batch_op.drop_index('idx_task_completed')
        batch_op.drop_index('idx_task_creation_date')
        batch_op.drop_index('idx_task_deadline')
        batch_op.drop_index('idx_task_last_modif')
        batch_op.drop_index('idx_task_status_id')
        batch_op.drop_index('idx_task_title')
        batch_op.drop_index('idx_task_uuid')
        batch_op.create_index(batch_op.f('ix_task_creation_date'), ['creation_date'], unique=False)
        batch_op.create_index(batch_op.f('ix_task_deadline'), ['deadline'], unique=False)
        batch_op.create_index(batch_op.f('ix_task_finish_date'), ['finish_date'], unique=False)
        batch_op.create_index(batch_op.f('ix_task_last_modif'), ['last_modif'], unique=False)
        batch_op.create_index(batch_op.f('ix_task_notif_deadline_id'), ['notif_deadline_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_task_status_id'), ['status_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_task_title'), ['title'], unique=False)
        batch_op.create_index(batch_op.f('ix_task_url'), ['url'], unique=False)
        batch_op.create_index(batch_op.f('ix_task_uuid'), ['uuid'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('task', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_task_uuid'))
        batch_op.drop_index(batch_op.f('ix_task_url'))
        batch_op.drop_index(batch_op.f('ix_task_title'))
        batch_op.drop_index(batch_op.f('ix_task_status_id'))
        batch_op.drop_index(batch_op.f('ix_task_notif_deadline_id'))
        batch_op.drop_index(batch_op.f('ix_task_last_modif'))
        batch_op.drop_index(batch_op.f('ix_task_finish_date'))
        batch_op.drop_index(batch_op.f('ix_task_deadline'))
        batch_op.drop_index(batch_op.f('ix_task_creation_date'))
        batch_op.create_index('idx_task_uuid', ['uuid'], unique=False)
        batch_op.create_index('idx_task_title', ['title'], unique=False)
        batch_op.create_index('idx_task_status_id', ['status_id'], unique=False)
        batch_op.create_index('idx_task_last_modif', ['last_modif'], unique=False)
        batch_op.create_index('idx_task_deadline', ['deadline'], unique=False)
        batch_op.create_index('idx_task_creation_date', ['creation_date'], unique=False)
        batch_op.create_index('idx_task_completed', ['completed'], unique=False)
        batch_op.create_index('idx_task_case_id', ['case_id'], unique=False)
        batch_op.alter_column('notes',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True)
        batch_op.alter_column('url',
               existing_type=sa.String(length=64),
               type_=sa.TEXT(),
               existing_nullable=True)
        batch_op.alter_column('description',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True)
        batch_op.alter_column('title',
               existing_type=sa.String(length=64),
               type_=sa.TEXT(),
               existing_nullable=True)
        batch_op.alter_column('uuid',
               existing_type=sa.String(length=36),
               type_=sa.TEXT(),
               existing_nullable=True)
        batch_op.alter_column('id',
               existing_type=sa.INTEGER(),
               nullable=True,
               autoincrement=True)

    with op.batch_alter_table('case', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_case_uuid'))
        batch_op.drop_index(batch_op.f('ix_case_title'))
        batch_op.drop_index(batch_op.f('ix_case_status_id'))
        batch_op.drop_index(batch_op.f('ix_case_recurring_type'))
        batch_op.drop_index(batch_op.f('ix_case_recurring_date'))
        batch_op.drop_index(batch_op.f('ix_case_owner_org_id'))
        batch_op.drop_index(batch_op.f('ix_case_notif_deadline_id'))
        batch_op.drop_index(batch_op.f('ix_case_last_modif'))
        batch_op.drop_index(batch_op.f('ix_case_finish_date'))
        batch_op.drop_index(batch_op.f('ix_case_deadline'))
        batch_op.drop_index(batch_op.f('ix_case_creation_date'))
        batch_op.create_index('idx_case_uuid', ['uuid'], unique=False)
        batch_op.create_index('idx_case_title', ['title'], unique=False)
        batch_op.create_index('idx_case_status_id', ['status_id'], unique=False)
        batch_op.create_index('idx_case_recurring_type', ['recurring_type'], unique=False)
        batch_op.create_index('idx_case_recurring_date', ['recurring_date'], unique=False)
        batch_op.create_index('idx_case_owner_org_id', ['owner_org_id'], unique=False)
        batch_op.create_index('idx_case_notif_deadline_id', ['notif_deadline_id'], unique=False)
        batch_op.create_index('idx_case_last_modif', ['last_modif'], unique=False)
        batch_op.create_index('idx_case_finish_date', ['finish_date'], unique=False)
        batch_op.create_index('idx_case_deadline', ['deadline'], unique=False)
        batch_op.create_index('idx_case_creation_date', ['creation_date'], unique=False)
        batch_op.alter_column('recurring_type',
               existing_type=sa.String(length=30),
               type_=sa.TEXT(),
               existing_nullable=True)
        batch_op.alter_column('description',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True)
        batch_op.alter_column('title',
               existing_type=sa.String(length=64),
               type_=sa.TEXT(),
               existing_nullable=True)
        batch_op.alter_column('uuid',
               existing_type=sa.String(length=36),
               type_=sa.TEXT(),
               existing_nullable=True)
        batch_op.alter_column('id',
               existing_type=sa.INTEGER(),
               nullable=True,
               autoincrement=True)
        batch_op.drop_column('notes')

    # ### end Alembic commands ###
