"""empty message

Revision ID: 312b3d2223d6
Revises: d9c47465de6e
Create Date: 2024-07-02 12:11:34.143597

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '312b3d2223d6'
down_revision = 'd9c47465de6e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('custom__tags',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=25), nullable=True),
    sa.Column('color', sa.String(length=20), nullable=True),
    sa.Column('icon', sa.String(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('custom__tags', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_custom__tags_color'), ['color'], unique=False)
        batch_op.create_index(batch_op.f('ix_custom__tags_icon'), ['icon'], unique=False)
        batch_op.create_index(batch_op.f('ix_custom__tags_name'), ['name'], unique=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('custom__tags', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_custom__tags_name'))
        batch_op.drop_index(batch_op.f('ix_custom__tags_icon'))
        batch_op.drop_index(batch_op.f('ix_custom__tags_color'))

    op.drop_table('custom__tags')
    # ### end Alembic commands ###
