"""add_foreign_key_role_id_to_user

Revision ID: 322c78d73617
Revises: a1b2c3d4e5f6
Create Date: 2026-04-12 02:25:15.909444

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '322c78d73617'
down_revision = 'a1b2c3d4e5f6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.create_foreign_key('fk_user_role_id', 'role', ['role_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_constraint('fk_user_role_id', type_='foreignkey')

    # ### end Alembic commands ###
