"""Add case_id to File model for case file attachments

Revision ID: 33e4650639fd
Revises: 29a27d426ed3
Create Date: 2026-01-29 10:00:00.000000

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '33e4650639fd'
down_revision = '29a27d426ed3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###

    bind = op.get_bind()
    inspector = sa.inspect(bind)
    file_columns = [col['name'] for col in inspector.get_columns('file')]
    
    with op.batch_alter_table('file', schema=None) as batch_op:
        # Make task_id nullable to support both task and case attachments
        if 'task_id' in file_columns:
            batch_op.alter_column('task_id',
                                  existing_type=sa.Integer(),
                                  nullable=True)
        
        # Add case_id column for case file attachments
        if 'case_id' not in file_columns:
            batch_op.add_column(sa.Column('case_id', sa.Integer(), nullable=True))
            batch_op.create_foreign_key('fk_file_case_id', 'case', ['case_id'], ['id'], ondelete='CASCADE')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    bind = op.get_bind()
    inspector = sa.inspect(bind)
    file_columns = [col['name'] for col in inspector.get_columns('file')]
    
    with op.batch_alter_table('file', schema=None) as batch_op:
        if 'case_id' in file_columns:
            batch_op.drop_constraint('fk_file_case_id', type_='foreignkey')
            batch_op.drop_column('case_id')
        
        if 'task_id' in file_columns:
            batch_op.alter_column('task_id',
                                  existing_type=sa.Integer(),
                                  nullable=False)
    # ### end Alembic commands ###
