"""Add Case_Timeline_Event_Link table

Revision ID: 3567475b1063
Revises: ebb8b017a285
Create Date: 2026-03-31 09:07:34.321433

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3567475b1063'
down_revision = 'ebb8b017a285'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###

    bind = op.get_bind()
    inspector = sa.inspect(bind)
    existing_tables = inspector.get_table_names()

    if 'case__timeline__event__link' not in existing_tables:
        op.create_table('case__timeline__event__link',
        sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
        sa.Column('case_id', sa.Integer(), nullable=True),
        sa.Column('source_event_id', sa.Integer(), nullable=True),
        sa.Column('target_event_id', sa.Integer(), nullable=True),
        sa.Column('label', sa.String(), nullable=True),
        sa.ForeignKeyConstraint(['source_event_id'], ['case__timeline__event.id'], ondelete='CASCADE'),
        sa.ForeignKeyConstraint(['target_event_id'], ['case__timeline__event.id'], ondelete='CASCADE'),
        sa.PrimaryKeyConstraint('id')
        )
        with op.batch_alter_table('case__timeline__event__link', schema=None) as batch_op:
            batch_op.create_index(batch_op.f('ix_case__timeline__event__link_case_id'), ['case_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###

    bind = op.get_bind()
    inspector = sa.inspect(bind)
    existing_tables = inspector.get_table_names()

    if 'case__timeline__event__link' in existing_tables:
        with op.batch_alter_table('case__timeline__event__link', schema=None) as batch_op:
            batch_op.drop_index(batch_op.f('ix_case__timeline__event__link_case_id'))

        op.drop_table('case__timeline__event__link')
    # ### end Alembic commands ###
