"""empty message

Revision ID: 3a0416665c4b
Revises: b517c582523f
Create Date: 2024-10-10 10:55:53.224114

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy import inspect
from sqlalchemy.exc import OperationalError


# revision identifiers, used by Alembic.
revision = '3a0416665c4b'
down_revision = 'b517c582523f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    bind = op.get_bind()
    inspector = inspect(bind)
    existing_columns = [col['name'] for col in inspector.get_columns('task')]
    
    if 'time_required' not in existing_columns:
        op.add_column('task', sa.Column('time_required', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    bind = op.get_bind()
    inspector = inspect(bind)
    existing_columns = [col['name'] for col in inspector.get_columns('task')]
    
    if 'time_required' in existing_columns:
        op.drop_column('task', 'time_required')

    # ### end Alembic commands ###
