"""empty message

Revision ID: 3b5b564abda2
Revises: 0fc6982b9493
Create Date: 2024-03-22 11:59:06.708937

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy import inspect


# revision identifiers, used by Alembic.
revision = '3b5b564abda2'
down_revision = '0fc6982b9493'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    bind = op.get_bind()
    inspector = inspect(bind)
    existing_columns = [col['name'] for col in inspector.get_columns('user')]
    
    if 'matrix_id' not in existing_columns:
        op.add_column('user', sa.Column('matrix_id', sa.String(), nullable=True))
        op.create_index('ix_user_matrix_id', 'user', ['matrix_id'], unique=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_user_matrix_id'))
        batch_op.drop_column('matrix_id')

    # ### end Alembic commands ###
