"""empty message

Revision ID: 3b5b564abda2
Revises: 0fc6982b9493
Create Date: 2024-03-22 11:59:06.708937

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3b5b564abda2'
down_revision = '0fc6982b9493'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('matrix_id', sa.String(), nullable=True))
        batch_op.create_index(batch_op.f('ix_user_matrix_id'), ['matrix_id'], unique=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_user_matrix_id'))
        batch_op.drop_column('matrix_id')

    # ### end Alembic commands ###
