"""empty message

Revision ID: 3f0bfdc6f04e
Revises: 6f6b34409b43
Create Date: 2023-12-12 08:42:00.014600

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.exc import OperationalError


# revision identifiers, used by Alembic.
revision = '3f0bfdc6f04e'
down_revision = '6f6b34409b43'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    try:
        with op.batch_alter_table('connector__instance', schema=None) as batch_op:
            batch_op.add_column(sa.Column('type', sa.String(length=36), nullable=True))
            batch_op.create_index(batch_op.f('ix_connector__instance_type'), ['type'], unique=False)
    except OperationalError:
        print("Column 'type' already exist in 'connector__instance'")

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('connector__instance', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_connector__instance_type'))
        batch_op.drop_column('type')

    # ### end Alembic commands ###
