"""empty message

Revision ID: 3f0bfdc6f04e
Revises: 6f6b34409b43
Create Date: 2023-12-12 08:42:00.014600

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy import inspect


# revision identifiers, used by Alembic.
revision = '3f0bfdc6f04e'
down_revision = '6f6b34409b43'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # Check if column exists before adding
    bind = op.get_bind()
    inspector = inspect(bind)
    existing_columns = [col['name'] for col in inspector.get_columns('connector__instance')]
    
    if 'type' not in existing_columns:
        op.add_column('connector__instance', sa.Column('type', sa.String(length=36), nullable=True))
        op.create_index('ix_connector__instance_type', 'connector__instance', ['type'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('connector__instance', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_connector__instance_type'))
        batch_op.drop_column('type')

    # ### end Alembic commands ###
