"""empty message

Revision ID: 44196916f12c
Revises: 72883f4859bf
Create Date: 2024-08-13 13:44:04.591119

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.exc import OperationalError


# revision identifiers, used by Alembic.
revision = '44196916f12c'
down_revision = '72883f4859bf'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    try:
        with op.batch_alter_table('case', schema=None) as batch_op:
            batch_op.add_column(sa.Column('hedgedoc_url', sa.String(), nullable=True))
    except OperationalError:
        print("Column 'hedgedoc_url' already exist in 'case'")

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('case', schema=None) as batch_op:
        batch_op.drop_column('hedgedoc_url')

    # ### end Alembic commands ###
