"""empty message

Revision ID: 4a544282986e
Revises: 03a283bcdd4b
Create Date: 2023-10-30 13:11:59.805487

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4a544282986e'
down_revision = '03a283bcdd4b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('case__tags',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('tag_id', sa.Integer(), nullable=True),
    sa.Column('case_id', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('case__tags', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_case__tags_case_id'), ['case_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_case__tags_tag_id'), ['tag_id'], unique=False)

    op.create_table('case__template__tags',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('tag_id', sa.Integer(), nullable=True),
    sa.Column('case_id', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('case__template__tags', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_case__template__tags_case_id'), ['case_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_case__template__tags_tag_id'), ['tag_id'], unique=False)

    op.create_table('tags',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('task__tags',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('tag_id', sa.Integer(), nullable=True),
    sa.Column('task_id', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('task__tags', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_task__tags_tag_id'), ['tag_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_task__tags_task_id'), ['task_id'], unique=False)

    op.create_table('task__template__tags',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('tag_id', sa.Integer(), nullable=True),
    sa.Column('task_id', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('task__template__tags', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_task__template__tags_tag_id'), ['tag_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_task__template__tags_task_id'), ['task_id'], unique=False)

    with op.batch_alter_table('case', schema=None) as batch_op:
        batch_op.drop_column('taxonomies')

    with op.batch_alter_table('case__template', schema=None) as batch_op:
        batch_op.drop_column('taxonomies')

    with op.batch_alter_table('task', schema=None) as batch_op:
        batch_op.drop_column('taxonomies')

    with op.batch_alter_table('task__template', schema=None) as batch_op:
        batch_op.drop_column('taxonomies')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('task__template', schema=None) as batch_op:
        batch_op.add_column(sa.Column('taxonomies', sa.VARCHAR(), nullable=True))

    with op.batch_alter_table('task', schema=None) as batch_op:
        batch_op.add_column(sa.Column('taxonomies', sa.VARCHAR(), nullable=True))

    with op.batch_alter_table('case__template', schema=None) as batch_op:
        batch_op.add_column(sa.Column('taxonomies', sa.VARCHAR(), nullable=True))

    with op.batch_alter_table('case', schema=None) as batch_op:
        batch_op.add_column(sa.Column('taxonomies', sa.VARCHAR(), nullable=True))

    with op.batch_alter_table('task__template__tags', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_task__template__tags_task_id'))
        batch_op.drop_index(batch_op.f('ix_task__template__tags_tag_id'))

    op.drop_table('task__template__tags')
    with op.batch_alter_table('task__tags', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_task__tags_task_id'))
        batch_op.drop_index(batch_op.f('ix_task__tags_tag_id'))

    op.drop_table('task__tags')
    op.drop_table('tags')
    with op.batch_alter_table('case__template__tags', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_case__template__tags_tag_id'))
        batch_op.drop_index(batch_op.f('ix_case__template__tags_case_id'))

    op.drop_table('case__template__tags')
    with op.batch_alter_table('case__tags', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_case__tags_tag_id'))
        batch_op.drop_index(batch_op.f('ix_case__tags_case_id'))

    op.drop_table('case__tags')
    # ### end Alembic commands ###
