"""empty message

Revision ID: 576a43bf5702
Revises: 41069730c13d
Create Date: 2024-07-04 10:38:32.767039

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.exc import OperationalError


# revision identifiers, used by Alembic.
revision = '576a43bf5702'
down_revision = '41069730c13d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    try:
        op.create_table('case__template__custom__tags',
        sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
        sa.Column('case_template_id', sa.Integer(), nullable=True),
        sa.Column('custom_tag_id', sa.Integer(), nullable=True),
        sa.PrimaryKeyConstraint('id')
        )
        with op.batch_alter_table('case__template__custom__tags', schema=None) as batch_op:
            batch_op.create_index(batch_op.f('ix_case__template__custom__tags_case_template_id'), ['case_template_id'], unique=False)
            batch_op.create_index(batch_op.f('ix_case__template__custom__tags_custom_tag_id'), ['custom_tag_id'], unique=False)
    except OperationalError:
        print("Table 'case__template__custom__tags' already exist")

    try:
        op.create_table('task__template__custom__tags',
        sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
        sa.Column('task_template_id', sa.Integer(), nullable=True),
        sa.Column('custom_tag_id', sa.Integer(), nullable=True),
        sa.PrimaryKeyConstraint('id')
        )
        with op.batch_alter_table('task__template__custom__tags', schema=None) as batch_op:
            batch_op.create_index(batch_op.f('ix_task__template__custom__tags_custom_tag_id'), ['custom_tag_id'], unique=False)
            batch_op.create_index(batch_op.f('ix_task__template__custom__tags_task_template_id'), ['task_template_id'], unique=False)
    except OperationalError:
        print("Table 'task__template__custom__tags' already exist")

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('task__template__custom__tags', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_task__template__custom__tags_task_template_id'))
        batch_op.drop_index(batch_op.f('ix_task__template__custom__tags_custom_tag_id'))

    op.drop_table('task__template__custom__tags')
    with op.batch_alter_table('case__template__custom__tags', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_case__template__custom__tags_custom_tag_id'))
        batch_op.drop_index(batch_op.f('ix_case__template__custom__tags_case_template_id'))

    op.drop_table('case__template__custom__tags')
    # ### end Alembic commands ###
