"""empty message

Revision ID: 67847bdca48b
Revises: 9b6c2d1f4a7e
Create Date: 2026-06-02 15:32:52.049269

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.sql import table, column
import uuid


# revision identifiers, used by Alembic.
revision = '67847bdca48b'
down_revision = '9b6c2d1f4a7e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    connection = op.get_bind()
    inspector = sa.inspect(connection)
    existing_tables = inspector.get_table_names()

    if '_alembic_tmp_misp__attribute' in existing_tables:
        op.drop_table('_alembic_tmp_misp__attribute')
    
    # ==========================================
    # 1. Update 'case__misp__object' (UUID)
    # ==========================================
    with op.batch_alter_table('case__misp__object', schema=None) as batch_op:
        batch_op.add_column(sa.Column('uuid', sa.String(length=36), nullable=True))
        batch_op.create_index(batch_op.f('ix_case__misp__object_uuid'), ['uuid'], unique=False)

    # Define a temporary structure to query/update this specific table
    t_case_misp = table('case__misp__object', column('id', sa.Integer), column('uuid', sa.String))
    rows = connection.execute(sa.select(t_case_misp.c.id)).fetchall()
    for row in rows:
        connection.execute(
            t_case_misp.update().where(t_case_misp.c.id == row.id).values(uuid=str(uuid.uuid4()))
        )

    # ==========================================
    # 2. Update 'custom__tags' (UUID)
    # ==========================================
    with op.batch_alter_table('custom__tags', schema=None) as batch_op:
        batch_op.add_column(sa.Column('uuid', sa.String(length=36), nullable=True))
        batch_op.create_index(batch_op.f('ix_custom__tags_uuid'), ['uuid'], unique=False)

    t_custom_tags = table('custom__tags', column('id', sa.Integer), column('uuid', sa.String))
    rows = connection.execute(sa.select(t_custom_tags.c.id)).fetchall()
    for row in rows:
        connection.execute(
            t_custom_tags.update().where(t_custom_tags.c.id == row.id).values(uuid=str(uuid.uuid4()))
        )

    # ==========================================
    # 3. Update 'misp__attribute' (UUID)
    # ==========================================
    with op.batch_alter_table('misp__attribute', schema=None) as batch_op:
        batch_op.add_column(sa.Column('uuid', sa.String(length=36), nullable=True))
        batch_op.create_index(batch_op.f('ix_misp__attribute_uuid'), ['uuid'], unique=False)

    t_misp_attr = table('misp__attribute', column('id', sa.Integer), column('uuid', sa.String))
    rows = connection.execute(sa.select(t_misp_attr.c.id)).fetchall()
    for row in rows:
        connection.execute(
            t_misp_attr.update().where(t_misp_attr.c.id == row.id).values(uuid=str(uuid.uuid4()))
        )

    # ==========================================
    # 4. Update 'case__template' (DateTime)
    # ==========================================
    with op.batch_alter_table('case__template', schema=None) as batch_op:
        batch_op.add_column(sa.Column('creation_date', sa.DateTime(), nullable=True))
        batch_op.create_index(batch_op.f('ix_case__template_creation_date'), ['creation_date'], unique=False)

    # For dates, we can update all rows instantly in one database command
    t_case_tmp = table('case__template', column('creation_date', sa.DateTime))
    connection.execute(t_case_tmp.update().values(creation_date=sa.func.now()))

    # ==========================================
    # 5. Update 'note__template' (DateTime)
    # ==========================================
    with op.batch_alter_table('note__template', schema=None) as batch_op:
        batch_op.add_column(sa.Column('creation_date', sa.DateTime(), nullable=True))
        batch_op.create_index(batch_op.f('ix_note__template_creation_date'), ['creation_date'], unique=False)

    t_note_tmp = table('note__template', column('creation_date', sa.DateTime))
    connection.execute(t_note_tmp.update().values(creation_date=sa.func.now()))

    # ==========================================
    # 6. Update 'task__template' (DateTime)
    # ==========================================
    with op.batch_alter_table('task__template', schema=None) as batch_op:
        batch_op.add_column(sa.Column('creation_date', sa.DateTime(), nullable=True))
        batch_op.create_index(batch_op.f('ix_task__template_creation_date'), ['creation_date'], unique=False)

    t_task_tmp = table('task__template', column('creation_date', sa.DateTime))
    connection.execute(t_task_tmp.update().values(creation_date=sa.func.now()))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('task__template', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_task__template_creation_date'))
        batch_op.drop_column('creation_date')

    with op.batch_alter_table('note__template', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_note__template_creation_date'))
        batch_op.drop_column('creation_date')

    with op.batch_alter_table('misp__attribute', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_misp__attribute_uuid'))
        batch_op.drop_column('uuid')

    with op.batch_alter_table('custom__tags', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_custom__tags_uuid'))
        batch_op.drop_column('uuid')

    with op.batch_alter_table('case__template', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_case__template_creation_date'))
        batch_op.drop_column('creation_date')

    with op.batch_alter_table('case__misp__object', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_case__misp__object_uuid'))
        batch_op.drop_column('uuid')
    # ### end Alembic commands ###
