"""empty message

Revision ID: 698d53567382
Revises: 29493862f7a9
Create Date: 2025-07-02 10:28:07.798734

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.exc import OperationalError


# revision identifiers, used by Alembic.
revision = '698d53567382'
down_revision = '29493862f7a9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    try:
        with op.batch_alter_table('misp__attribute', schema=None) as batch_op:
            batch_op.add_column(sa.Column('disable_correlation', sa.Boolean(), nullable=True))
    except OperationalError:
        print("Column 'disable_correlation' already exist in 'misp__attribute'")

    try:
        with op.batch_alter_table('user', schema=None) as batch_op:
            batch_op.alter_column('password_hash',
                existing_type=sa.VARCHAR(length=128),
                type_=sa.String(length=165),
                existing_nullable=True)
    except OperationalError:
        print("Column 'password_hash' already modify in 'user'")

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    try:
        with op.batch_alter_table('user', schema=None) as batch_op:
            batch_op.alter_column('password_hash',
                existing_type=sa.String(length=165),
                type_=sa.VARCHAR(length=128),
                existing_nullable=True)
    except OperationalError:
        print("Column 'password_hash' already modify in 'user'")

    try:
        with op.batch_alter_table('misp__attribute', schema=None) as batch_op:
            batch_op.drop_column('disable_correlation')
    except OperationalError:
        print("Column 'disable_correlation' already dropped from 'misp__attribute'")

    # ### end Alembic commands ###
