"""empty message

Revision ID: 69e305fdc1b8
Revises: 44196916f12c
Create Date: 2024-08-20 10:46:49.931432

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.exc import OperationalError


# revision identifiers, used by Alembic.
revision = '69e305fdc1b8'
down_revision = '44196916f12c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    try:
        op.create_table('analyzer__result',
        sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
        sa.Column('origin_url', sa.String(), nullable=True),
        sa.Column('is_pending', sa.Boolean(), nullable=True),
        sa.Column('request_date', sa.DateTime(), nullable=True),
        sa.PrimaryKeyConstraint('id')
        )
        with op.batch_alter_table('analyzer__result', schema=None) as batch_op:
            batch_op.create_index(batch_op.f('ix_analyzer__result_origin_url'), ['origin_url'], unique=False)
            batch_op.create_index(batch_op.f('ix_analyzer__result_request_date'), ['request_date'], unique=False)
    except OperationalError:
        print("Table 'analyzer__result' already exist")

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('analyzer__result', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_analyzer__result_request_date'))
        batch_op.drop_index(batch_op.f('ix_analyzer__result_origin_url'))

    op.drop_table('analyzer__result')
    # ### end Alembic commands ###
