"""empty message

Revision ID: 69e305fdc1b8
Revises: 44196916f12c
Create Date: 2024-08-20 10:46:49.931432

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy import inspect
from sqlalchemy.exc import OperationalError


# revision identifiers, used by Alembic.
revision = '69e305fdc1b8'
down_revision = '44196916f12c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    bind = op.get_bind()
    inspector = inspect(bind)
    existing_tables = inspector.get_table_names()
    
    if 'analyzer__result' not in existing_tables:
        op.create_table('analyzer__result',
        sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
        sa.Column('origin_url', sa.String(), nullable=True),
        sa.Column('is_pending', sa.Boolean(), nullable=True),
        sa.Column('request_date', sa.DateTime(), nullable=True),
        sa.PrimaryKeyConstraint('id')
        )
        op.create_index('ix_analyzer__result_origin_url', 'analyzer__result', ['origin_url'], unique=False)
        op.create_index('ix_analyzer__result_request_date', 'analyzer__result', ['request_date'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    bind = op.get_bind()
    inspector = inspect(bind)
    existing_tables = inspector.get_table_names()
    
    if 'analyzer__result' in existing_tables:
        existing_indexes = [idx['name'] for idx in inspector.get_indexes('analyzer__result')]
        if 'ix_analyzer__result_request_date' in existing_indexes:
            op.drop_index('ix_analyzer__result_request_date', table_name='analyzer__result')
        if 'ix_analyzer__result_origin_url' in existing_indexes:
            op.drop_index('ix_analyzer__result_origin_url', table_name='analyzer__result')
        op.drop_table('analyzer__result')

    # ### end Alembic commands ###
