"""empty message

Revision ID: 6a9a28d9fb7a
Revises: 7760a877dff6
Create Date: 2024-10-18 14:31:37.764727

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.exc import OperationalError


# revision identifiers, used by Alembic.
revision = '6a9a28d9fb7a'
down_revision = '7760a877dff6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    try:
        with op.batch_alter_table('case', schema=None) as batch_op:
            batch_op.add_column(sa.Column('time_required', sa.String(), nullable=True))
    except OperationalError:
        print("Column 'time_required' already exist in 'case'")

    try:
        with op.batch_alter_table('case__template', schema=None) as batch_op:
            batch_op.add_column(sa.Column('time_required', sa.String(), nullable=True))
            batch_op.add_column(sa.Column('notes', sa.String(), nullable=True))
    except OperationalError:
        print("Column 'time_required' or 'notes' already exist in 'case__template'")

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    try:
        with op.batch_alter_table('case__template', schema=None) as batch_op:
            batch_op.drop_column('notes')
            batch_op.drop_column('time_required')
    except OperationalError:
        print("Column 'time_required' or 'notes' already dropped from 'case__template'")

    try:
        with op.batch_alter_table('case', schema=None) as batch_op:
            batch_op.drop_column('time_required')
    except OperationalError:
        print("Column 'time_required' already dropped from 'case'")

    # ### end Alembic commands ###
