"""empty message

Revision ID: 724ed0d8ae74
Revises: 333440cacf71
Create Date: 2025-09-25 11:37:13.272600

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.exc import OperationalError


# revision identifiers, used by Alembic.
revision = '724ed0d8ae74'
down_revision = '333440cacf71'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    bind = op.get_bind()
    inspector = sa.inspect(bind)
    case_column = [col['name'] for col in inspector.get_columns('case')]

    if 'is_updated_from_misp' not in case_column:
        with op.batch_alter_table('case', schema=None) as batch_op:
            batch_op.add_column(sa.Column('is_updated_from_misp', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    bind = op.get_bind()
    inspector = sa.inspect(bind)
    case_column = [col['name'] for col in inspector.get_columns('case')]

    if 'is_updated_from_misp' in case_column:
        with op.batch_alter_table('case', schema=None) as batch_op:
            batch_op.drop_column('is_updated_from_misp')
    # ### end Alembic commands ###
