"""empty message

Revision ID: 724ed0d8ae74
Revises: 333440cacf71
Create Date: 2025-09-25 11:37:13.272600

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.exc import OperationalError


# revision identifiers, used by Alembic.
revision = '724ed0d8ae74'
down_revision = '333440cacf71'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    try:
        with op.batch_alter_table('case', schema=None) as batch_op:
            batch_op.add_column(sa.Column('is_created_from_misp', sa.String(length=36), nullable=True))
    except OperationalError:
        print("Column 'is_created_from_misp' already exist in 'case'")

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    try:
        with op.batch_alter_table('case', schema=None) as batch_op:
            batch_op.drop_column('is_created_from_misp')
    except OperationalError:
        print("Column 'is_created_from_misp' already dropped from 'case'")
    # ### end Alembic commands ###
