"""empty message

Revision ID: 73b8cc4d3c54
Revises: c42cd6e3e1ea
Create Date: 2023-12-07 10:05:44.775815

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy import inspect
from sqlalchemy.exc import OperationalError


# revision identifiers, used by Alembic.
revision = '73b8cc4d3c54'
down_revision = 'c42cd6e3e1ea'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    bind = op.get_bind()
    inspector = inspect(bind)
    existing_columns = [col['name'] for col in inspector.get_columns('tags')]
    
    if 'description' not in existing_columns:
        op.add_column('tags', sa.Column('description', sa.String(), nullable=True))
    if 'expanded' not in existing_columns:
        op.add_column('tags', sa.Column('expanded', sa.String(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    bind = op.get_bind()
    inspector = inspect(bind)
    existing_columns = [col['name'] for col in inspector.get_columns('tags')]
    
    if 'expanded' in existing_columns:
        op.drop_column('tags', 'expanded')
    if 'description' in existing_columns:
        op.drop_column('tags', 'description')

    # ### end Alembic commands ###
