"""Add org_admin to Role model

Revision ID: 7437a55c703f
Revises: a1d8a776d21e
Create Date: 2026-01-22 07:57:32.726129

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7437a55c703f'
down_revision = 'a1d8a776d21e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###

    bind = op.get_bind()
    inspector = sa.inspect(bind)
    role_columns = [col['name'] for col in inspector.get_columns('role')]
    if 'org_admin' not in role_columns:
        with op.batch_alter_table('role', schema=None) as batch_op:
            batch_op.add_column(sa.Column('org_admin', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###

    bind = op.get_bind()
    inspector = sa.inspect(bind)
    role_columns = [col['name'] for col in inspector.get_columns('role')]
    if 'org_admin' in role_columns:
        with op.batch_alter_table('role', schema=None) as batch_op:
            batch_op.drop_column('org_admin')

    # ### end Alembic commands ###
