"""empty message

Revision ID: 74b67b392f32
Revises: 19fb9265b8c1
Create Date: 2023-11-17 11:10:54.352020

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy import inspect


# revision identifiers, used by Alembic.
revision = '74b67b392f32'
down_revision = '19fb9265b8c1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # Check if columns exist before adding
    bind = op.get_bind()
    inspector = inspect(bind)
    
    # Check cluster table
    cluster_columns = [col['name'] for col in inspector.get_columns('cluster')]
    if 'exclude' not in cluster_columns:
        op.add_column('cluster', sa.Column('exclude', sa.Boolean(), nullable=True))
    if 'tag' not in cluster_columns:
        op.add_column('cluster', sa.Column('tag', sa.String(), nullable=True))

    # Check galaxy table
    galaxy_columns = [col['name'] for col in inspector.get_columns('galaxy')]
    if 'exclude' not in galaxy_columns:
        op.add_column('galaxy', sa.Column('exclude', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('galaxy', schema=None) as batch_op:
        batch_op.drop_column('exclude')

    with op.batch_alter_table('cluster', schema=None) as batch_op:
        batch_op.drop_column('tag')
        batch_op.drop_column('exclude')

    # ### end Alembic commands ###
