"""empty message

Revision ID: 74b67b392f32
Revises: 19fb9265b8c1
Create Date: 2023-11-17 11:10:54.352020

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.exc import OperationalError


# revision identifiers, used by Alembic.
revision = '74b67b392f32'
down_revision = '19fb9265b8c1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    try:
        with op.batch_alter_table('cluster', schema=None) as batch_op:
            batch_op.add_column(sa.Column('exclude', sa.Boolean(), nullable=True))
            batch_op.add_column(sa.Column('tag', sa.String(), nullable=True))
    except OperationalError:
        print("Column 'exclude' and 'tag' already exist in 'cluster'")

    try:
        with op.batch_alter_table('galaxy', schema=None) as batch_op:
            batch_op.add_column(sa.Column('exclude', sa.Boolean(), nullable=True))
    except OperationalError:
        print("Column 'exclude' already exist in 'galaxy'")

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('galaxy', schema=None) as batch_op:
        batch_op.drop_column('exclude')

    with op.batch_alter_table('cluster', schema=None) as batch_op:
        batch_op.drop_column('tag')
        batch_op.drop_column('exclude')

    # ### end Alembic commands ###
