"""empty message

Revision ID: 762a4317af55
Revises: 312b3d2223d6
Create Date: 2024-07-02 15:28:13.227255

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy import inspect


# revision identifiers, used by Alembic.
revision = '762a4317af55'
down_revision = '312b3d2223d6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    bind = op.get_bind()
    inspector = inspect(bind)
    existing_tables = inspector.get_table_names()
    
    if 'case__custom__tags' not in existing_tables:
        op.create_table('case__custom__tags',
        sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
        sa.Column('case_id', sa.Integer(), nullable=True),
        sa.Column('custom_tag_id', sa.Integer(), nullable=True),
        sa.PrimaryKeyConstraint('id')
        )
        op.create_index('ix_case__custom__tags_case_id', 'case__custom__tags', ['case_id'], unique=False)
        op.create_index('ix_case__custom__tags_custom_tag_id', 'case__custom__tags', ['custom_tag_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('case__custom__tags', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_case__custom__tags_custom_tag_id'))
        batch_op.drop_index(batch_op.f('ix_case__custom__tags_case_id'))

    op.drop_table('case__custom__tags')
    # ### end Alembic commands ###
