"""empty message

Revision ID: 7760a877dff6
Revises: 3a0416665c4b
Create Date: 2024-10-17 11:16:03.447654

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.exc import OperationalError


# revision identifiers, used by Alembic.
revision = '7760a877dff6'
down_revision = '3a0416665c4b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    try:
        with op.batch_alter_table('task__template', schema=None) as batch_op:
            batch_op.add_column(sa.Column('time_required', sa.String(), nullable=True))
    except OperationalError:
        print("Column 'time_required' already exist in 'task__template'")

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    try:
        with op.batch_alter_table('task__template', schema=None) as batch_op:
            batch_op.drop_column('time_required')
    except OperationalError:
        print("Column 'time_required' already dropped from 'task__template'")

    # ### end Alembic commands ###
