"""empty message

Revision ID: 77984d64c89e
Revises: 8f00b18976f9
Create Date: 2025-03-19 11:57:05.950267

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.exc import OperationalError


# revision identifiers, used by Alembic.
revision = '77984d64c89e'
down_revision = '8f00b18976f9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    try:
        with op.batch_alter_table('case', schema=None) as batch_op:
            batch_op.add_column(sa.Column('ticket_id', sa.String(), nullable=True))
    except OperationalError:
        print("Column 'ticket_id' already exist in Case")

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    try:
        with op.batch_alter_table('case', schema=None) as batch_op:
            batch_op.drop_column('ticket_id')
    except OperationalError:
        print("Column 'ticket_id' already dropped from Case")

    # ### end Alembic commands ###
