"""empty message

Revision ID: 77984d64c89e
Revises: 8f00b18976f9
Create Date: 2025-03-19 11:57:05.950267

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy import inspect


# revision identifiers, used by Alembic.
revision = '77984d64c89e'
down_revision = '8f00b18976f9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # Check if column exists before adding
    bind = op.get_bind()
    inspector = inspect(bind)
    existing_columns = [col['name'] for col in inspector.get_columns('case')]
    
    if 'ticket_id' not in existing_columns:
        op.add_column('case', sa.Column('ticket_id', sa.String(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # Check if column exists before dropping
    bind = op.get_bind()
    inspector = inspect(bind)
    existing_columns = [col['name'] for col in inspector.get_columns('case')]
    
    if 'ticket_id' in existing_columns:
        op.drop_column('case', 'ticket_id')

    # ### end Alembic commands ###
