"""empty message

Revision ID: 7d5996650e44
Revises: d46002a5f863
Create Date: 2025-07-31 13:37:59.847139

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.exc import OperationalError


# revision identifiers, used by Alembic.
revision = '7d5996650e44'
down_revision = 'd46002a5f863'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    try:
        with op.batch_alter_table('misp__attribute', schema=None) as batch_op:
            batch_op.add_column(sa.Column('object_relation', sa.String(), nullable=True))
            batch_op.create_index(batch_op.f('ix_misp__attribute_object_relation'), ['object_relation'], unique=False)
    except OperationalError:
        print("Column 'object_relation' already exist in 'misp__attribute'")

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    try:
        with op.batch_alter_table('misp__attribute', schema=None) as batch_op:
            batch_op.drop_index(batch_op.f('ix_misp__attribute_object_relation'))
            batch_op.drop_column('object_relation')
    except OperationalError:
        print("Column 'object_relation' already dropped from 'misp__attribute'")

    # ### end Alembic commands ###
