"""empty message

Revision ID: 7d5996650e44
Revises: d46002a5f863
Create Date: 2025-07-31 13:37:59.847139

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy import inspect
from sqlalchemy.exc import OperationalError


# revision identifiers, used by Alembic.
revision = '7d5996650e44'
down_revision = 'd46002a5f863'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # Check if column exists before adding
    bind = op.get_bind()
    inspector = inspect(bind)
    existing_columns = [col['name'] for col in inspector.get_columns('misp__attribute')]
    
    if 'object_relation' not in existing_columns:
        op.add_column('misp__attribute', sa.Column('object_relation', sa.String(), nullable=True))
        op.create_index('ix_misp__attribute_object_relation', 'misp__attribute', ['object_relation'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    bind = op.get_bind()
    inspector = inspect(bind)
    existing_columns = [col['name'] for col in inspector.get_columns('misp__attribute')]
    
    if 'object_relation' in existing_columns:
        existing_indexes = [idx['name'] for idx in inspector.get_indexes('misp__attribute')]
        if 'ix_misp__attribute_object_relation' in existing_indexes:
            op.drop_index('ix_misp__attribute_object_relation', table_name='misp__attribute')
        op.drop_column('misp__attribute', 'object_relation')

    # ### end Alembic commands ###
