"""Add Task_External_Reference table

Revision ID: 8e8ade3bbb4a
Revises: 33e4650639fd
Create Date: 2026-02-09 18:57:19.084504

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8e8ade3bbb4a'
down_revision = '33e4650639fd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('task__external__reference',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('task_id', sa.Integer(), nullable=True),
    sa.Column('url', sa.String(), nullable=True),
    sa.Column('uuid', sa.String(length=36), nullable=True),
    sa.ForeignKeyConstraint(['task_id'], ['task.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('task__external__reference', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_task__external__reference_url'), ['url'], unique=False)
        batch_op.create_index(batch_op.f('ix_task__external__reference_uuid'), ['uuid'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('task__external__reference', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_task__external__reference_uuid'))
        batch_op.drop_index(batch_op.f('ix_task__external__reference_url'))

    op.drop_table('task__external__reference')
    # ### end Alembic commands ###
