"""empty message

Revision ID: 93068451b88b
Revises: 994eadb096f7
Create Date: 2025-04-09 09:57:18.144835

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.exc import OperationalError


# revision identifiers, used by Alembic.
revision = '93068451b88b'
down_revision = '994eadb096f7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    try:
        with op.batch_alter_table('misp__attribute', schema=None) as batch_op:
            batch_op.add_column(sa.Column('first_seen', sa.DateTime(), nullable=True))
            batch_op.add_column(sa.Column('last_seen', sa.DateTime(), nullable=True))
            batch_op.add_column(sa.Column('comment', sa.String(), nullable=True))
            batch_op.add_column(sa.Column('ids_flag', sa.Boolean(), nullable=True))
            batch_op.create_index(batch_op.f('ix_misp__attribute_first_seen'), ['first_seen'], unique=False)
            batch_op.create_index(batch_op.f('ix_misp__attribute_last_seen'), ['last_seen'], unique=False)
    except OperationalError:
        print("Columns already exist in 'misp__attribute'")

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    try:
        with op.batch_alter_table('misp__attribute', schema=None) as batch_op:
            batch_op.drop_index(batch_op.f('ix_misp__attribute_last_seen'))
            batch_op.drop_index(batch_op.f('ix_misp__attribute_first_seen'))
            batch_op.drop_column('ids_flag')
            batch_op.drop_column('comment')
            batch_op.drop_column('last_seen')
            batch_op.drop_column('first_seen')
    except OperationalError:
        print("Columns already dropped from 'misp__attribute'")

    # ### end Alembic commands ###
