"""empty message

Revision ID: 93068451b88b
Revises: 994eadb096f7
Create Date: 2025-04-09 09:57:18.144835

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy import inspect
from sqlalchemy.exc import OperationalError


# revision identifiers, used by Alembic.
revision = '93068451b88b'
down_revision = '994eadb096f7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    bind = op.get_bind()
    inspector = inspect(bind)
    existing_columns = [col['name'] for col in inspector.get_columns('misp__attribute')]
    
    if 'first_seen' not in existing_columns:
        op.add_column('misp__attribute', sa.Column('first_seen', sa.DateTime(), nullable=True))
        op.create_index('ix_misp__attribute_first_seen', 'misp__attribute', ['first_seen'], unique=False)
    if 'last_seen' not in existing_columns:
        op.add_column('misp__attribute', sa.Column('last_seen', sa.DateTime(), nullable=True))
        op.create_index('ix_misp__attribute_last_seen', 'misp__attribute', ['last_seen'], unique=False)
    if 'comment' not in existing_columns:
        op.add_column('misp__attribute', sa.Column('comment', sa.String(), nullable=True))
    if 'ids_flag' not in existing_columns:
        op.add_column('misp__attribute', sa.Column('ids_flag', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    bind = op.get_bind()
    inspector = inspect(bind)
    existing_columns = [col['name'] for col in inspector.get_columns('misp__attribute')]
    existing_indexes = [idx['name'] for idx in inspector.get_indexes('misp__attribute')]
    
    if 'last_seen' in existing_columns:
        if 'ix_misp__attribute_last_seen' in existing_indexes:
            op.drop_index('ix_misp__attribute_last_seen', table_name='misp__attribute')
        op.drop_column('misp__attribute', 'last_seen')
    if 'first_seen' in existing_columns:
        if 'ix_misp__attribute_first_seen' in existing_indexes:
            op.drop_index('ix_misp__attribute_first_seen', table_name='misp__attribute')
        op.drop_column('misp__attribute', 'first_seen')
    if 'ids_flag' in existing_columns:
        op.drop_column('misp__attribute', 'ids_flag')
    if 'comment' in existing_columns:
        op.drop_column('misp__attribute', 'comment')

    # ### end Alembic commands ###
