"""empty message

Revision ID: 9ee9484a8102
Revises: a421e8f2f851
Create Date: 2023-10-27 08:38:20.565663

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.exc import OperationalError


# revision identifiers, used by Alembic.
revision = '9ee9484a8102'
down_revision = 'a421e8f2f851'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    try:
        with op.batch_alter_table('task', schema=None) as batch_op:
            batch_op.add_column(sa.Column('taxonomies', sa.String(), nullable=True))
    except OperationalError:
        print("Column 'taxonomies' already exist in 'task'")

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('task', schema=None) as batch_op:
        batch_op.drop_column('taxonomies')

    # ### end Alembic commands ###
