import datetime
from alembic import op
import sqlalchemy as sa
from sqlalchemy import inspect


# revision identifiers, used by Alembic.
revision = '9ffdc12e43a9'
down_revision = '576a43bf5702'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    bind = op.get_bind()
    inspector = inspect(bind)
    
    # Add last_modif to case__template
    case_template_columns = [col['name'] for col in inspector.get_columns('case__template')]
    if 'last_modif' not in case_template_columns:
        op.add_column('case__template', sa.Column('last_modif', sa.DateTime(), nullable=True))
        op.create_index('ix_case__template_last_modif', 'case__template', ['last_modif'], unique=False)

    # Add last_modif to task__template
    task_template_columns = [col['name'] for col in inspector.get_columns('task__template')]
    if 'last_modif' not in task_template_columns:
        op.add_column('task__template', sa.Column('last_modif', sa.DateTime(), nullable=True))
        op.create_index('ix_task__template_last_modif', 'task__template', ['last_modif'], unique=False)

    connection = op.get_bind()
    current_time = datetime.datetime.now(tz=datetime.timezone.utc)

    cases = connection.execute(sa.text("SELECT id FROM case__template")).fetchall()
    tasks = connection.execute(sa.text("SELECT id FROM task__template")).fetchall()

    for case_ in cases:
        connection.execute(
            sa.text("UPDATE case__template SET last_modif = :last_modif WHERE id = :id"),
            {'last_modif': current_time, 'id': case_.id}
        )

    for task in tasks:
        connection.execute(
            sa.text("UPDATE task__template SET last_modif = :last_modif WHERE id = :id"),
            {'last_modif': current_time, 'id': task.id}
        )
    
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('task__template', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_task__template_last_modif'))
        batch_op.drop_column('last_modif')

    with op.batch_alter_table('case__template', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_case__template_last_modif'))
        batch_op.drop_column('last_modif')

    # ### end Alembic commands ###
