"""Add file metadata fields (upload_date, file_size, file_type)

Revision ID: a1d8a776d21e
Revises: f0c8b2c9e75d
Create Date: 2026-01-16 19:58:16.406004

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a1d8a776d21e'
down_revision = 'f0c8b2c9e75d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('file', schema=None) as batch_op:
        batch_op.add_column(sa.Column('upload_date', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('file_size', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('file_type', sa.String(length=100), nullable=True))
        batch_op.drop_constraint(batch_op.f('fk_file_case_id'), type_='foreignkey')
        batch_op.drop_column('case_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('file', schema=None) as batch_op:
        batch_op.add_column(sa.Column('case_id', sa.INTEGER(), nullable=True))
        batch_op.create_foreign_key(batch_op.f('fk_file_case_id'), 'case', ['case_id'], ['id'], ondelete='CASCADE')
        batch_op.drop_column('file_type')
        batch_op.drop_column('file_size')
        batch_op.drop_column('upload_date')

    # ### end Alembic commands ###
