"""Add file metadata fields (upload_date, file_size, file_type)

Revision ID: a1d8a776d21e
Revises: f0c8b2c9e75d
Create Date: 2026-01-16 19:58:16.406004

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a1d8a776d21e'
down_revision = 'f0c8b2c9e75d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###

    bind = op.get_bind()
    inspector = sa.inspect(bind)
    file_columns = [col['name'] for col in inspector.get_columns('file')]
    with op.batch_alter_table('file', schema=None) as batch_op:
        if 'upload_date' not in file_columns:
            batch_op.add_column(sa.Column('upload_date', sa.DateTime(), nullable=True))
        if 'file_size' not in file_columns:
            batch_op.add_column(sa.Column('file_size', sa.Integer(), nullable=True))
        if 'file_type' not in file_columns:
            batch_op.add_column(sa.Column('file_type', sa.String(length=100), nullable=True))
        
        if 'case_id' in file_columns:
            batch_op.drop_constraint(batch_op.f('fk_file_case_id'), type_='foreignkey')
            batch_op.drop_column('case_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    bind = op.get_bind()
    inspector = sa.inspect(bind)
    file_columns = [col['name'] for col in inspector.get_columns('file')]
    with op.batch_alter_table('file', schema=None) as batch_op:
        if 'file_type' in file_columns:
            batch_op.drop_column('file_type')
        if 'file_size' in file_columns:
            batch_op.drop_column('file_size')
        if 'upload_date' in file_columns:
            batch_op.drop_column('upload_date')

    # ### end Alembic commands ###
