"""empty message

Revision ID: a421e8f2f851
Revises: ac7be233b619
Create Date: 2023-10-25 11:38:15.149139

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.exc import OperationalError


# revision identifiers, used by Alembic.
revision = 'a421e8f2f851'
down_revision = 'ac7be233b619'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    try:
        with op.batch_alter_table('case', schema=None) as batch_op:
            batch_op.add_column(sa.Column('taxonomies', sa.String(), nullable=True))
    except OperationalError:
        print("Column 'taxonomies' already exist in 'case'")

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('case', schema=None) as batch_op:
        batch_op.drop_column('taxonomies')

    # ### end Alembic commands ###
