"""empty message

Revision ID: a421e8f2f851
Revises: ac7be233b619
Create Date: 2023-10-25 11:38:15.149139

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy import inspect
from sqlalchemy.exc import OperationalError


# revision identifiers, used by Alembic.
revision = 'a421e8f2f851'
down_revision = 'ac7be233b619'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    bind = op.get_bind()
    inspector = inspect(bind)
    existing_columns = [col['name'] for col in inspector.get_columns('case')]
    
    if 'taxonomies' not in existing_columns:
        op.add_column('case', sa.Column('taxonomies', sa.String(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    bind = op.get_bind()
    inspector = inspect(bind)
    existing_columns = [col['name'] for col in inspector.get_columns('case')]
    
    if 'taxonomies' in existing_columns:
        op.drop_column('case', 'taxonomies')

    # ### end Alembic commands ###
