"""empty message

Revision ID: a5e09a98ee8e
Revises: case_admin_001
Create Date: 2026-02-02 13:36:51.028256

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a5e09a98ee8e'
down_revision = 'case_admin_001'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###

    conn = op.get_bind()
    inspector = sa.inspect(conn)
    existing_tables = inspector.get_table_names()

    if 'case__misp__object__connector__instance' in existing_tables:
        with op.batch_alter_table('case__misp__object__connector__instance', schema=None) as batch_op:
            batch_op.drop_index(batch_op.f('ix_case__misp__object__connector__instance_case_id'))
            batch_op.drop_index(batch_op.f('ix_case__misp__object__connector__instance_instance_id'))

        op.drop_table('case__misp__object__connector__instance')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    conn = op.get_bind()
    inspector = sa.inspect(conn)
    existing_tables = inspector.get_table_names()
    if 'case__misp__object__connector__instance' not in existing_tables:
        op.create_table('case__misp__object__connector__instance',
        sa.Column('id', sa.INTEGER(), nullable=False),
        sa.Column('case_id', sa.INTEGER(), nullable=True),
        sa.Column('instance_id', sa.INTEGER(), nullable=True),
        sa.Column('identifier', sa.VARCHAR(), nullable=True),
        sa.PrimaryKeyConstraint('id')
        )
        with op.batch_alter_table('case__misp__object__connector__instance', schema=None) as batch_op:
            batch_op.create_index(batch_op.f('ix_case__misp__object__connector__instance_instance_id'), ['instance_id'], unique=False)
            batch_op.create_index(batch_op.f('ix_case__misp__object__connector__instance_case_id'), ['case_id'], unique=False)

    # ### end Alembic commands ###
