"""empty message

Revision ID: a878d2c91115
Revises: 4a544282986e
Create Date: 2023-11-02 11:05:46.900725

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.exc import OperationalError


# revision identifiers, used by Alembic.
revision = 'a878d2c91115'
down_revision = '4a544282986e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    try:
        with op.batch_alter_table('tags', schema=None) as batch_op:
            batch_op.add_column(sa.Column('color', sa.String(), nullable=True))
    except OperationalError:
        print("Column 'color' already exist in 'tags'")

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tags', schema=None) as batch_op:
        batch_op.drop_column('color')

    # ### end Alembic commands ###
