"""empty message

Revision ID: a878d2c91115
Revises: 4a544282986e
Create Date: 2023-11-02 11:05:46.900725

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy import inspect
from sqlalchemy import inspect


# revision identifiers, used by Alembic.
revision = 'a878d2c91115'
down_revision = '4a544282986e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    
    # Obtenir l'inspecteur pour vérifier l'existence des tables et colonnes
    conn = op.get_bind()
    inspector = inspect(conn)
    existing_tables = inspector.get_table_names()
    
    # Ajouter colonne color à tags si elle n'existe pas
    if 'tags' in existing_tables:
        columns = [col['name'] for col in inspector.get_columns('tags')]
        if 'color' not in columns:
            op.add_column('tags', sa.Column('color', sa.String(), nullable=True))
            print("Added color column to tags")
        else:
            print("Column color already exists in tags")
    else:
        print("Table tags does not exist")

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tags', schema=None) as batch_op:
        batch_op.drop_column('color')

    # ### end Alembic commands ###
