"""add version to case and task templates

Revision ID: a95e730510d6
Revises: 598df1c175e3
Create Date: 2026-02-26 09:23:35.915330

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a95e730510d6'
down_revision = '598df1c175e3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('case__template', schema=None) as batch_op:
        batch_op.add_column(sa.Column('version', sa.Integer(), nullable=True))

    with op.batch_alter_table('task__template', schema=None) as batch_op:
        batch_op.add_column(sa.Column('version', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('task__template', schema=None) as batch_op:
        batch_op.drop_column('version')

    with op.batch_alter_table('case__template', schema=None) as batch_op:
        batch_op.drop_column('version')

    # ### end Alembic commands ###
