"""empty message

Revision ID: ab99c63cd1c2
Revises: 04ee0d5e0abb
Create Date: 2023-11-29 12:10:42.882375

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy import inspect


# revision identifiers, used by Alembic.
revision = 'ab99c63cd1c2'
down_revision = '04ee0d5e0abb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # Check if column exists before adding
    bind = op.get_bind()
    inspector = inspect(bind)
    existing_columns = [col['name'] for col in inspector.get_columns('connector__icon')]
    
    if 'description' not in existing_columns:
        op.add_column('connector__icon', sa.Column('description', sa.String(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('connector__icon', schema=None) as batch_op:
        batch_op.drop_column('description')

    # ### end Alembic commands ###
