"""empty message

Revision ID: ac7be233b619
Revises: 6c71bd3c10d8
Create Date: 2023-08-17 15:25:08.253145

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.exc import OperationalError


# revision identifiers, used by Alembic.
revision = 'ac7be233b619'
down_revision = '6c71bd3c10d8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    try:
        op.create_table('recurring__notification',
        sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
        sa.Column('user_id', sa.Integer(), nullable=True),
        sa.Column('case_id', sa.Integer(), nullable=True),
        sa.PrimaryKeyConstraint('id')
        )
        with op.batch_alter_table('recurring__notification', schema=None) as batch_op:
            batch_op.create_index(batch_op.f('ix_recurring__notification_case_id'), ['case_id'], unique=False)
            batch_op.create_index(batch_op.f('ix_recurring__notification_user_id'), ['user_id'], unique=False)
    except OperationalError:
        print("Table recurring__notification already exist")

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('recurring__notification', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_recurring__notification_user_id'))
        batch_op.drop_index(batch_op.f('ix_recurring__notification_case_id'))

    op.drop_table('recurring__notification')
    # ### end Alembic commands ###
