"""Add case_admin to Role model

Revision ID: case_admin_001
Revises: queue_roles_001, 29a27d426ed3
Create Date: 2026-02-01 00:00:00.000000

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'case_admin_001'
down_revision = ('queue_roles_001', '29a27d426ed3')
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###

    bind = op.get_bind()
    inspector = sa.inspect(bind)
    role_columns = [col['name'] for col in inspector.get_columns('role')]
    
    with op.batch_alter_table('role', schema=None) as batch_op:
        if 'case_admin' not in role_columns:
            batch_op.add_column(sa.Column('case_admin', sa.Boolean(), nullable=True, default=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###

    bind = op.get_bind()
    inspector = sa.inspect(bind)
    role_columns = [col['name'] for col in inspector.get_columns('role')]
    
    with op.batch_alter_table('role', schema=None) as batch_op:
        if 'case_admin' in role_columns:
            batch_op.drop_column('case_admin')

    # ### end Alembic commands ###
