"""empty message

Revision ID: b8d53a427749
Revises: 165fdb190dd0
Create Date: 2024-04-24 10:00:33.892980

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy import inspect


# revision identifiers, used by Alembic.
revision = 'b8d53a427749'
down_revision = '165fdb190dd0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # Check if columns exist before adding
    bind = op.get_bind()
    inspector = inspect(bind)
    
    # Check case__connector__instance table
    case_connector_columns = [col['name'] for col in inspector.get_columns('case__connector__instance')]
    if 'identifier' not in case_connector_columns:
        op.add_column('case__connector__instance', sa.Column('identifier', sa.String(), nullable=True))

    # Check task__connector__instance table
    task_connector_columns = [col['name'] for col in inspector.get_columns('task__connector__instance')]
    if 'identifier' not in task_connector_columns:
        op.add_column('task__connector__instance', sa.Column('identifier', sa.String(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('task__connector__instance', schema=None) as batch_op:
        batch_op.drop_column('identifier')

    with op.batch_alter_table('case__connector__instance', schema=None) as batch_op:
        batch_op.drop_column('identifier')

    # ### end Alembic commands ###
