"""empty message

Revision ID: b90304f277d7
Revises: 3f0bfdc6f04e
Create Date: 2023-12-19 08:36:49.726272

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy import inspect


# revision identifiers, used by Alembic.
revision = 'b90304f277d7'
down_revision = '3f0bfdc6f04e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    bind = op.get_bind()
    inspector = inspect(bind)
    existing_tables = inspector.get_table_names()
    
    # Create case__connector__id table
    if 'case__connector__id' not in existing_tables:
        op.create_table('case__connector__id',
        sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
        sa.Column('case_id', sa.Integer(), nullable=True),
        sa.Column('instance_id', sa.Integer(), nullable=True),
        sa.Column('identifier', sa.String(), nullable=True),
        sa.PrimaryKeyConstraint('id')
        )
        op.create_index('ix_case__connector__id_case_id', 'case__connector__id', ['case_id'], unique=False)
        op.create_index('ix_case__connector__id_instance_id', 'case__connector__id', ['instance_id'], unique=False)

    # Create case__connector__instance table
    if 'case__connector__instance' not in existing_tables:
        op.create_table('case__connector__instance',
        sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
        sa.Column('case_id', sa.Integer(), nullable=True),
        sa.Column('instance_id', sa.Integer(), nullable=True),
        sa.PrimaryKeyConstraint('id')
        )
        op.create_index('ix_case__connector__instance_case_id', 'case__connector__instance', ['case_id'], unique=False)
        op.create_index('ix_case__connector__instance_instance_id', 'case__connector__instance', ['instance_id'], unique=False)

    # Create case__template__connector__instance table
    if 'case__template__connector__instance' not in existing_tables:
        op.create_table('case__template__connector__instance',
        sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
        sa.Column('template_id', sa.Integer(), nullable=True),
        sa.Column('instance_id', sa.Integer(), nullable=True),
        sa.PrimaryKeyConstraint('id')
        )
        op.create_index('ix_case__template__connector__instance_instance_id', 'case__template__connector__instance', ['instance_id'], unique=False)
        op.create_index('ix_case__template__connector__instance_template_id', 'case__template__connector__instance', ['template_id'], unique=False)

    # Create task__connector__id table
    if 'task__connector__id' not in existing_tables:
        op.create_table('task__connector__id',
        sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
        sa.Column('task_id', sa.Integer(), nullable=True),
        sa.Column('instance_id', sa.Integer(), nullable=True),
        sa.Column('identifier', sa.String(), nullable=True),
        sa.PrimaryKeyConstraint('id')
        )
        op.create_index('ix_task__connector__id_instance_id', 'task__connector__id', ['instance_id'], unique=False)
        op.create_index('ix_task__connector__id_task_id', 'task__connector__id', ['task_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('task__connector__id', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_task__connector__id_task_id'))
        batch_op.drop_index(batch_op.f('ix_task__connector__id_instance_id'))

    op.drop_table('task__connector__id')
    with op.batch_alter_table('case__template__connector__instance', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_case__template__connector__instance_template_id'))
        batch_op.drop_index(batch_op.f('ix_case__template__connector__instance_instance_id'))

    op.drop_table('case__template__connector__instance')
    with op.batch_alter_table('case__connector__instance', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_case__connector__instance_instance_id'))
        batch_op.drop_index(batch_op.f('ix_case__connector__instance_case_id'))

    op.drop_table('case__connector__instance')
    with op.batch_alter_table('case__connector__id', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_case__connector__id_instance_id'))
        batch_op.drop_index(batch_op.f('ix_case__connector__id_case_id'))

    op.drop_table('case__connector__id')
    # ### end Alembic commands ###
