"""postgres follow-up after mariadb compatibility model changes
The first MariaDB install must be stamped on this migration file as of v3.4.0
!!! As soon as MariaDB database is initialised and stamped to head with this current migration file
it must NOT be downgraded by construction because previous versions were incompatible with MariaDB
due to the VARCHAR() or db.String() with no length !!!

Revision ID: b9cde1d4adca
Revises: e1a2b3c4d5f6
Create Date: 2026-06-16 17:59:17.106515

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'b9cde1d4adca'
down_revision = 'e1a2b3c4d5f6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.alter_column('matrix_id',
               existing_type=sa.VARCHAR(), # As it should normally be in Postgres
               type_=sa.String(length=64),
               existing_nullable=True)
    
    with op.batch_alter_table('case', schema=None) as batch_op:
        batch_op.alter_column('title',
               existing_type=sa.VARCHAR(),
               type_=sa.String(length=255),
               existing_nullable=True)
        batch_op.alter_column('description',
               existing_type=sa.VARCHAR(),
               type_=sa.Text(),
               existing_nullable=True)
        batch_op.alter_column('notes',
               existing_type=sa.VARCHAR(),
               type_=sa.Text(),
               existing_nullable=True)
        batch_op.alter_column('hedgedoc_url',
               existing_type=sa.VARCHAR(),
               type_=sa.String(length=255),
               existing_nullable=True)
        batch_op.alter_column('time_required',
               existing_type=sa.VARCHAR(),
               type_=sa.String(length=64),
               existing_nullable=True)
        batch_op.alter_column('computer_assistate_report',
               existing_type=sa.VARCHAR(),
               type_=sa.Text().with_variant(
                   sa.dialects.mysql.LONGTEXT(),
                   "mysql",
                   "mariadb",
               ),
               existing_nullable=True)
        batch_op.alter_column('computer_assistate_model',
               existing_type=sa.VARCHAR(),
               type_=sa.String(64),
               existing_nullable=True)
        batch_op.alter_column('ticket_id',
               existing_type=sa.VARCHAR(),
               type_=sa.String(length=128),
               existing_nullable=True)

    with op.batch_alter_table('task', schema=None) as batch_op:
        batch_op.alter_column('title',
               existing_type=sa.VARCHAR(),
               type_=sa.String(255),
               existing_nullable=True)
        batch_op.alter_column('description',
               existing_type=sa.VARCHAR(),
               type_=sa.Text(),
               existing_nullable=True)
        batch_op.alter_column('time_required',
               existing_type=sa.VARCHAR(),
               type_=sa.String(64),
               existing_nullable=True)

    with op.batch_alter_table('subtask', schema=None) as batch_op:
        batch_op.alter_column('description',
               existing_type=sa.VARCHAR(),
               type_=sa.Text(),
               existing_nullable=True)

    with op.batch_alter_table('note', schema=None) as batch_op:
        batch_op.alter_column('note',
               existing_type=sa.VARCHAR(),
               type_=sa.Text(),
               existing_nullable=True)

    with op.batch_alter_table("task__url__tool", schema=None) as batch_op:
        batch_op.alter_column(
            "name",
            existing_type=sa.VARCHAR(),
            type_=sa.String(length=64),
            existing_nullable=True,
        )

    with op.batch_alter_table("rulezet__rule", schema=None) as batch_op:
        batch_op.alter_column(
            "remote_id",
            existing_type=sa.VARCHAR(),
            type_=sa.String(length=36),
            existing_nullable=True,
        )
        batch_op.alter_column(
            "title",
            existing_type=sa.VARCHAR(),
            type_=sa.String(length=255),
            existing_nullable=True,
        )
        batch_op.alter_column(
            "description",
            existing_type=sa.VARCHAR(),
            type_=sa.Text(),
            existing_nullable=True,
        )
        batch_op.alter_column(
            "format",
            existing_type=sa.VARCHAR(),
            type_=sa.String(length=32),
            existing_nullable=True,
        )
        batch_op.alter_column(
            "version",
            existing_type=sa.VARCHAR(),
            type_=sa.String(length=64),
            existing_nullable=True,
        )

    with op.batch_alter_table("task__external__reference", schema=None) as batch_op:
        batch_op.alter_column(
            "url",
            existing_type=sa.VARCHAR(),
            type_=sa.String(length=8192),
            existing_nullable=True,
        )

    with op.batch_alter_table('org', schema=None) as batch_op:
        batch_op.alter_column('description',
               existing_type=sa.VARCHAR(),
               type_=sa.Text(),
               existing_nullable=True)

    with op.batch_alter_table('role', schema=None) as batch_op:
        batch_op.alter_column('description',
               existing_type=sa.VARCHAR(),
               type_=sa.Text(),
               existing_nullable=True)

    with op.batch_alter_table('alert', schema=None) as batch_op:
        batch_op.drop_index("ix_alert_message")
        batch_op.alter_column('message',
               existing_type=sa.VARCHAR(),
               type_=sa.Text(),
               existing_nullable=True)
        batch_op.alter_column(
            "webhook_url",
            existing_type=sa.VARCHAR(),
            type_=sa.String(length=8192),
            existing_nullable=True,
        )

    with op.batch_alter_table('notification', schema=None) as batch_op:
        batch_op.drop_index("ix_notification_message")
        batch_op.alter_column('message',
               existing_type=sa.VARCHAR(),
               type_=sa.Text(),
               existing_nullable=True)

    with op.batch_alter_table('case__template', schema=None) as batch_op:
        batch_op.alter_column('title',
               existing_type=sa.VARCHAR(),
               type_=sa.String(length=255),
               existing_nullable=True)
        batch_op.alter_column('description',
               existing_type=sa.VARCHAR(),
               type_=sa.Text(),
               existing_nullable=True)
        batch_op.alter_column('time_required',
               existing_type=sa.VARCHAR(),
               type_=sa.String(length=64),
               existing_nullable=True)
        batch_op.alter_column('notes',
               existing_type=sa.VARCHAR(),
               type_=sa.Text(),
               existing_nullable=True)

    with op.batch_alter_table('task__template', schema=None) as batch_op:
        batch_op.alter_column('title',
               existing_type=sa.VARCHAR(),
               type_=sa.String(length=255),
               existing_nullable=True)
        batch_op.alter_column('description',
               existing_type=sa.VARCHAR(),
               type_=sa.Text(),
               existing_nullable=True)
        batch_op.alter_column('time_required',
               existing_type=sa.VARCHAR(),
               type_=sa.String(length=64),
               existing_nullable=True)

    with op.batch_alter_table('subtask__template', schema=None) as batch_op:
        batch_op.alter_column('description',
               existing_type=sa.VARCHAR(),
               type_=sa.Text(),
               existing_nullable=True)

    with op.batch_alter_table('note__template', schema=None) as batch_op:
        batch_op.alter_column('note',
               existing_type=sa.VARCHAR(),
               type_=sa.Text(),
               existing_nullable=True)

    with op.batch_alter_table('task__template__url__tool', schema=None) as batch_op:
        batch_op.alter_column('name',
               existing_type=sa.VARCHAR(),
               type_=sa.String(length=64),
               existing_nullable=True)

    with op.batch_alter_table('taxonomy', schema=None) as batch_op:
        batch_op.alter_column('name',
               existing_type=sa.VARCHAR(),
               type_=sa.String(length=64),
               existing_nullable=True)
        batch_op.alter_column('description',
               existing_type=sa.VARCHAR(),
               type_=sa.Text(),
               existing_nullable=True)

    with op.batch_alter_table('tags', schema=None) as batch_op:
        batch_op.alter_column('name',
               existing_type=sa.VARCHAR(),
               type_=sa.Text(),
               existing_nullable=True)
        batch_op.alter_column('description',
               existing_type=sa.VARCHAR(),
               type_=sa.Text(),
               existing_nullable=True)
        batch_op.alter_column('color',
               existing_type=sa.VARCHAR(),
               type_=sa.String(length=16),
               existing_nullable=True)

    with op.batch_alter_table('galaxy', schema=None) as batch_op:
        batch_op.alter_column('name',
               existing_type=sa.VARCHAR(),
               type_=sa.String(length=64),
               existing_nullable=True)
        batch_op.alter_column('description',
               existing_type=sa.VARCHAR(),
               type_=sa.Text(),
               existing_nullable=True)
        batch_op.alter_column(
            "type",
            existing_type=sa.VARCHAR(),
            type_=sa.String(length=64),
            existing_nullable=True,
        )
        batch_op.alter_column(
            "icon",
            existing_type=sa.VARCHAR(),
            type_=sa.String(length=64),
            existing_nullable=True,
        )

    with op.batch_alter_table('cluster', schema=None) as batch_op:
        batch_op.alter_column('name',
               existing_type=sa.VARCHAR(),
               type_=sa.String(255),
               existing_nullable=True)
        batch_op.alter_column('description',
               existing_type=sa.VARCHAR(),
               type_=sa.Text(),
               existing_nullable=True)
        batch_op.alter_column('meta',
               existing_type=sa.VARCHAR(),
               type_=sa.Text().with_variant(
                   sa.dialects.mysql.LONGTEXT(),
                   "mysql",
                   "mariadb",
               ),
               existing_nullable=True)
        batch_op.alter_column('tag',
               existing_type=sa.VARCHAR(),
               type_=sa.String(255),
               existing_nullable=True)

    with op.batch_alter_table('connector', schema=None) as batch_op:
        batch_op.alter_column('description',
               existing_type=sa.VARCHAR(),
               type_=sa.Text(),
               existing_nullable=True)

    with op.batch_alter_table('connector__instance', schema=None) as batch_op:
        batch_op.alter_column('description',
               existing_type=sa.VARCHAR(),
               type_=sa.Text(),
               existing_nullable=True)

    with op.batch_alter_table('connector__icon', schema=None) as batch_op:
        batch_op.alter_column('description',
               existing_type=sa.VARCHAR(),
               type_=sa.Text(),
               existing_nullable=True)

    with op.batch_alter_table('case__connector__instance', schema=None) as batch_op:
        batch_op.alter_column('identifier',
               existing_type=sa.VARCHAR(),
               type_=sa.String(64),
               existing_nullable=True)

    with op.batch_alter_table('case__template__connector__instance', schema=None) as batch_op:
        batch_op.alter_column('identifier',
               existing_type=sa.VARCHAR(),
               type_=sa.String(64),
               existing_nullable=True)

    with op.batch_alter_table('task__connector__instance', schema=None) as batch_op:
        batch_op.alter_column('identifier',
               existing_type=sa.VARCHAR(),
               type_=sa.String(64),
               existing_nullable=True)

    with op.batch_alter_table('misp__module', schema=None) as batch_op:
        batch_op.alter_column('name',
               existing_type=sa.VARCHAR(),
               type_=sa.String(64),
               existing_nullable=True)
        batch_op.alter_column('description',
               existing_type=sa.VARCHAR(),
               type_=sa.Text(),
               existing_nullable=True)
        batch_op.alter_column('input_attr',
               existing_type=sa.VARCHAR(),
               type_=sa.Text(),
               existing_nullable=True)

    with op.batch_alter_table('misp__module__result', schema=None) as batch_op:
        batch_op.alter_column('query_enter',
               existing_type=sa.VARCHAR(),
               type_=sa.Text(),
               existing_nullable=True)
        batch_op.alter_column('input_query',
               existing_type=sa.VARCHAR(),
               type_=sa.Text(),
               existing_nullable=True)
        batch_op.alter_column('result',
               existing_type=sa.VARCHAR(),
               type_=sa.Text(),
               existing_nullable=True)
        batch_op.alter_column(
            "modules_list",
            existing_type=sa.VARCHAR(),
            type_=sa.Text(),
            existing_nullable=True,
        )

    with op.batch_alter_table('configurable__fields', schema=None) as batch_op:
        batch_op.alter_column('name',
               existing_type=sa.VARCHAR(),
               type_=sa.String(36),
               existing_nullable=True)

    with op.batch_alter_table('misp__module__config', schema=None) as batch_op:
        batch_op.alter_column(
            "value",
            existing_type=sa.VARCHAR(),
            type_=sa.String(255),
            existing_nullable=True
        )

    with op.batch_alter_table("custom__tags", schema=None) as batch_op:
        batch_op.alter_column(
            "name",
            existing_type=sa.VARCHAR(),
            type_=sa.String(length=64),
            existing_nullable=True,
        )
        batch_op.alter_column(
            "icon",
            existing_type=sa.VARCHAR(),
            type_=sa.String(length=64),
            existing_nullable=True,
        )

    with op.batch_alter_table("case__misp__object", schema=None) as batch_op:
        batch_op.alter_column(
            "name",
            existing_type=sa.VARCHAR(),
            type_=sa.String(length=64),
            existing_nullable=True,
        )

    with op.batch_alter_table('misp__attribute', schema=None) as batch_op:
        batch_op.alter_column('comment',
               existing_type=sa.VARCHAR(),
               type_=sa.Text(),
               existing_nullable=True)
        batch_op.alter_column('type',
               existing_type=sa.VARCHAR(),
               type_=sa.String(length=64),
               existing_nullable=True)
        batch_op.alter_column('object_relation',
               existing_type=sa.VARCHAR(),
               type_=sa.String(length=64),
               existing_nullable=True)
        batch_op.alter_column('value',
               existing_type=sa.VARCHAR(),
               type_=sa.String(length=255),
               existing_nullable=True)

    with op.batch_alter_table('note__template__model', schema=None) as batch_op:
        batch_op.alter_column('title',
               existing_type=sa.VARCHAR(),
               type_=sa.String(length=255),
               existing_nullable=True)
        batch_op.alter_column('description',
               existing_type=sa.VARCHAR(),
               type_=sa.Text(),
               existing_nullable=True)
        batch_op.alter_column('content',
               existing_type=sa.VARCHAR(),
               type_=sa.Text(),
               existing_nullable=True)

    with op.batch_alter_table('template__repository', schema=None) as batch_op:
        batch_op.alter_column('description',
               existing_type=sa.VARCHAR(),
               type_=sa.Text(),
               existing_nullable=True)

    with op.batch_alter_table('template__repository_entry', schema=None) as batch_op:
        batch_op.alter_column('description',
               existing_type=sa.VARCHAR(),
               type_=sa.Text(),
               existing_nullable=True)

    with op.batch_alter_table('case__note__template__model', schema=None) as batch_op:
        batch_op.alter_column('content',
               existing_type=sa.VARCHAR(),
               type_=sa.Text(),
               existing_nullable=True)

    with op.batch_alter_table('case__timeline__event', schema=None) as batch_op:
        batch_op.alter_column('description',
               existing_type=sa.VARCHAR(),
               type_=sa.Text(),
               existing_nullable=False)
        batch_op.alter_column('date_text',
               existing_type=sa.VARCHAR(),
               type_=sa.String(length=64),
               existing_nullable=True)

    with op.batch_alter_table('case__timeline__event__link', schema=None) as batch_op:
        batch_op.alter_column('label',
               existing_type=sa.VARCHAR(),
               type_=sa.String(length=128),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    with op.batch_alter_table("case__timeline__event__link", schema=None) as batch_op:
        batch_op.alter_column(
            "label",
            existing_type=sa.String(length=128),
            type_=sa.VARCHAR(),
            existing_nullable=True,
        )

    with op.batch_alter_table("case__timeline__event", schema=None) as batch_op:
        batch_op.alter_column(
            "description",
            existing_type=sa.Text(),
            type_=sa.VARCHAR(),
            existing_nullable=False,
        )
        batch_op.alter_column(
            "date_text",
            existing_type=sa.String(length=64),
            type_=sa.VARCHAR(),
            existing_nullable=True,
        )

    with op.batch_alter_table("case__note__template__model", schema=None) as batch_op:
        batch_op.alter_column(
            "content",
            existing_type=sa.Text(),
            type_=sa.VARCHAR(),
            existing_nullable=True,
        )

    with op.batch_alter_table("template__repository_entry", schema=None) as batch_op:
        batch_op.alter_column(
            "description",
            existing_type=sa.Text(),
            type_=sa.VARCHAR(),
            existing_nullable=True,
        )

    with op.batch_alter_table("template__repository", schema=None) as batch_op:
        batch_op.alter_column(
            "description",
            existing_type=sa.Text(),
            type_=sa.VARCHAR(),
            existing_nullable=True,
        )

    with op.batch_alter_table("note__template__model", schema=None) as batch_op:
        batch_op.alter_column(
            "title",
            existing_type=sa.String(length=255),
            type_=sa.VARCHAR(),
            existing_nullable=True,
        )
        batch_op.alter_column(
            "description",
            existing_type=sa.Text(),
            type_=sa.VARCHAR(),
            existing_nullable=True,
        )
        batch_op.alter_column(
            "content",
            existing_type=sa.Text(),
            type_=sa.VARCHAR(),
            existing_nullable=True,
        )

    with op.batch_alter_table("misp__attribute", schema=None) as batch_op:
        batch_op.alter_column(
            "comment",
            existing_type=sa.Text(),
            type_=sa.VARCHAR(),
            existing_nullable=True,
        )
        batch_op.alter_column(
            "type",
            existing_type=sa.String(length=64),
            type_=sa.VARCHAR(),
            existing_nullable=True,
        )
        batch_op.alter_column(
            "object_relation",
            existing_type=sa.String(length=64),
            type_=sa.VARCHAR(),
            existing_nullable=True,
        )
        batch_op.alter_column(
            "value",
            existing_type=sa.String(length=255),
            type_=sa.VARCHAR(),
            existing_nullable=True,
        )

    with op.batch_alter_table("case__misp__object", schema=None) as batch_op:
        batch_op.alter_column(
            "name",
            existing_type=sa.String(length=64),
            type_=sa.VARCHAR(),
            existing_nullable=True,
        )

    with op.batch_alter_table("custom__tags", schema=None) as batch_op:
        batch_op.alter_column(
            "name",
            existing_type=sa.String(length=64),
            type_=sa.VARCHAR(),
            existing_nullable=True,
        )
        batch_op.alter_column(
            "icon",
            existing_type=sa.String(length=64),
            type_=sa.VARCHAR(),
            existing_nullable=True,
        )

    with op.batch_alter_table("misp__module__config", schema=None) as batch_op:
        batch_op.alter_column(
            "value",
            existing_type=sa.String(length=255),
            type_=sa.VARCHAR(),
            existing_nullable=True,
        )

    with op.batch_alter_table("configurable__fields", schema=None) as batch_op:
        batch_op.alter_column(
            "name",
            existing_type=sa.String(length=36),
            type_=sa.VARCHAR(),
            existing_nullable=True,
        )

    with op.batch_alter_table("misp__module__result", schema=None) as batch_op:
        batch_op.alter_column(
            "query_enter",
            existing_type=sa.Text(),
            type_=sa.VARCHAR(),
            existing_nullable=True,
        )
        batch_op.alter_column(
            "input_query",
            existing_type=sa.Text(),
            type_=sa.VARCHAR(),
            existing_nullable=True,
        )
        batch_op.alter_column(
            "result",
            existing_type=sa.Text(),
            type_=sa.VARCHAR(),
            existing_nullable=True,
        )
        batch_op.alter_column(
            "modules_list",
            existing_type=sa.Text(),
            type_=sa.VARCHAR(),
            existing_nullable=True,
        )

    with op.batch_alter_table("misp__module", schema=None) as batch_op:
        batch_op.alter_column(
            "name",
            existing_type=sa.String(length=64),
            type_=sa.VARCHAR(),
            existing_nullable=True,
        )
        batch_op.alter_column(
            "description",
            existing_type=sa.Text(),
            type_=sa.VARCHAR(),
            existing_nullable=True,
        )
        batch_op.alter_column(
            "input_attr",
            existing_type=sa.Text(),
            type_=sa.VARCHAR(),
            existing_nullable=True,
        )

    with op.batch_alter_table("task__connector__instance", schema=None) as batch_op:
        batch_op.alter_column(
            "identifier",
            existing_type=sa.String(length=64),
            type_=sa.VARCHAR(),
            existing_nullable=True,
        )

    with op.batch_alter_table("case__template__connector__instance", schema=None) as batch_op:
        batch_op.alter_column(
            "identifier",
            existing_type=sa.String(length=64),
            type_=sa.VARCHAR(),
            existing_nullable=True,
        )

    with op.batch_alter_table("case__connector__instance", schema=None) as batch_op:
        batch_op.alter_column(
            "identifier",
            existing_type=sa.String(length=64),
            type_=sa.VARCHAR(),
            existing_nullable=True,
        )

    with op.batch_alter_table("connector__icon", schema=None) as batch_op:
        batch_op.alter_column(
            "description",
            existing_type=sa.Text(),
            type_=sa.VARCHAR(),
            existing_nullable=True,
        )

    with op.batch_alter_table("connector__instance", schema=None) as batch_op:
        batch_op.alter_column(
            "description",
            existing_type=sa.Text(),
            type_=sa.VARCHAR(),
            existing_nullable=True,
        )

    with op.batch_alter_table("connector", schema=None) as batch_op:
        batch_op.alter_column(
            "description",
            existing_type=sa.Text(),
            type_=sa.VARCHAR(),
            existing_nullable=True,
        )

    with op.batch_alter_table("cluster", schema=None) as batch_op:
        batch_op.alter_column(
            "name",
            existing_type=sa.String(length=255),
            type_=sa.VARCHAR(),
            existing_nullable=True,
        )
        batch_op.alter_column(
            "description",
            existing_type=sa.Text(),
            type_=sa.VARCHAR(),
            existing_nullable=True,
        )
        batch_op.alter_column(
            "meta",
            existing_type=sa.Text().with_variant(
                sa.dialects.mysql.LONGTEXT(),
                "mysql",
                "mariadb",
            ),
            type_=sa.VARCHAR(),
            existing_nullable=True,
        )
        batch_op.alter_column(
            "tag",
            existing_type=sa.String(length=255),
            type_=sa.VARCHAR(),
            existing_nullable=True,
        )

    with op.batch_alter_table("galaxy", schema=None) as batch_op:
        batch_op.alter_column(
            "name",
            existing_type=sa.String(length=64),
            type_=sa.VARCHAR(),
            existing_nullable=True,
        )
        batch_op.alter_column(
            "description",
            existing_type=sa.Text(),
            type_=sa.VARCHAR(),
            existing_nullable=True,
        )
        batch_op.alter_column(
            "type",
            existing_type=sa.String(length=64),
            type_=sa.VARCHAR(),
            existing_nullable=True,
        )
        batch_op.alter_column(
            "icon",
            existing_type=sa.String(length=64),
            type_=sa.VARCHAR(),
            existing_nullable=True,
        )

    with op.batch_alter_table("tags", schema=None) as batch_op:
        batch_op.alter_column(
            "name",
            existing_type=sa.Text(),
            type_=sa.VARCHAR(),
            existing_nullable=True,
        )
        batch_op.alter_column(
            "description",
            existing_type=sa.Text(),
            type_=sa.VARCHAR(),
            existing_nullable=True,
        )
        batch_op.alter_column(
            "color",
            existing_type=sa.String(length=16),
            type_=sa.VARCHAR(),
            existing_nullable=True,
        )

    with op.batch_alter_table("taxonomy", schema=None) as batch_op:
        batch_op.alter_column(
            "name",
            existing_type=sa.String(length=64),
            type_=sa.VARCHAR(),
            existing_nullable=True,
        )
        batch_op.alter_column(
            "description",
            existing_type=sa.Text(),
            type_=sa.VARCHAR(),
            existing_nullable=True,
        )

    with op.batch_alter_table("task__template__url__tool", schema=None) as batch_op:
        batch_op.alter_column(
            "name",
            existing_type=sa.String(length=64),
            type_=sa.VARCHAR(),
            existing_nullable=True,
        )

    with op.batch_alter_table("note__template", schema=None) as batch_op:
        batch_op.alter_column(
            "note",
            existing_type=sa.Text(),
            type_=sa.VARCHAR(),
            existing_nullable=True,
        )

    with op.batch_alter_table("subtask__template", schema=None) as batch_op:
        batch_op.alter_column(
            "description",
            existing_type=sa.Text(),
            type_=sa.VARCHAR(),
            existing_nullable=True,
        )

    with op.batch_alter_table("task__template", schema=None) as batch_op:
        batch_op.alter_column(
            "title",
            existing_type=sa.String(length=255),
            type_=sa.VARCHAR(),
            existing_nullable=True,
        )
        batch_op.alter_column(
            "description",
            existing_type=sa.Text(),
            type_=sa.VARCHAR(),
            existing_nullable=True,
        )
        batch_op.alter_column(
            "time_required",
            existing_type=sa.String(length=64),
            type_=sa.VARCHAR(),
            existing_nullable=True,
        )

    with op.batch_alter_table("case__template", schema=None) as batch_op:
        batch_op.alter_column(
            "title",
            existing_type=sa.String(length=255),
            type_=sa.VARCHAR(),
            existing_nullable=True,
        )
        batch_op.alter_column(
            "description",
            existing_type=sa.Text(),
            type_=sa.VARCHAR(),
            existing_nullable=True,
        )
        batch_op.alter_column(
            "time_required",
            existing_type=sa.String(length=64),
            type_=sa.VARCHAR(),
            existing_nullable=True,
        )
        batch_op.alter_column(
            "notes",
            existing_type=sa.Text(),
            type_=sa.VARCHAR(),
            existing_nullable=True,
        )

    with op.batch_alter_table("notification", schema=None) as batch_op:
        batch_op.alter_column(
            "message",
            existing_type=sa.Text(),
            type_=sa.VARCHAR(),
            existing_nullable=True,
        )
        batch_op.create_index(
            "ix_notification_message",
            ["message"],
            unique=False,
        )

    with op.batch_alter_table("alert", schema=None) as batch_op:
        batch_op.alter_column(
            "message",
            existing_type=sa.Text(),
            type_=sa.VARCHAR(),
            existing_nullable=True,
        )
        batch_op.alter_column(
            "webhook_url",
            existing_type=sa.String(length=8192),
            type_=sa.VARCHAR(),
            existing_nullable=True,
        )
        batch_op.create_index(
            "ix_alert_message",
            ["message"],
            unique=False,
        )

    with op.batch_alter_table("role", schema=None) as batch_op:
        batch_op.alter_column(
            "description",
            existing_type=sa.Text(),
            type_=sa.VARCHAR(),
            existing_nullable=True,
        )

    with op.batch_alter_table("org", schema=None) as batch_op:
        batch_op.alter_column(
            "description",
            existing_type=sa.Text(),
            type_=sa.VARCHAR(),
            existing_nullable=True,
        )

    with op.batch_alter_table("task__external__reference", schema=None) as batch_op:
        batch_op.alter_column(
            "url",
            existing_type=sa.String(length=8192),
            type_=sa.VARCHAR(),
            existing_nullable=True,
        )

    with op.batch_alter_table("rulezet__rule", schema=None) as batch_op:
        batch_op.alter_column(
            "remote_id",
            existing_type=sa.String(length=36),
            type_=sa.VARCHAR(),
            existing_nullable=True,
        )
        batch_op.alter_column(
            "title",
            existing_type=sa.String(length=255),
            type_=sa.VARCHAR(),
            existing_nullable=True,
        )
        batch_op.alter_column(
            "description",
            existing_type=sa.Text(),
            type_=sa.VARCHAR(),
            existing_nullable=True,
        )
        batch_op.alter_column(
            "format",
            existing_type=sa.String(length=32),
            type_=sa.VARCHAR(),
            existing_nullable=True,
        )
        batch_op.alter_column(
            "version",
            existing_type=sa.String(length=64),
            type_=sa.VARCHAR(),
            existing_nullable=True,
        )

    with op.batch_alter_table("task__url__tool", schema=None) as batch_op:
        batch_op.alter_column(
            "name",
            existing_type=sa.String(length=64),
            type_=sa.VARCHAR(),
            existing_nullable=True,
        )

    with op.batch_alter_table("subtask", schema=None) as batch_op:
        batch_op.alter_column(
            "description",
            existing_type=sa.Text(),
            type_=sa.VARCHAR(),
            existing_nullable=True,
        )

    with op.batch_alter_table("task", schema=None) as batch_op:
        batch_op.alter_column(
            "title",
            existing_type=sa.String(length=255),
            type_=sa.VARCHAR(),
            existing_nullable=True,
        )
        batch_op.alter_column(
            "description",
            existing_type=sa.Text(),
            type_=sa.VARCHAR(),
            existing_nullable=True,
        )
        batch_op.alter_column(
            "time_required",
            existing_type=sa.String(length=64),
            type_=sa.VARCHAR(),
            existing_nullable=True,
        )

    with op.batch_alter_table("case", schema=None) as batch_op:
        batch_op.alter_column(
            "title",
            existing_type=sa.String(length=255),
            type_=sa.VARCHAR(),
            existing_nullable=True,
        )
        batch_op.alter_column(
            "description",
            existing_type=sa.Text(),
            type_=sa.VARCHAR(),
            existing_nullable=True,
        )
        batch_op.alter_column(
            "notes",
            existing_type=sa.Text(),
            type_=sa.VARCHAR(),
            existing_nullable=True,
        )
        batch_op.alter_column(
            "hedgedoc_url",
            existing_type=sa.String(length=255),
            type_=sa.VARCHAR(),
            existing_nullable=True,
        )
        batch_op.alter_column(
            "time_required",
            existing_type=sa.String(length=64),
            type_=sa.VARCHAR(),
            existing_nullable=True,
        )
        batch_op.alter_column(
            "computer_assistate_report",
            existing_type=sa.Text().with_variant(
                sa.dialects.mysql.LONGTEXT(),
                "mysql",
                "mariadb",
            ),
            type_=sa.VARCHAR(),
            existing_nullable=True,
        )
        batch_op.alter_column(
            "computer_assistate_model",
            existing_type=sa.String(length=64),
            type_=sa.VARCHAR(),
            existing_nullable=True,
        )
        batch_op.alter_column(
            "ticket_id",
            existing_type=sa.String(length=128),
            type_=sa.VARCHAR(),
            existing_nullable=True,
        )

    with op.batch_alter_table("user", schema=None) as batch_op:
        batch_op.alter_column(
            "matrix_id",
            existing_type=sa.String(length=64),
            type_=sa.VARCHAR(),
            existing_nullable=True,
        )

