"""empty message

Revision ID: c42cd6e3e1ea
Revises: 1c4ba5044f75
Create Date: 2023-12-06 09:48:39.994520

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy import inspect


# revision identifiers, used by Alembic.
revision = 'c42cd6e3e1ea'
down_revision = '1c4ba5044f75'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # Check what exists before making changes
    bind = op.get_bind()
    inspector = inspect(bind)
    existing_tables = inspector.get_table_names()
    
    # Create task__connector__instance table if it doesn't exist
    if 'task__connector__instance' not in existing_tables:
        op.create_table('task__connector__instance',
        sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
        sa.Column('task_id', sa.Integer(), nullable=True),
        sa.Column('instance_id', sa.Integer(), nullable=True),
        sa.PrimaryKeyConstraint('id')
        )
        op.create_index('ix_task__connector__instance_instance_id', 'task__connector__instance', ['instance_id'], unique=False)
        op.create_index('ix_task__connector__instance_task_id', 'task__connector__instance', ['task_id'], unique=False)
    else:
        print("Table 'task__connector__instance' already exists")

    # Drop task__connector table if it exists
    if 'task__connector' in existing_tables:
        # Drop indexes first if they exist
        try:
            op.drop_index('ix_task__connector_connector_id', 'task__connector')
        except:
            pass
        try:
            op.drop_index('ix_task__connector_task_id', 'task__connector')
        except:
            pass
        op.drop_table('task__connector')
    else:
        print("Table 'task__connector' already dropped")
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('task__connector',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('task_id', sa.INTEGER(), nullable=True),
    sa.Column('connector_id', sa.INTEGER(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('task__connector', schema=None) as batch_op:
        batch_op.create_index('ix_task__connector_task_id', ['task_id'], unique=False)
        batch_op.create_index('ix_task__connector_connector_id', ['connector_id'], unique=False)

    with op.batch_alter_table('task__connector__instance', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_task__connector__instance_task_id'))
        batch_op.drop_index(batch_op.f('ix_task__connector__instance_instance_id'))

    op.drop_table('task__connector__instance')
    # ### end Alembic commands ###
