"""empty message

Revision ID: c45dc323e50c
Revises: a7c2f8e91d03
Create Date: 2026-05-05 15:46:22.491808

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c45dc323e50c'
down_revision = 'a7c2f8e91d03'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    bind = op.get_bind()
    inspector = sa.inspect(bind)
    existing_tables = inspector.get_table_names()

    if 'alert' not in existing_tables:
        op.create_table('alert',
        sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
        sa.Column('case_id', sa.Integer(), nullable=True),
        sa.Column('message', sa.String(), nullable=True),
        sa.Column('status', sa.String(length=30), nullable=True),
        sa.Column('creation_date', sa.DateTime(), nullable=True),
        sa.Column('is_read', sa.Boolean(), nullable=True),
        sa.Column('webhook_url', sa.String(), nullable=True),
        sa.Column('webhook_status', sa.Integer(), nullable=True),
        sa.PrimaryKeyConstraint('id')
        )
        with op.batch_alter_table('alert', schema=None) as batch_op:
            batch_op.create_index(batch_op.f('ix_alert_case_id'), ['case_id'], unique=False)
            batch_op.create_index(batch_op.f('ix_alert_creation_date'), ['creation_date'], unique=False)
            batch_op.create_index(batch_op.f('ix_alert_message'), ['message'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    bind = op.get_bind()
    inspector = sa.inspect(bind)
    existing_tables = inspector.get_table_names()

    if 'alert' in existing_tables:
        with op.batch_alter_table('alert', schema=None) as batch_op:
            batch_op.drop_index(batch_op.f('ix_alert_message'))
            batch_op.drop_index(batch_op.f('ix_alert_creation_date'))
            batch_op.drop_index(batch_op.f('ix_alert_case_id'))

        op.drop_table('alert')
    # ### end Alembic commands ###
