"""empty message

Revision ID: cff3c5e46550
Revises: a878d2c91115
Create Date: 2023-11-03 11:24:30.309808

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cff3c5e46550'
down_revision = 'a878d2c91115'
branch_labels = None
depends_on = None

naming_convention = {
    "ix": 'ix_%(column_0_label)s',
    "uq": "uq_%(table_name)s_%(column_0_name)s",
    "ck": "ck_%(table_name)s_%(column_0_name)s",
    "fk": "fk_%(table_name)s_%(column_0_name)s_%(referred_table_name)s",
    "pk": "pk_%(table_name)s"
}


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('taxonomy',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('description', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('tags', schema=None, naming_convention=naming_convention) as batch_op:
        batch_op.add_column(sa.Column('taxonomy_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key('fk_tags_taxonomy_id_taxonomy', 'taxonomy', ['taxonomy_id'], ['id'], ondelete='CASCADE')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tags', schema=None, naming_convention=naming_convention) as batch_op:
        batch_op.drop_constraint('fk_tags_taxonomy_id_taxonomy', type_='foreignkey')
        batch_op.drop_column('taxonomy_id')

    op.drop_table('taxonomy')
    # ### end Alembic commands ###
