"""empty message

Revision ID: d46002a5f863
Revises: 698d53567382
Create Date: 2025-07-28 14:23:48.589797

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy import inspect
from sqlalchemy.exc import OperationalError


# revision identifiers, used by Alembic.
revision = 'd46002a5f863'
down_revision = '698d53567382'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    bind = op.get_bind()
    inspector = inspect(bind)
    existing_columns = [col['name'] for col in inspector.get_columns('task__url__tool')]
    
    if 'uuid' not in existing_columns:
        op.add_column('task__url__tool', sa.Column('uuid', sa.String(length=36), nullable=True))
        op.create_index('ix_task__url__tool_uuid', 'task__url__tool', ['uuid'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    bind = op.get_bind()
    inspector = inspect(bind)
    existing_columns = [col['name'] for col in inspector.get_columns('task__url__tool')]
    
    if 'uuid' in existing_columns:
        existing_indexes = [idx['name'] for idx in inspector.get_indexes('task__url__tool')]
        if 'ix_task__url__tool_uuid' in existing_indexes:
            op.drop_index('ix_task__url__tool_uuid', table_name='task__url__tool')
        op.drop_column('task__url__tool', 'uuid')

    # ### end Alembic commands ###
