"""add_connector_sync_log

Revision ID: d8d9c6285852
Revises: e1f2a3b4c5d6
Create Date: 2026-04-29 15:25:18.082697

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd8d9c6285852'
down_revision = 'e1f2a3b4c5d6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('connector__sync__log',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('case_id', sa.Integer(), nullable=True),
    sa.Column('case_connector_instance_id', sa.Integer(), nullable=True),
    sa.Column('direction', sa.String(length=10), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.Column('status', sa.String(length=10), nullable=True),
    sa.Column('message', sa.Text(), nullable=True),
    sa.Column('objects_synced', sa.Integer(), nullable=True),
    sa.Column('objects_failed', sa.Integer(), nullable=True),
    sa.Column('details', sa.JSON(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('connector__sync__log', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_connector__sync__log_case_connector_instance_id'), ['case_connector_instance_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_connector__sync__log_case_id'), ['case_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_connector__sync__log_timestamp'), ['timestamp'], unique=False)

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_user_role_id'), type_='foreignkey')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.create_foreign_key(batch_op.f('fk_user_role_id'), 'role', ['role_id'], ['id'])

    with op.batch_alter_table('connector__sync__log', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_connector__sync__log_timestamp'))
        batch_op.drop_index(batch_op.f('ix_connector__sync__log_case_id'))
        batch_op.drop_index(batch_op.f('ix_connector__sync__log_case_connector_instance_id'))

    op.drop_table('connector__sync__log')
    # ### end Alembic commands ###
