"""empty message

Revision ID: d914b6b4c07d
Revises: 0ca756cb8128
Create Date: 2024-01-26 14:51:54.864032

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy import inspect


# revision identifiers, used by Alembic.
revision = 'd914b6b4c07d'
down_revision = '0ca756cb8128'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
	bind = op.get_bind()
	inspector = inspect(bind)
	existing_columns = [col['name'] for col in inspector.get_columns('case__task__template')]
	
	if 'case_order_id' not in existing_columns:
		op.add_column('case__task__template', sa.Column('case_order_id', sa.Integer(), nullable=True))
		op.create_index('ix_case__task__template_case_order_id', 'case__task__template', ['case_order_id'], unique=False)

	# Connexion à la base de données (utilisez votre moteur de base de données)
	connection = op.get_bind()

	# Sélectionnez toutes les lignes de la table users
	cases_templates = connection.execute(sa.text("SELECT id FROM case__template")).fetchall()

    # Incrémentation du compteur pour chaque utilisateur
	for case_ in cases_templates:
		case_task_template = connection.execute(sa.text(f"SELECT task_id FROM case__task__template WHERE case_id={case_.id}")).fetchall()
		cp = 1
		for tasks_ids in case_task_template:
			connection.execute(
				sa.text(f"UPDATE case__task__template SET case_order_id = {cp} WHERE task_id = {tasks_ids.task_id}")
			)
			cp += 1

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('case__task__template', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_case__task__template_case_order_id'))
        batch_op.drop_column('case_order_id')

    # ### end Alembic commands ###
