"""empty message

Revision ID: d9c47465de6e
Revises: 871d6b7ad0c7
Create Date: 2024-05-29 13:37:38.408165

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd9c47465de6e'
down_revision = '871d6b7ad0c7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('analyzer',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=64), nullable=True),
    sa.Column('url', sa.String(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('analyzer', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_analyzer_name'), ['name'], unique=True)
        batch_op.create_index(batch_op.f('ix_analyzer_url'), ['url'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('analyzer', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_analyzer_url'))
        batch_op.drop_index(batch_op.f('ix_analyzer_name'))

    op.drop_table('analyzer')
    # ### end Alembic commands ###
