"""empty message

Revision ID: dde56729b9d4
Revises: d8d9c6285852
Create Date: 2026-05-05 09:36:50.271540

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'dde56729b9d4'
down_revision = 'd8d9c6285852'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    bind = op.get_bind()
    inspector = sa.inspect(bind)
    existing_tables = inspector.get_table_names()

    if 'chat_conversation' not in existing_tables:
        op.create_table('chat_conversation',
        sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
        sa.Column('user_id', sa.Integer(), nullable=False),
        sa.Column('title', sa.String(length=200), nullable=False),
        sa.Column('created_at', sa.DateTime(), nullable=True),
        sa.Column('updated_at', sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(['user_id'], ['user.id'], ondelete='CASCADE'),
        sa.PrimaryKeyConstraint('id')
        )
        with op.batch_alter_table('chat_conversation', schema=None) as batch_op:
            batch_op.create_index(batch_op.f('ix_chat_conversation_user_id'), ['user_id'], unique=False)

    if 'chat_message' not in existing_tables:
        op.create_table('chat_message',
        sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
        sa.Column('conversation_id', sa.Integer(), nullable=False),
        sa.Column('role', sa.String(length=10), nullable=False),
        sa.Column('content', sa.Text(), nullable=False),
        sa.Column('created_at', sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(['conversation_id'], ['chat_conversation.id'], ondelete='CASCADE'),
        sa.PrimaryKeyConstraint('id')
        )
        with op.batch_alter_table('chat_message', schema=None) as batch_op:
            batch_op.create_index(batch_op.f('ix_chat_message_conversation_id'), ['conversation_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    bind = op.get_bind()
    inspector = sa.inspect(bind)
    existing_tables = inspector.get_table_names()

    if 'chat_message' in existing_tables:
        with op.batch_alter_table('chat_message', schema=None) as batch_op:
            batch_op.drop_index(batch_op.f('ix_chat_message_conversation_id'))

        op.drop_table('chat_message')

    if 'chat_conversation' in existing_tables:
        with op.batch_alter_table('chat_conversation', schema=None) as batch_op:
            batch_op.drop_index(batch_op.f('ix_chat_conversation_user_id'))

        op.drop_table('chat_conversation')
    # ### end Alembic commands ###
