"""empty message

Revision ID: decb78ddf061
Revises: cff3c5e46550
Create Date: 2023-11-03 15:16:27.985659

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.exc import OperationalError


# revision identifiers, used by Alembic.
revision = 'decb78ddf061'
down_revision = 'cff3c5e46550'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    try:
        with op.batch_alter_table('tags', schema=None) as batch_op:
            batch_op.add_column(sa.Column('exclude', sa.Boolean(), nullable=True))
    except OperationalError:
        print("Column 'exclude' already exist in 'tags'")

    try:
        with op.batch_alter_table('taxonomy', schema=None) as batch_op:
            batch_op.add_column(sa.Column('exclude', sa.Boolean(), nullable=True))
    except OperationalError:
        print("Column 'exclude' already exist in 'taxonomy'")

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('taxonomy', schema=None) as batch_op:
        batch_op.drop_column('exclude')

    with op.batch_alter_table('tags', schema=None) as batch_op:
        batch_op.drop_column('exclude')

    # ### end Alembic commands ###
