"""empty message

Revision ID: e38bec5037d7
Revises: 69e305fdc1b8
Create Date: 2024-08-20 11:44:22.875561

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.exc import OperationalError


# revision identifiers, used by Alembic.
revision = 'e38bec5037d7'
down_revision = '69e305fdc1b8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    try:
        with op.batch_alter_table('analyzer__result', schema=None) as batch_op:
            batch_op.add_column(sa.Column('result', sa.String(), nullable=True))
    except OperationalError:
        print("Column 'result' already exist in 'analyzer__result'")

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('analyzer__result', schema=None) as batch_op:
        batch_op.drop_column('result')

    # ### end Alembic commands ###
