"""empty message

Revision ID: e38bec5037d7
Revises: 69e305fdc1b8
Create Date: 2024-08-20 11:44:22.875561

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy import inspect


# revision identifiers, used by Alembic.
revision = 'e38bec5037d7'
down_revision = '69e305fdc1b8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    bind = op.get_bind()
    inspector = inspect(bind)
    existing_columns = [col['name'] for col in inspector.get_columns('analyzer__result')]
    
    if 'result' not in existing_columns:
        op.add_column('analyzer__result', sa.Column('result', sa.String(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('analyzer__result', schema=None) as batch_op:
        batch_op.drop_column('result')

    # ### end Alembic commands ###
