"""Add Case_Timeline_Event table

Revision ID: ebb8b017a285
Revises: c3d4e5f6a7b8
Create Date: 2026-03-30 12:04:04.162601

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ebb8b017a285'
down_revision = 'c3d4e5f6a7b8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###

    bind = op.get_bind()
    inspector = sa.inspect(bind)
    existing_tables = inspector.get_table_names()

    if 'case__timeline__event' not in existing_tables:
        op.create_table('case__timeline__event',
        sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
        sa.Column('case_id', sa.Integer(), nullable=True),
        sa.Column('date_text', sa.String(), nullable=False),
        sa.Column('date_parsed', sa.DateTime(), nullable=True),
        sa.Column('description', sa.String(), nullable=False),
        sa.Column('misp_object_id', sa.Integer(), nullable=True),
        sa.Column('creation_date', sa.DateTime(), nullable=True),
        sa.PrimaryKeyConstraint('id')
        )
        with op.batch_alter_table('case__timeline__event', schema=None) as batch_op:
            batch_op.create_index(batch_op.f('ix_case__timeline__event_case_id'), ['case_id'], unique=False)
            batch_op.create_index(batch_op.f('ix_case__timeline__event_creation_date'), ['creation_date'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###

    bind = op.get_bind()
    inspector = sa.inspect(bind)
    existing_tables = inspector.get_table_names()

    if 'case__timeline__event' in existing_tables:
        with op.batch_alter_table('case__timeline__event', schema=None) as batch_op:
            batch_op.drop_index(batch_op.f('ix_case__timeline__event_creation_date'))
            batch_op.drop_index(batch_op.f('ix_case__timeline__event_case_id'))

        op.drop_table('case__timeline__event')
    # ### end Alembic commands ###
