"""empty message

Revision ID: f0c8b2c9e75d
Revises: eab5ed1e3fb1
Create Date: 2025-11-18 12:45:24.337154

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f0c8b2c9e75d'
down_revision = 'eab5ed1e3fb1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    bind = op.get_bind()
    inspector = sa.inspect(bind)
    existing_columns = [col['name'] for col in inspector.get_columns('case')]

    if not 'computer_assistate_report' in existing_columns:
        with op.batch_alter_table('case', schema=None) as batch_op:
            batch_op.add_column(sa.Column('computer_assistate_report', sa.String(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    bind = op.get_bind()
    inspector = sa.inspect(bind)
    existing_columns = [col['name'] for col in inspector.get_columns('case')]
    
    if 'computer_assistate_report' in existing_columns:
        with op.batch_alter_table('case', schema=None) as batch_op:
            batch_op.drop_column('computer_assistate_report')

    # ### end Alembic commands ###
