"""empty message

Revision ID: f8c4a065648d
Revises: 3567475b1063
Create Date: 2026-04-07 09:17:22.032945

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f8c4a065648d'
down_revision = '3567475b1063'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    conn = op.get_bind()
    inspector = sa.inspect(conn)
    tables = inspector.get_table_names()

    if 'rulezet__rule' not in tables:
        op.create_table('rulezet__rule',
        sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
        sa.Column('uuid', sa.String(length=36), nullable=True),
        sa.Column('case_id', sa.Integer(), nullable=True),
        sa.Column('instance_id', sa.Integer(), nullable=True),
        sa.Column('remote_id', sa.String(), nullable=True),
        sa.Column('title', sa.String(), nullable=True),
        sa.Column('description', sa.String(), nullable=True),
        sa.Column('format', sa.String(), nullable=True),
        sa.Column('content', sa.Text(), nullable=True),
        sa.Column('version', sa.String(), nullable=True),
        sa.Column('date_added', sa.DateTime(), nullable=True),
        sa.PrimaryKeyConstraint('id')
        )
        with op.batch_alter_table('rulezet__rule', schema=None) as batch_op:
            batch_op.create_index(batch_op.f('ix_rulezet__rule_case_id'), ['case_id'], unique=False)
            batch_op.create_index(batch_op.f('ix_rulezet__rule_date_added'), ['date_added'], unique=False)
            batch_op.create_index(batch_op.f('ix_rulezet__rule_instance_id'), ['instance_id'], unique=False)
            batch_op.create_index(batch_op.f('ix_rulezet__rule_remote_id'), ['remote_id'], unique=False)
            batch_op.create_index(batch_op.f('ix_rulezet__rule_uuid'), ['uuid'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    conn = op.get_bind()
    inspector = sa.inspect(conn)
    tables = inspector.get_table_names()

    if 'rulezet__rule' in tables:
        with op.batch_alter_table('rulezet__rule', schema=None) as batch_op:
            batch_op.drop_index(batch_op.f('ix_rulezet__rule_uuid'))
            batch_op.drop_index(batch_op.f('ix_rulezet__rule_remote_id'))
            batch_op.drop_index(batch_op.f('ix_rulezet__rule_instance_id'))
            batch_op.drop_index(batch_op.f('ix_rulezet__rule_date_added'))
            batch_op.drop_index(batch_op.f('ix_rulezet__rule_case_id'))

        op.drop_table('rulezet__rule')
    # ### end Alembic commands ###
